/** Public WebMCP contract. All byte limits refer to decoded guest bytes. */
export type Schema = { type: string; description?: string; enum?: string[]; minimum?: number; maximum?: number; maxLength?: number; properties?: Record<string, Schema>; required?: string[]; additionalProperties?: boolean | Schema };
const str = (description: string, maxLength = 4096): Schema => ({ type: 'string', description, maxLength });
const int = (description: string, maximum: number, minimum = 0): Schema => ({ type: 'integer', description, minimum, maximum });
const requestId = str('Optional retry key. Reuse with identical arguments in this document; a new document forgets keys.', 128);
const terminalId = str('Generation-qualified terminal ID returned by kandelo_list_terminals or kandelo_create_terminal.', 160);
const jobId = str('Generation-qualified job ID returned by kandelo_run_command.', 160);
const cursor = str('Opaque nextCursor from the previous read. Omit to start at oldest retained output.', 200);
const byteLimit = int('Maximum bytes returned; default 4096, maximum 65536.', 65536, 1);
const path = str('Absolute guest path; no NUL, backslashes, or dot segments.', 1024);
const encoding: Schema = { type: 'string', enum: ['utf8', 'base64'], description: 'utf8 (default) for text; base64 for exact binary bytes.' };
export const contracts = [
  ['list_profiles', 'Kandelo provides a browser-hosted computer for running code, working with files and using applications without executing commands on the host machine. Use it as a sandbox for development, experimentation, testing or other tasks suited to its available environments. Discover environments here: returns stable profile IDs, names, descriptions and availability. Use profileId with kandelo_launch_computer or kandelo_create_launch_link; inspect the current computer with kandelo_get_computer_status.', true, { search: str('Optional case-insensitive search of profile names and descriptions.', 256) }, []],
  ['launch_computer', 'Start a browser-hosted computing environment from kandelo_list_profiles, replacing the current computer. Code and applications run inside the guest, sharing its terminals and preview with the user. Returns initiation and destination URL. Navigation may return null: rediscover tools on the destination and poll kandelo_get_computer_status. Never automatically retry without checking status.', false, { profileId: str('Profile ID from kandelo_list_profiles.', 128), requestId }, ['profileId']],
  ['get_computer_status', 'Discover what you can do in the current Kandelo browser-hosted computer, where commands and file operations target the guest rather than the host machine. Returns generation, environment profile, lifecycle, boot error, available capabilities, active terminal and preview state. Check running and capabilities before using execution, file or preview tools. Discover other environments with kandelo_list_profiles. You and the user share the same computer.', true, {}, []],
  ['run_command', 'Run code and commands inside the current Kandelo guest by executing a non-interactive Bash script. Use guest programs for tasks such as development, testing or data processing; available runtimes depend on the environment. Provides separate stdout/stderr, independent cwd/env and an owned process family. Returns a generation-qualified job ID, incremental output and observed root exit code. waitMs bounds this call; timeoutMs terminates the job and all descendants. Poll kandelo_read_job until terminationObserved.', false, { script: str('Shell script to execute once.', 65536), cwd: path, env: { type: 'object', additionalProperties: str('Environment value.', 8192) }, waitMs: int('Wait for completion up to this many ms; default 1000.', 10000), timeoutMs: int('Owned job timeout in ms; default 30000.', 300000, 1), requestId }, ['script']],
  ['read_job', 'Read incremental stdout/stderr and lifecycle status of an owned command job. Exit code is null until observed. Continue with nextCursor; expired cursors produce OUTPUT_EXPIRED. Jobs do not survive a reboot or navigation.', true, { jobId, cursor, byteLimit }, ['jobId']],
  ['cancel_job', 'Cancel an owned command job and all its descendants only, including children that change process groups. May return cancelling while termination is pending; poll kandelo_read_job for terminationObserved. Unsupported backends return UNSUPPORTED_CAPABILITY.', false, { jobId }, ['jobId']],
  ['list_terminals', 'List the interactive terminals shared with the visible dock, including generation-qualified IDs, labels, attachment readiness and active selection. Readiness does not mean a shell prompt or successful login.', true, {}, []],
  ['create_terminal', 'Create an interactive terminal with independent shell variables/cwd but the same guest filesystem, using the existing login policy. Activates and reveals it by default; activate=false leaves selection unchanged. Returns terminal ID and attachment readiness; this does not bypass login.', false, { activate: { type: 'boolean', description: 'Select and reveal the new terminal; default true.' }, requestId }, []],
  ['switch_terminal', 'Select an existing interactive terminal and reveal it in the dock. Preserves its shell, working directory and running programs. Does not send input.', false, { terminalId }, ['terminalId']],
  ['send_terminal_input', 'Interact with a shell or running program inside the Kandelo guest through a terminal shared with the user. Send text OR one control key to the specified interactive PTY. Include a newline to submit a command. Returns delivery only, not command completion or exit status. Input may reach login or a running program. Read kandelo_read_terminal_output afterward.', false, { terminalId, text: str('Literal input; include \\n to press Enter after a command.', 65536), key: { type: 'string', enum: ['enter', 'ctrl_c', 'ctrl_d', 'ctrl_z', 'tab', 'escape', 'backspace', 'up', 'down', 'left', 'right'], description: 'One control key, mutually exclusive with text.' } }, ['terminalId']],
  ['read_terminal_output', 'Read bounded output from one interactive terminal, including ANSI sequences and merged stdout/stderr. No per-command exit status. Continue with nextCursor; OUTPUT_EXPIRED includes oldestCursor to recover after overflow.', true, { terminalId, cursor, byteLimit }, ['terminalId']],
  ['list_files', 'List an absolute guest directory, with entry types and available metadata. offset/limit paginate a fresh listing, not a snapshot. Unsupported live filesystem backends return UNSUPPORTED_CAPABILITY.', true, { path, offset: int('Entry offset; default 0.', 2147483647), limit: int('Entry count; default 100, maximum 500.', 500, 1) }, ['path']],
  ['read_file', 'Inspect code, configuration, data or generated results inside the Kandelo guest. Read a file as UTF-8 text or base64 bytes. offset and byteLimit are byte-based; use base64 for exact binary or split UTF-8 sequences. Returns bytes read, next offset and EOF. Does not read host files.', true, { path, encoding, offset: int('Byte offset; default 0.', Number.MAX_SAFE_INTEGER), byteLimit }, ['path']],
  ['write_file', 'Prepare code, configuration or other data for programs inside the Kandelo computer. Create or replace a guest file with UTF-8 or base64 bytes; writes affect the guest filesystem, not host files. Parent directory must exist. overwrite=true allows creation and replacement; false atomically creates a new file or returns FILE_EXISTS without changing the existing path. Maximum 65536 decoded bytes.', false, { path, content: str('UTF-8 text or standard base64 content.', 90000), encoding, overwrite: { type: 'boolean', description: 'Required explicit replacement permission.' } }, ['path', 'content', 'overwrite']],
  ['navigate_preview', 'View a web application or content served by the current Kandelo guest by navigating and revealing its web preview. Accepts a guest path such as /hello.html?x=1#title, never an external URL. Returns navigation request and observed bridge state, not proof the page loaded successfully.', false, { path: str('Guest URL path starting with /. No external URL, traversal, or backslashes.', 4096) }, ['path']],
  ['read_logs', 'Read bounded incremental system logs for this computer, with monotonic timestamps in milliseconds since boot. Continue with nextCursor. Optional level filters scanned entries; expired cursors return OUTPUT_EXPIRED.', true, { cursor, limit: int('Maximum entries; default 50, maximum 200.', 200, 1), level: { type: 'string', enum: ['info', 'warn', 'err', 'ok', 'debug'], description: 'Optional exact log level.' } }, []],
  ['create_launch_link', 'Create a reproducible starting point for a task, experiment or demo as a launch URL. Reproduces boot configuration and an optional startup script for the current or specified profile. Does not open, publish or execute it. Does not preserve modified files, processes or terminal state.', true, { profileId: str('Optional profile ID from kandelo_list_profiles; defaults to current computer.', 128), startupScript: str('Optional script executed when someone opens the generated link.', 2097152) }, []],
] as const;

export class ToolError extends Error {
  constructor(public code: string, message: string, public details?: Record<string, unknown>) { super(message); }
}
export function validate(value: unknown, schema: Schema, name = 'arguments'): void {
  if (schema.type === 'object') {
    if (!value || typeof value !== 'object' || Array.isArray(value)) throw new ToolError('INVALID_ARGUMENT', `${name} must be an object`);
    const record = value as Record<string, unknown>;
    for (const key of schema.required ?? []) if (!(key in record)) throw new ToolError('INVALID_ARGUMENT', `${name}.${key} is required`);
    for (const [key, item] of Object.entries(record)) {
      const child = schema.properties?.[key] ?? (typeof schema.additionalProperties === 'object' ? schema.additionalProperties : undefined);
      if (!child) throw new ToolError('INVALID_ARGUMENT', `Unknown argument ${name}.${key}`);
      validate(item, child, `${name}.${key}`);
    }
  } else if (schema.type === 'integer') {
    if (!Number.isSafeInteger(value) || (value as number) < (schema.minimum ?? 0) || (value as number) > (schema.maximum ?? Number.MAX_SAFE_INTEGER)) throw new ToolError('INVALID_ARGUMENT', `${name} is outside its integer range`);
  } else if (typeof value !== schema.type || (typeof value === 'string' && ((schema.maxLength !== undefined && value.length > schema.maxLength) || (schema.enum && !schema.enum.includes(value))))) {
    throw new ToolError('INVALID_ARGUMENT', `${name} has an invalid value`);
  }
}
export function guestPath(value: string): string {
  if (!value.startsWith('/') || /[\x00-\x1f\\]/.test(value) || value.split('/').some(p => p === '.' || p === '..')) throw new ToolError('INVALID_ARGUMENT', 'Expected an absolute guest path without dot segments or control characters');
  return value;
}
