script_path = "packages/registry/spidermonkey/build-spidermonkey.sh"
repo_url    = "https://github.com/brandonpayton/wasm-posix-kernel.git"
commit      = "d50f54f16bf242c0897e48b71bb519b386407fa8"
revision    = 9

[binary]
index_url = "https://github.com/brandonpayton/wasm-posix-kernel/releases/download/binaries-abi-v{abi}/index.toml"
