/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
/* /dev/kandelo/bluetooth: a Web Bluetooth device brokered to one guest. */
/* Source of truth: crates/shared/src/lib.rs, module `bluetooth`. */
#ifndef KANDELO_BLUETOOTH_H
#define KANDELO_BLUETOOTH_H

#include <stddef.h>
#include <stdint.h>

#define KANDELO_BLUETOOTH_DEVICE_PATH "/dev/kandelo/bluetooth"
#define KANDELO_BLUETOOTH_RECORD_VERSION (1)
#define KANDELO_BLUETOOTH_KIND_REQUEST (1)
#define KANDELO_BLUETOOTH_KIND_RESPONSE (2)
#define KANDELO_BLUETOOTH_KIND_NOTIFY (3)
#define KANDELO_BLUETOOTH_KIND_STATUS (4)
#define KANDELO_BLUETOOTH_MAX_PAYLOAD_BYTES (4096)
#define KANDELO_BLUETOOTH_MAX_QUEUED_RECORDS (64)
#define KANDELO_BLUETOOTH_MAX_PENDING_REQUESTS (16)
#define KANDELO_BLUETOOTH_RECORD_HEADER_SIZE (16)

/* One record in either direction: this header, then `len` bytes */
/* of UTF-8 text. All fields are little-endian. The guest writes */
/* KIND_REQUEST records (seq = its request id, never 0) and reads */
/* KIND_RESPONSE (same seq), KIND_NOTIFY and KIND_STATUS records. */
struct kandelo_bluetooth_record {
	uint32_t version;
	uint32_t kind;
	uint32_t seq;
	uint32_t len;
};

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(struct kandelo_bluetooth_record) == 16, "record ABI size");
_Static_assert(offsetof(struct kandelo_bluetooth_record, len) == 12, "record.len ABI offset");
#endif

#endif /* KANDELO_BLUETOOTH_H */
