/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
/* /dev/kandelo/clipboard: host clipboard text for a guest agent. */
/* Source of truth: crates/shared/src/lib.rs, module `clipboard`. */
#ifndef KANDELO_CLIPBOARD_H
#define KANDELO_CLIPBOARD_H

#include <stddef.h>
#include <stdint.h>

#define KANDELO_CLIPBOARD_DEVICE_PATH "/dev/kandelo/clipboard"
#define KANDELO_CLIPBOARD_RECORD_VERSION (1)
#define KANDELO_CLIPBOARD_KIND_OFFER_TEXT (1)
#define KANDELO_CLIPBOARD_MAX_TEXT_BYTES (1048576)
#define KANDELO_CLIPBOARD_RECORD_HEADER_SIZE (16)
#define KANDELO_CLIPBOARD_ACK_SIZE (8)
#define KANDELO_CLIPBOARD_ACK_PENDING (1)
#define KANDELO_CLIPBOARD_ACK_SUPERSEDED (-125)
#define KANDELO_CLIPBOARD_ACK_NO_AGENT (-6)
#define KANDELO_CLIPBOARD_ACK_UNKNOWN_SEQ (-2)

/* One record as read from the device: this header, then `len` */
/* bytes of UTF-8 text. All fields are little-endian. */
struct kandelo_clipboard_record {
	uint32_t version;
	uint32_t kind;
	uint32_t seq;
	uint32_t len;
};

/* Written back after an offer: status 0 once the selection is */
/* installed, else a negative errno. */
struct kandelo_clipboard_ack {
	uint32_t seq;
	int32_t status;
};

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(struct kandelo_clipboard_record) == 16, "record ABI size");
_Static_assert(offsetof(struct kandelo_clipboard_record, len) == 12, "record.len ABI offset");
_Static_assert(sizeof(struct kandelo_clipboard_ack) == 8, "ack ABI size");
_Static_assert(offsetof(struct kandelo_clipboard_ack, status) == 4, "ack.status ABI offset");
#endif

#endif /* KANDELO_CLIPBOARD_H */
