script_path = "packages/registry/libinput-lite/build-libinput-lite.sh"
repo_url    = "https://github.com/Automattic/kandelo.git"
commit      = "d1b1156e8d166d1fd596806d4ecd000b15241cac"
revision    = 1

[binary]
index_url = "https://github.com/Automattic/kandelo/releases/download/binaries-abi-v{abi}/index.toml"
