/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
/* Regenerated by scripts/check-abi-version.sh; drift is a CI failure. */
#ifndef KANDELO_PLATFORM_LIMITS_H
#define KANDELO_PLATFORM_LIMITS_H

#define KANDELO_POSIX_ARG_MAX_BYTES 4194304u
#define KANDELO_POSIX_PATH_MAX_BYTES 4096u
#define KANDELO_POSIX_IOV_MAX 1024u
#define KANDELO_PROCESS_METADATA_ENTRY_MAX_BYTES 65536u
#define KANDELO_MAX_REPORTABLE_TRANSFER_BYTES 2147483647u

#endif /* KANDELO_PLATFORM_LIMITS_H */
