/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
/* Regenerated by scripts/check-abi-version.sh; drift is a CI failure. */
#ifndef KANDELO_THREAD_SYSCALLS_H
#define KANDELO_THREAD_SYSCALLS_H

#define KANDELO_SYS_THREAD_CANCEL 415u

#endif /* KANDELO_THREAD_SYSCALLS_H */
