/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
/* Regenerated by scripts/check-abi-version.sh; drift is a CI failure. */
/*
* Guest self-marshalling descriptor table (Phase 2 opaque transport).
*
* Projects `wasm_posix_shared::host_abi::SYSCALL_ARG_DESCRIPTORS` plus
* the nested iovec/msghdr syscalls into a compact runtime table the
* musl glue encoder (`__marshal_channel_record`) consumes to build an
* opaque `channel_record` at DATA_OFFSET. Additive: not on the live
* syscall path yet, and does NOT participate in the ABI snapshot.
*/
#ifndef KANDELO_SYSCALL_MARSHAL_H
#define KANDELO_SYSCALL_MARSHAL_H

#include <stdint.h>

/* Record wire layout, sourced from wasm_posix_shared::channel_record
* and ::channel so the encoder never hardcodes offsets. */
#define KANDELO_RECORD_MAGIC 0x3152434Bu
#define KANDELO_RECORD_ABI 1u
#define KANDELO_RECORD_HEADER_BYTES 64u
#define KANDELO_RECORD_SPAN_DESCRIPTOR_BYTES 12u
#define KANDELO_RECORD_MAX_SPANS 8u
#define KANDELO_RECORD_MAX_IOVEC 1024u
#define KANDELO_RECORD_INLINE_BUDGET 65480u
/* RecordHeader field byte offsets. */
#define KANDELO_RECORD_H_MAGIC 0u
#define KANDELO_RECORD_H_RECORD_ABI 4u
#define KANDELO_RECORD_H_SYSCALL 6u
#define KANDELO_RECORD_H_SPAN_COUNT 8u
#define KANDELO_RECORD_H_FLAGS 10u
#define KANDELO_RECORD_H_SCALARS 16u
/* SpanDescriptor field byte offsets. */
#define KANDELO_RECORD_D_KIND 0u
#define KANDELO_RECORD_D_ARG_INDEX 1u
#define KANDELO_RECORD_D_OFFSET 4u
#define KANDELO_RECORD_D_LEN 8u
/* Nested iovec-array region field offsets. */
#define KANDELO_RECORD_IOVEC_COUNT_OFFSET 0u
#define KANDELO_RECORD_IOVEC_ENTRIES_OFFSET 4u
#define KANDELO_RECORD_IOVEC_ENTRY_BYTES 8u
/* Nested msghdr region field offsets (fixed prefix). */
#define KANDELO_RECORD_MSGHDR_NAME_OFF_OFFSET 0u
#define KANDELO_RECORD_MSGHDR_NAME_LEN_OFFSET 4u
#define KANDELO_RECORD_MSGHDR_IOVEC_BLOCK_OFFSET 8u

/* Flat-span record kinds (mirror channel_record::SPAN_KIND_*). */
#define KANDELO_MARSHAL_SPAN_IN_PTR 1u
#define KANDELO_MARSHAL_SPAN_OUT_PTR 2u
#define KANDELO_MARSHAL_SPAN_IN_OUT_PTR 3u
#define KANDELO_MARSHAL_SPAN_PATH_STR 4u
#define KANDELO_MARSHAL_SPAN_IOVEC_ARRAY 5u
#define KANDELO_MARSHAL_SPAN_MSGHDR 6u

/* Size rules (mirror host_abi::SyscallArgSize variant order). */
#define KANDELO_MARSHAL_SIZE_CSTRING 0u
#define KANDELO_MARSHAL_SIZE_ARG 1u
#define KANDELO_MARSHAL_SIZE_DEREF 2u
#define KANDELO_MARSHAL_SIZE_FIXED 3u
#define KANDELO_MARSHAL_SIZE_LAYOUT 4u

/* Whole-syscall nested marshalling shapes. */
#define KANDELO_MARSHAL_NESTED_NONE 0u
#define KANDELO_MARSHAL_NESTED_IOVEC 1u
#define KANDELO_MARSHAL_NESTED_MSGHDR 2u

/* One pointer argument to marshal.
*   arg_index : which of the six syscall words holds the pointer.
*   span_kind : KANDELO_MARSHAL_SPAN_* emitted for this arg.
*   size_kind : KANDELO_MARSHAL_SIZE_* selecting how `len` is computed.
*   nullable  : 1 => a null pointer omits the span entirely.
*   a,b,c     : size-rule operands, by size_kind:
*     CSTRING -> a = max_bytes (scan ceiling incl. NUL)
*     ARG     -> a = length arg index, b = multiplier, c = add
*     DEREF   -> a = arg index holding a u32* length
*     FIXED   -> a = byte length
*     LAYOUT  -> a = wasm32 size, b = wasm64 size
*   For a nested syscall the single entry carries, for IOVEC,
*   a = the iovcnt arg index; MSGHDR uses arg_index only.
*/
struct kandelo_marshal_arg {
    uint8_t arg_index;
    uint8_t span_kind;
    uint8_t size_kind;
    uint8_t nullable;
    uint32_t a;
    uint32_t b;
    uint32_t c;
};

struct kandelo_marshal_syscall {
    uint32_t syscall_number;
    uint8_t nested; /* KANDELO_MARSHAL_NESTED_* */
    uint8_t arg_count;
    const struct kandelo_marshal_arg *args;
};

static const struct kandelo_marshal_arg kandelo_marshal_args_1[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_3[] = {
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_4[] = {
    { 1u, 1u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_6[] = {
    { 1u, 2u, 3u, 0u, 112u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_9[] = {
    { 0u, 2u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_11[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 1u, 2u, 3u, 0u, 112u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_12[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 1u, 2u, 3u, 0u, 112u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_13[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_14[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_15[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_16[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_17[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_18[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_19[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_20[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_21[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_22[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_23[] = {
    { 0u, 2u, 1u, 0u, 1u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_24[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_25[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_26[] = {
    { 1u, 2u, 3u, 0u, 16u, 0u, 0u },
    { 2u, 2u, 1u, 0u, 3u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_36[] = {
    { 1u, 1u, 3u, 1u, 16u, 0u, 0u },
    { 2u, 2u, 3u, 1u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_37[] = {
    { 1u, 1u, 3u, 1u, 8u, 0u, 0u },
    { 2u, 2u, 3u, 1u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_40[] = {
    { 1u, 2u, 3u, 0u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_41[] = {
    { 0u, 1u, 3u, 0u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_43[] = {
    { 0u, 4u, 0u, 0u, 65537u, 0u, 0u },
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_44[] = {
    { 0u, 4u, 0u, 0u, 65537u, 0u, 0u },
    { 1u, 4u, 0u, 0u, 65537u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_45[] = {
    { 0u, 4u, 0u, 0u, 65537u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_51[] = {
    { 1u, 1u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_53[] = {
    { 1u, 2u, 2u, 1u, 2u, 0u, 0u },
    { 2u, 3u, 3u, 1u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_54[] = {
    { 1u, 1u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_55[] = {
    { 1u, 1u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_56[] = {
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_58[] = {
    { 3u, 2u, 2u, 0u, 4u, 0u, 0u },
    { 4u, 3u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_59[] = {
    { 3u, 1u, 1u, 0u, 4u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_60[] = {
    { 0u, 3u, 1u, 0u, 1u, 8u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_61[] = {
    { 3u, 2u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_62[] = {
    { 1u, 1u, 1u, 0u, 2u, 1u, 0u },
    { 4u, 1u, 1u, 0u, 5u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_63[] = {
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
    { 4u, 2u, 2u, 1u, 5u, 0u, 0u },
    { 5u, 3u, 3u, 1u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_64[] = {
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_65[] = {
    { 1u, 1u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_69[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_70[] = {
    { 1u, 2u, 3u, 0u, 60u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_71[] = {
    { 2u, 1u, 3u, 0u, 60u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_75[] = {
    { 0u, 2u, 3u, 0u, 390u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_78[] = {
    { 0u, 2u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_81[] = {
    { 1u, 5u, 0u, 0u, 2u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_82[] = {
    { 1u, 5u, 0u, 0u, 2u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_83[] = {
    { 1u, 2u, 3u, 0u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_84[] = {
    { 1u, 1u, 3u, 0u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_85[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_93[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 2u, 2u, 3u, 0u, 112u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_94[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_95[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_96[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 3u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_97[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_98[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_99[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_100[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 3u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_101[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 2u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_102[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 2u, 2u, 1u, 0u, 3u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_108[] = {
    { 1u, 2u, 3u, 0u, 144u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_109[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_110[] = {
    { 0u, 1u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_112[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 2u, 2u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_113[] = {
    { 2u, 2u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_114[] = {
    { 1u, 2u, 2u, 0u, 2u, 0u, 0u },
    { 2u, 3u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_115[] = {
    { 1u, 2u, 2u, 0u, 2u, 0u, 0u },
    { 2u, 3u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_119[] = {
    { 3u, 2u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_120[] = {
    { 0u, 2u, 1u, 0u, 1u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_122[] = {
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_123[] = {
    { 1u, 2u, 3u, 1u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_124[] = {
    { 2u, 1u, 3u, 0u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_125[] = {
    { 1u, 4u, 0u, 1u, 4096u, 0u, 0u },
    { 2u, 1u, 3u, 1u, 32u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_129[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 2u, 2u, 4u, 0u, 88u, 120u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_130[] = {
    { 2u, 2u, 4u, 0u, 88u, 120u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_132[] = {
    { 0u, 2u, 3u, 0u, 4u, 0u, 0u },
    { 1u, 2u, 3u, 0u, 4u, 0u, 0u },
    { 2u, 2u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_134[] = {
    { 0u, 2u, 3u, 0u, 4u, 0u, 0u },
    { 1u, 2u, 3u, 0u, 4u, 0u, 0u },
    { 2u, 2u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_135[] = {
    { 1u, 2u, 1u, 0u, 0u, 4u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_136[] = {
    { 1u, 1u, 1u, 0u, 0u, 4u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_137[] = {
    { 1u, 6u, 0u, 0u, 0u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_138[] = {
    { 1u, 6u, 0u, 0u, 0u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_139[] = {
    { 1u, 2u, 3u, 1u, 4u, 0u, 0u },
    { 3u, 2u, 3u, 1u, 144u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_140[] = {
    { 0u, 4u, 0u, 0u, 256u, 0u, 0u },
    { 1u, 2u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_205[] = {
    { 2u, 1u, 4u, 0u, 128u, 128u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_206[] = {
    { 0u, 2u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_207[] = {
    { 0u, 1u, 3u, 0u, 8u, 0u, 0u },
    { 1u, 2u, 4u, 1u, 128u, 128u, 0u },
    { 2u, 1u, 3u, 1u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_209[] = {
    { 0u, 1u, 4u, 1u, 12u, 24u, 0u },
    { 1u, 2u, 4u, 1u, 12u, 24u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_211[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_224[] = {
    { 1u, 2u, 4u, 0u, 16u, 32u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_225[] = {
    { 1u, 1u, 4u, 0u, 16u, 32u, 0u },
    { 2u, 2u, 4u, 1u, 16u, 32u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_230[] = {
    { 1u, 2u, 3u, 0u, 48u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_231[] = {
    { 1u, 1u, 3u, 0u, 48u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_233[] = {
    { 2u, 1u, 3u, 0u, 48u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_236[] = {
    { 1u, 2u, 3u, 0u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_238[] = {
    { 2u, 2u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_244[] = {
    { 2u, 1u, 3u, 0u, 32u, 0u, 0u },
    { 3u, 2u, 3u, 1u, 32u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_245[] = {
    { 1u, 2u, 3u, 0u, 32u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_246[] = {
    { 1u, 1u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_250[] = {
    { 2u, 1u, 3u, 1u, 16u, 0u, 0u },
    { 3u, 2u, 3u, 1u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_251[] = {
    { 0u, 3u, 1u, 0u, 1u, 8u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_256[] = {
    { 0u, 4u, 0u, 0u, 250u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_260[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 4u, 2u, 3u, 0u, 256u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_269[] = {
    { 0u, 2u, 4u, 0u, 312u, 368u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_271[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_272[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_288[] = {
    { 2u, 2u, 4u, 0u, 128u, 128u, 0u },
    { 4u, 2u, 3u, 1u, 144u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_290[] = {
    { 1u, 3u, 3u, 1u, 8u, 0u, 0u },
    { 3u, 3u, 3u, 1u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_291[] = {
    { 1u, 3u, 3u, 1u, 8u, 0u, 0u },
    { 3u, 3u, 3u, 1u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_294[] = {
    { 2u, 3u, 3u, 1u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_295[] = {
    { 1u, 5u, 0u, 0u, 2u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_296[] = {
    { 1u, 5u, 0u, 0u, 2u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_297[] = {
    { 1u, 5u, 0u, 0u, 2u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_298[] = {
    { 1u, 5u, 0u, 0u, 2u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_299[] = {
    { 0u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_306[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
    { 3u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_325[] = {
    { 0u, 2u, 3u, 1u, 4u, 0u, 0u },
    { 1u, 2u, 3u, 1u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_326[] = {
    { 1u, 1u, 4u, 1u, 64u, 64u, 0u },
    { 2u, 2u, 3u, 0u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_327[] = {
    { 2u, 1u, 3u, 0u, 32u, 0u, 0u },
    { 3u, 2u, 3u, 1u, 32u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_328[] = {
    { 1u, 2u, 3u, 0u, 32u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_331[] = {
    { 0u, 4u, 0u, 0u, 256u, 0u, 0u },
    { 3u, 1u, 4u, 1u, 32u, 64u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_332[] = {
    { 0u, 4u, 0u, 0u, 256u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_333[] = {
    { 1u, 1u, 1u, 0u, 2u, 1u, 0u },
    { 4u, 1u, 3u, 1u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_334[] = {
    { 1u, 2u, 1u, 0u, 2u, 1u, 0u },
    { 3u, 2u, 3u, 1u, 4u, 0u, 0u },
    { 4u, 1u, 3u, 1u, 16u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_335[] = {
    { 1u, 1u, 4u, 1u, 64u, 64u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_336[] = {
    { 1u, 1u, 4u, 1u, 32u, 64u, 0u },
    { 2u, 2u, 4u, 1u, 32u, 64u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_342[] = {
    { 1u, 1u, 1u, 0u, 2u, 6u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_377[] = {
    { 1u, 1u, 3u, 0u, 8u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_382[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_383[] = {
    { 1u, 4u, 0u, 0u, 4096u, 0u, 0u },
};

static const struct kandelo_marshal_arg kandelo_marshal_args_384[] = {
    { 1u, 2u, 2u, 1u, 2u, 0u, 0u },
    { 2u, 3u, 3u, 1u, 4u, 0u, 0u },
};

static const struct kandelo_marshal_syscall kandelo_marshal_table[] = {
    { 1u, 0u, 1u, kandelo_marshal_args_1 },
    { 3u, 0u, 1u, kandelo_marshal_args_3 },
    { 4u, 0u, 1u, kandelo_marshal_args_4 },
    { 6u, 0u, 1u, kandelo_marshal_args_6 },
    { 9u, 0u, 1u, kandelo_marshal_args_9 },
    { 11u, 0u, 2u, kandelo_marshal_args_11 },
    { 12u, 0u, 2u, kandelo_marshal_args_12 },
    { 13u, 0u, 1u, kandelo_marshal_args_13 },
    { 14u, 0u, 1u, kandelo_marshal_args_14 },
    { 15u, 0u, 1u, kandelo_marshal_args_15 },
    { 16u, 0u, 2u, kandelo_marshal_args_16 },
    { 17u, 0u, 2u, kandelo_marshal_args_17 },
    { 18u, 0u, 2u, kandelo_marshal_args_18 },
    { 19u, 0u, 2u, kandelo_marshal_args_19 },
    { 20u, 0u, 1u, kandelo_marshal_args_20 },
    { 21u, 0u, 1u, kandelo_marshal_args_21 },
    { 22u, 0u, 1u, kandelo_marshal_args_22 },
    { 23u, 0u, 1u, kandelo_marshal_args_23 },
    { 24u, 0u, 1u, kandelo_marshal_args_24 },
    { 25u, 0u, 1u, kandelo_marshal_args_25 },
    { 26u, 0u, 2u, kandelo_marshal_args_26 },
    { 36u, 0u, 2u, kandelo_marshal_args_36 },
    { 37u, 0u, 2u, kandelo_marshal_args_37 },
    { 40u, 0u, 1u, kandelo_marshal_args_40 },
    { 41u, 0u, 1u, kandelo_marshal_args_41 },
    { 43u, 0u, 2u, kandelo_marshal_args_43 },
    { 44u, 0u, 2u, kandelo_marshal_args_44 },
    { 45u, 0u, 1u, kandelo_marshal_args_45 },
    { 51u, 0u, 1u, kandelo_marshal_args_51 },
    { 53u, 0u, 2u, kandelo_marshal_args_53 },
    { 54u, 0u, 1u, kandelo_marshal_args_54 },
    { 55u, 0u, 1u, kandelo_marshal_args_55 },
    { 56u, 0u, 1u, kandelo_marshal_args_56 },
    { 58u, 0u, 2u, kandelo_marshal_args_58 },
    { 59u, 0u, 1u, kandelo_marshal_args_59 },
    { 60u, 0u, 1u, kandelo_marshal_args_60 },
    { 61u, 0u, 1u, kandelo_marshal_args_61 },
    { 62u, 0u, 2u, kandelo_marshal_args_62 },
    { 63u, 0u, 3u, kandelo_marshal_args_63 },
    { 64u, 0u, 1u, kandelo_marshal_args_64 },
    { 65u, 0u, 1u, kandelo_marshal_args_65 },
    { 69u, 0u, 1u, kandelo_marshal_args_69 },
    { 70u, 0u, 1u, kandelo_marshal_args_70 },
    { 71u, 0u, 1u, kandelo_marshal_args_71 },
    { 75u, 0u, 1u, kandelo_marshal_args_75 },
    { 78u, 0u, 1u, kandelo_marshal_args_78 },
    { 81u, 1u, 1u, kandelo_marshal_args_81 },
    { 82u, 1u, 1u, kandelo_marshal_args_82 },
    { 83u, 0u, 1u, kandelo_marshal_args_83 },
    { 84u, 0u, 1u, kandelo_marshal_args_84 },
    { 85u, 0u, 1u, kandelo_marshal_args_85 },
    { 93u, 0u, 2u, kandelo_marshal_args_93 },
    { 94u, 0u, 1u, kandelo_marshal_args_94 },
    { 95u, 0u, 1u, kandelo_marshal_args_95 },
    { 96u, 0u, 2u, kandelo_marshal_args_96 },
    { 97u, 0u, 1u, kandelo_marshal_args_97 },
    { 98u, 0u, 1u, kandelo_marshal_args_98 },
    { 99u, 0u, 1u, kandelo_marshal_args_99 },
    { 100u, 0u, 2u, kandelo_marshal_args_100 },
    { 101u, 0u, 2u, kandelo_marshal_args_101 },
    { 102u, 0u, 2u, kandelo_marshal_args_102 },
    { 108u, 0u, 1u, kandelo_marshal_args_108 },
    { 109u, 0u, 2u, kandelo_marshal_args_109 },
    { 110u, 0u, 1u, kandelo_marshal_args_110 },
    { 112u, 0u, 2u, kandelo_marshal_args_112 },
    { 113u, 0u, 1u, kandelo_marshal_args_113 },
    { 114u, 0u, 2u, kandelo_marshal_args_114 },
    { 115u, 0u, 2u, kandelo_marshal_args_115 },
    { 119u, 0u, 1u, kandelo_marshal_args_119 },
    { 120u, 0u, 1u, kandelo_marshal_args_120 },
    { 122u, 0u, 1u, kandelo_marshal_args_122 },
    { 123u, 0u, 1u, kandelo_marshal_args_123 },
    { 124u, 0u, 1u, kandelo_marshal_args_124 },
    { 125u, 0u, 2u, kandelo_marshal_args_125 },
    { 129u, 0u, 2u, kandelo_marshal_args_129 },
    { 130u, 0u, 1u, kandelo_marshal_args_130 },
    { 132u, 0u, 3u, kandelo_marshal_args_132 },
    { 134u, 0u, 3u, kandelo_marshal_args_134 },
    { 135u, 0u, 1u, kandelo_marshal_args_135 },
    { 136u, 0u, 1u, kandelo_marshal_args_136 },
    { 137u, 2u, 1u, kandelo_marshal_args_137 },
    { 138u, 2u, 1u, kandelo_marshal_args_138 },
    { 139u, 0u, 2u, kandelo_marshal_args_139 },
    { 140u, 0u, 2u, kandelo_marshal_args_140 },
    { 205u, 0u, 1u, kandelo_marshal_args_205 },
    { 206u, 0u, 1u, kandelo_marshal_args_206 },
    { 207u, 0u, 3u, kandelo_marshal_args_207 },
    { 209u, 0u, 2u, kandelo_marshal_args_209 },
    { 211u, 0u, 1u, kandelo_marshal_args_211 },
    { 224u, 0u, 1u, kandelo_marshal_args_224 },
    { 225u, 0u, 2u, kandelo_marshal_args_225 },
    { 230u, 0u, 1u, kandelo_marshal_args_230 },
    { 231u, 0u, 1u, kandelo_marshal_args_231 },
    { 233u, 0u, 1u, kandelo_marshal_args_233 },
    { 236u, 0u, 1u, kandelo_marshal_args_236 },
    { 238u, 0u, 1u, kandelo_marshal_args_238 },
    { 244u, 0u, 2u, kandelo_marshal_args_244 },
    { 245u, 0u, 1u, kandelo_marshal_args_245 },
    { 246u, 0u, 1u, kandelo_marshal_args_246 },
    { 250u, 0u, 2u, kandelo_marshal_args_250 },
    { 251u, 0u, 1u, kandelo_marshal_args_251 },
    { 256u, 0u, 1u, kandelo_marshal_args_256 },
    { 260u, 0u, 2u, kandelo_marshal_args_260 },
    { 269u, 0u, 1u, kandelo_marshal_args_269 },
    { 271u, 0u, 1u, kandelo_marshal_args_271 },
    { 272u, 0u, 1u, kandelo_marshal_args_272 },
    { 288u, 0u, 2u, kandelo_marshal_args_288 },
    { 290u, 0u, 2u, kandelo_marshal_args_290 },
    { 291u, 0u, 2u, kandelo_marshal_args_291 },
    { 294u, 0u, 1u, kandelo_marshal_args_294 },
    { 295u, 1u, 1u, kandelo_marshal_args_295 },
    { 296u, 1u, 1u, kandelo_marshal_args_296 },
    { 297u, 1u, 1u, kandelo_marshal_args_297 },
    { 298u, 1u, 1u, kandelo_marshal_args_298 },
    { 299u, 0u, 1u, kandelo_marshal_args_299 },
    { 306u, 0u, 2u, kandelo_marshal_args_306 },
    { 325u, 0u, 2u, kandelo_marshal_args_325 },
    { 326u, 0u, 2u, kandelo_marshal_args_326 },
    { 327u, 0u, 2u, kandelo_marshal_args_327 },
    { 328u, 0u, 1u, kandelo_marshal_args_328 },
    { 331u, 0u, 2u, kandelo_marshal_args_331 },
    { 332u, 0u, 1u, kandelo_marshal_args_332 },
    { 333u, 0u, 2u, kandelo_marshal_args_333 },
    { 334u, 0u, 3u, kandelo_marshal_args_334 },
    { 335u, 0u, 1u, kandelo_marshal_args_335 },
    { 336u, 0u, 2u, kandelo_marshal_args_336 },
    { 342u, 0u, 1u, kandelo_marshal_args_342 },
    { 377u, 0u, 1u, kandelo_marshal_args_377 },
    { 382u, 0u, 1u, kandelo_marshal_args_382 },
    { 383u, 0u, 1u, kandelo_marshal_args_383 },
    { 384u, 0u, 2u, kandelo_marshal_args_384 },
};

#define KANDELO_MARSHAL_SYSCALL_COUNT 131u

#endif /* KANDELO_SYSCALL_MARSHAL_H */
