/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
#ifndef KANDELO_CHANNEL_SCALARS_H
#define KANDELO_CHANNEL_SCALARS_H

#include <bits/syscall.h>

/* WHY: the shared scalar table is authoritative, but musl still owns
* the public target syscall-number headers. Compile both together so
* a renumbering cannot silently reinterpret an i64 channel slot. */
#ifndef __NR_read
#error "musl is missing __NR_read required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_read == 3u,
"musl __NR_read drifted from the Kandelo channel scalar contract");
#ifndef __NR_write
#error "musl is missing __NR_write required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_write == 4u,
"musl __NR_write drifted from the Kandelo channel scalar contract");
#ifndef __NR_lseek
#error "musl is missing __NR_lseek required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_lseek == 5u,
"musl __NR_lseek drifted from the Kandelo channel scalar contract");
#ifndef __NR_readlink
#error "musl is missing __NR_readlink required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_readlink == 19u,
"musl __NR_readlink drifted from the Kandelo channel scalar contract");
#ifndef __NR_getcwd
#error "musl is missing __NR_getcwd required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_getcwd == 23u,
"musl __NR_getcwd drifted from the Kandelo channel scalar contract");
#ifndef __NR_readdir
#error "musl is missing __NR_readdir required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_readdir == 26u,
"musl __NR_readdir drifted from the Kandelo channel scalar contract");
#ifndef __NR_getenv
#error "musl is missing __NR_getenv required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_getenv == 43u,
"musl __NR_getenv drifted from the Kandelo channel scalar contract");
#ifndef __NR_mmap
#error "musl is missing __NR_mmap required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_mmap == 46u,
"musl __NR_mmap drifted from the Kandelo channel scalar contract");
#ifndef __NR_munmap
#error "musl is missing __NR_munmap required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_munmap == 47u,
"musl __NR_munmap drifted from the Kandelo channel scalar contract");
#ifndef __NR_brk
#error "musl is missing __NR_brk required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_brk == 48u,
"musl __NR_brk drifted from the Kandelo channel scalar contract");
#ifndef __NR_mprotect
#error "musl is missing __NR_mprotect required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_mprotect == 49u,
"musl __NR_mprotect drifted from the Kandelo channel scalar contract");
#ifndef __NR_bind
#error "musl is missing __NR_bind required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_bind == 51u,
"musl __NR_bind drifted from the Kandelo channel scalar contract");
#ifndef __NR_connect
#error "musl is missing __NR_connect required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_connect == 54u,
"musl __NR_connect drifted from the Kandelo channel scalar contract");
#ifndef __NR_send
#error "musl is missing __NR_send required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_send == 55u,
"musl __NR_send drifted from the Kandelo channel scalar contract");
#ifndef __NR_recv
#error "musl is missing __NR_recv required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_recv == 56u,
"musl __NR_recv drifted from the Kandelo channel scalar contract");
#ifndef __NR_setsockopt
#error "musl is missing __NR_setsockopt required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_setsockopt == 59u,
"musl __NR_setsockopt drifted from the Kandelo channel scalar contract");
#ifndef __NR_poll
#error "musl is missing __NR_poll required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_poll == 60u,
"musl __NR_poll drifted from the Kandelo channel scalar contract");
#ifndef __NR_sendto
#error "musl is missing __NR_sendto required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_sendto == 62u,
"musl __NR_sendto drifted from the Kandelo channel scalar contract");
#ifndef __NR_recvfrom
#error "musl is missing __NR_recvfrom required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_recvfrom == 63u,
"musl __NR_recvfrom drifted from the Kandelo channel scalar contract");
#ifndef __NR_pread
#error "musl is missing __NR_pread required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_pread == 64u,
"musl __NR_pread drifted from the Kandelo channel scalar contract");
#ifndef __NR_pwrite
#error "musl is missing __NR_pwrite required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_pwrite == 65u,
"musl __NR_pwrite drifted from the Kandelo channel scalar contract");
#ifndef __NR_time
#error "musl is missing __NR_time required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_time == 66u,
"musl __NR_time drifted from the Kandelo channel scalar contract");
#ifndef __NR_signal
#error "musl is missing __NR_signal required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_signal == 73u,
"musl __NR_signal drifted from the Kandelo channel scalar contract");
#ifndef __NR_ftruncate
#error "musl is missing __NR_ftruncate required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_ftruncate == 79u,
"musl __NR_ftruncate drifted from the Kandelo channel scalar contract");
#ifndef __NR_truncate
#error "musl is missing __NR_truncate required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_truncate == 85u,
"musl __NR_truncate drifted from the Kandelo channel scalar contract");
#ifndef __NR_readlinkat
#error "musl is missing __NR_readlinkat required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_readlinkat == 102u,
"musl __NR_readlinkat drifted from the Kandelo channel scalar contract");
#ifndef __NR_realpath
#error "musl is missing __NR_realpath required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_realpath == 109u,
"musl __NR_realpath drifted from the Kandelo channel scalar contract");
#ifndef __NR__llseek
#error "musl is missing __NR__llseek required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR__llseek == 119u,
"musl __NR__llseek drifted from the Kandelo channel scalar contract");
#ifndef __NR_getrandom
#error "musl is missing __NR_getrandom required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_getrandom == 120u,
"musl __NR_getrandom drifted from the Kandelo channel scalar contract");
#ifndef __NR_getdents64
#error "musl is missing __NR_getdents64 required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_getdents64 == 122u,
"musl __NR_getdents64 drifted from the Kandelo channel scalar contract");
#ifndef __NR_mremap
#error "musl is missing __NR_mremap required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_mremap == 126u,
"musl __NR_mremap drifted from the Kandelo channel scalar contract");
#ifndef __NR_madvise
#error "musl is missing __NR_madvise required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_madvise == 128u,
"musl __NR_madvise drifted from the Kandelo channel scalar contract");
#ifndef __NR_getgroups
#error "musl is missing __NR_getgroups required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_getgroups == 135u,
"musl __NR_getgroups drifted from the Kandelo channel scalar contract");
#ifndef __NR_setgroups
#error "musl is missing __NR_setgroups required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_setgroups == 136u,
"musl __NR_setgroups drifted from the Kandelo channel scalar contract");
#ifndef __NR_futex
#error "musl is missing __NR_futex required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_futex == 200u,
"musl __NR_futex drifted from the Kandelo channel scalar contract");
#ifndef __NR_set_tid_address
#error "musl is missing __NR_set_tid_address required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_set_tid_address == 203u,
"musl __NR_set_tid_address drifted from the Kandelo channel scalar contract");
#ifndef __NR_sched_setaffinity
#error "musl is missing __NR_sched_setaffinity required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_sched_setaffinity == 237u,
"musl __NR_sched_setaffinity drifted from the Kandelo channel scalar contract");
#ifndef __NR_sched_getaffinity
#error "musl is missing __NR_sched_getaffinity required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_sched_getaffinity == 238u,
"musl __NR_sched_getaffinity drifted from the Kandelo channel scalar contract");
#ifndef __NR_epoll_pwait
#error "musl is missing __NR_epoll_pwait required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_epoll_pwait == 241u,
"musl __NR_epoll_pwait drifted from the Kandelo channel scalar contract");
#ifndef __NR_signalfd4
#error "musl is missing __NR_signalfd4 required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_signalfd4 == 246u,
"musl __NR_signalfd4 drifted from the Kandelo channel scalar contract");
#ifndef __NR_ppoll
#error "musl is missing __NR_ppoll required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_ppoll == 251u,
"musl __NR_ppoll drifted from the Kandelo channel scalar contract");
#ifndef __NR_set_robust_list
#error "musl is missing __NR_set_robust_list required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_set_robust_list == 261u,
"musl __NR_set_robust_list drifted from the Kandelo channel scalar contract");
#ifndef __NR_get_robust_list
#error "musl is missing __NR_get_robust_list required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_get_robust_list == 262u,
"musl __NR_get_robust_list drifted from the Kandelo channel scalar contract");
#ifndef __NR_msync
#error "musl is missing __NR_msync required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_msync == 278u,
"musl __NR_msync drifted from the Kandelo channel scalar contract");
#ifndef __NR_mlock
#error "musl is missing __NR_mlock required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_mlock == 279u,
"musl __NR_mlock drifted from the Kandelo channel scalar contract");
#ifndef __NR_mlock2
#error "musl is missing __NR_mlock2 required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_mlock2 == 280u,
"musl __NR_mlock2 drifted from the Kandelo channel scalar contract");
#ifndef __NR_munlock
#error "musl is missing __NR_munlock required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_munlock == 281u,
"musl __NR_munlock drifted from the Kandelo channel scalar contract");
#ifndef __NR_copy_file_range
#error "musl is missing __NR_copy_file_range required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_copy_file_range == 290u,
"musl __NR_copy_file_range drifted from the Kandelo channel scalar contract");
#ifndef __NR_splice
#error "musl is missing __NR_splice required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_splice == 291u,
"musl __NR_splice drifted from the Kandelo channel scalar contract");
#ifndef __NR_readahead
#error "musl is missing __NR_readahead required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_readahead == 293u,
"musl __NR_readahead drifted from the Kandelo channel scalar contract");
#ifndef __NR_sendfile
#error "musl is missing __NR_sendfile required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_sendfile == 294u,
"musl __NR_sendfile drifted from the Kandelo channel scalar contract");
#ifndef __NR_preadv
#error "musl is missing __NR_preadv required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_preadv == 295u,
"musl __NR_preadv drifted from the Kandelo channel scalar contract");
#ifndef __NR_pwritev
#error "musl is missing __NR_pwritev required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_pwritev == 296u,
"musl __NR_pwritev drifted from the Kandelo channel scalar contract");
#ifndef __NR_preadv2
#error "musl is missing __NR_preadv2 required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_preadv2 == 297u,
"musl __NR_preadv2 drifted from the Kandelo channel scalar contract");
#ifndef __NR_pwritev2
#error "musl is missing __NR_pwritev2 required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_pwritev2 == 298u,
"musl __NR_pwritev2 drifted from the Kandelo channel scalar contract");
#ifndef __NR_fallocate
#error "musl is missing __NR_fallocate required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_fallocate == 308u,
"musl __NR_fallocate drifted from the Kandelo channel scalar contract");
#ifndef __NR_mq_timedsend
#error "musl is missing __NR_mq_timedsend required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_mq_timedsend == 333u,
"musl __NR_mq_timedsend drifted from the Kandelo channel scalar contract");
#ifndef __NR_mq_timedreceive
#error "musl is missing __NR_mq_timedreceive required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_mq_timedreceive == 334u,
"musl __NR_mq_timedreceive drifted from the Kandelo channel scalar contract");
#ifndef __NR_msgrcv
#error "musl is missing __NR_msgrcv required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_msgrcv == 338u,
"musl __NR_msgrcv drifted from the Kandelo channel scalar contract");
#ifndef __NR_msgsnd
#error "musl is missing __NR_msgsnd required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_msgsnd == 339u,
"musl __NR_msgsnd drifted from the Kandelo channel scalar contract");
#ifndef __NR_semop
#error "musl is missing __NR_semop required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_semop == 342u,
"musl __NR_semop drifted from the Kandelo channel scalar contract");
#ifndef __NR_shmget
#error "musl is missing __NR_shmget required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_shmget == 344u,
"musl __NR_shmget drifted from the Kandelo channel scalar contract");
#ifndef __NR_signalfd
#error "musl is missing __NR_signalfd required by the Kandelo channel scalar contract"
#endif
_Static_assert(__NR_signalfd == 377u,
"musl __NR_signalfd drifted from the Kandelo channel scalar contract");

#endif
