[package]
name = "kandelo"
version.workspace = true
edition.workspace = true

[lib]
name = "kandelo_kernel"
crate-type = ["cdylib", "rlib"]

[dependencies]
runtime-core = { path = "../runtime-core" }
spin = { version = "=0.12.2", default-features = false, features = ["mutex", "spin_mutex"] }
wasm-posix-shared = { path = "../shared" }

[target.'cfg(any(target_arch = "wasm32", target_arch = "wasm64"))'.dependencies]
dlmalloc = { version = "0.2.14", default-features = false }
