// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/array-isarray.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"

namespace v8::internal {

// Builtin: ArrayIsArray
Address Builtin_ArrayIsArray(int args_length, Address* args_object,
                         Isolate* isolate) {
  DCHECK(isolate->context().is_null() || IsContext(isolate->context()));
  BuiltinArguments args(args_length, args_object);
  HandleScope scope(isolate);
  USE(isolate);
  Tagged<NativeContext> parameter0 = Cast<NativeContext>(isolate->context());
  USE(parameter0);
  Tagged<NativeContext> context = parameter0;
  USE(context);
  Tagged<JSAny> parameter1 = Cast<JSAny>(args[1]);
  USE(parameter1);
  Tagged<JSAny> arg = parameter1;
  USE(arg);
  Tagged<JSArray> tmp0{};  USE(tmp0);
  bool label1 = false;
  Tagged<JSProxy> tmp2{};  USE(tmp2);
  bool label3 = false;
  Tagged<True> tmp4{}; USE(tmp4);
  Tagged<False> tmp5{}; USE(tmp5);
  Tagged<JSAny> tmp6{};  USE(tmp6);
  goto block0;

  block0:
  tmp0 = TqRuntimeCast_JSArray_1(parameter0, parameter1, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  tmp2 = TqRuntimeCast_JSProxy_1(parameter0, static_cast<Tagged<JSAny>>(parameter1), &label3);
  if (label3) {
    goto block8;
  }
  goto block7;

  block3:
  tmp4 = True_0(isolate);
  return tmp4.ptr();

  block8:
  tmp5 = False_0(isolate);
  return tmp5.ptr();

  block7:
  tmp6 = Runtime::Call<Runtime::kArrayIsArray>(isolate, parameter0, parameter1);
  return tmp6.ptr();
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/array-flat.tq?l=65&c=13
inline Tagged<JSArray> TqRuntimeCast_JSArray_1(Tagged<Context> p_context, Tagged<Object> p_o, bool* label_CastError) {
  Tagged<HeapObject> tmp0{};  USE(tmp0);
  bool label1 = false;
  Tagged<JSArray> tmp2{};  USE(tmp2);
  bool label3 = false;
  goto block0;

  block0:
  tmp0 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedToHeapObject(p_o, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  goto block1;

  block3:
  tmp2 = TqRuntimeCast_JSArray_0(tmp0, &label3);
  if (label3) {
    goto block6;
  }
  goto block5;

  block6:
  goto block1;

  block5:
  goto block7;

  block1:
  *label_CastError = true;
  return;

  block7:
  return tmp2;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/promise-abstract-operations.tq?l=56&c=7
inline Tagged<JSProxy> TqRuntimeCast_JSProxy_1(Tagged<Context> p_context, Tagged<Object> p_o, bool* label_CastError) {
  Tagged<HeapObject> tmp0{};  USE(tmp0);
  bool label1 = false;
  Tagged<JSProxy> tmp2{};  USE(tmp2);
  bool label3 = false;
  goto block0;

  block0:
  tmp0 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedToHeapObject(p_o, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  goto block1;

  block3:
  tmp2 = TqRuntimeCast_JSProxy_0(tmp0, &label3);
  if (label3) {
    goto block6;
  }
  goto block5;

  block6:
  goto block1;

  block5:
  goto block7;

  block1:
  *label_CastError = true;
  return;

  block7:
  return tmp2;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-array.tq?l=61&c=1
inline Tagged<JSArray> TqRuntimeCast_JSArray_0(Tagged<HeapObject> p_obj, bool* label_CastError) {
  Tagged<JSArray> tmp0{};  USE(tmp0);
  bool label1 = false;
  goto block0;

  block0:
  tmp0 = TqRuntimeDownCastForTorqueClass_JSArray_0(p_obj, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  *label_CastError = true;
  return;

  block3:
  goto block5;

  block5:
  return tmp0;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-proxy.tq?l=5&c=1
inline Tagged<JSProxy> TqRuntimeCast_JSProxy_0(Tagged<HeapObject> p_obj, bool* label_CastError) {
  Tagged<JSProxy> tmp0{};  USE(tmp0);
  bool label1 = false;
  goto block0;

  block0:
  tmp0 = TqRuntimeDownCastForTorqueClass_JSProxy_0(p_obj, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  *label_CastError = true;
  return;

  block3:
  goto block5;

  block5:
  return tmp0;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-array.tq?l=61&c=1
inline Tagged<JSArray> TqRuntimeDownCastForTorqueClass_JSArray_0(Tagged<HeapObject> p_o, bool* label_CastError) {
  intptr_t tmp0{}; USE(tmp0);
  Tagged<Map> tmp1{}; USE(tmp1);
  Tagged<Map> tmp2{}; USE(tmp2);
  bool tmp3{}; USE(tmp3);
  intptr_t tmp4{}; USE(tmp4);
  InstanceType tmp5{}; USE(tmp5);
  uint32_t tmp6{}; USE(tmp6);
  bool tmp7{}; USE(tmp7);
  int32_t tmp8{}; USE(tmp8);
  intptr_t tmp9{}; USE(tmp9);
  InstanceType tmp10{}; USE(tmp10);
  uint16_t tmp11{}; USE(tmp11);
  int32_t tmp12{}; USE(tmp12);
  InstanceType tmp13{}; USE(tmp13);
  uint16_t tmp14{}; USE(tmp14);
  int32_t tmp15{}; USE(tmp15);
  int32_t tmp16{}; USE(tmp16);
  uint32_t tmp17{}; USE(tmp17);
  uint32_t tmp18{}; USE(tmp18);
  bool tmp19{}; USE(tmp19);
  Tagged<JSArray> tmp20{}; USE(tmp20);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(0);
  tmp1 = TaggedField<Tagged<Map>>::load(UncheckedCast<HeapObject>(p_o), static_cast<int>(tmp0));
  if (((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprInt31Equal(static_cast<InstanceType>(2119), static_cast<InstanceType>(2119))))) {
    goto block3;
  } else {
    goto block4;
  }

  block3:
  if ((CodeStubAssembler(state_).ClassHasMapConstant<JSArray>())) {
    goto block6;
  } else {
    goto block7;
  }

  block6:
  tmp2 = []() -> Tagged<Map> { UNREACHABLE(); }();
  tmp3 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedNotEqual(tmp1, tmp2);
  if (tmp3) {
    goto block9;
  } else {
    goto block10;
  }

  block9:
  goto block1;

  block10:
  goto block8;

  block7:
  tmp4 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp5 = (tmp1)->ReadField<InstanceType>(tmp4);
  tmp6 = TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0(static_cast<InstanceType>(2119));
  tmp7 = TorqueRuntimeMacroShims::CodeStubAssembler::Word32NotEqual(tmp5, tmp6);
  if (tmp7) {
    goto block11;
  } else {
    goto block12;
  }

  block11:
  goto block1;

  block12:
  goto block8;

  block8:
  goto block5;

  block4:
  tmp8 = TqRuntimeFromConstexpr_int32_constexpr_int32_0((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprUint32Sub(static_cast<InstanceType>(2119), static_cast<InstanceType>(2119))));
  tmp9 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp10 = (tmp1)->ReadField<InstanceType>(tmp9);
  tmp11 = TqRuntimeConvert_uint16_InstanceType_0(tmp10);
  tmp12 = TqRuntimeConvert_int32_uint16_0(tmp11);
  tmp13 = TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0(static_cast<InstanceType>(2119));
  tmp14 = TqRuntimeConvert_uint16_InstanceType_0(tmp13);
  tmp15 = TqRuntimeConvert_int32_uint16_0(tmp14);
  tmp16 = TorqueRuntimeMacroShims::CodeStubAssembler::Int32Sub(tmp12, tmp15);
  tmp17 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp16);
  tmp18 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp8);
  tmp19 = TorqueRuntimeMacroShims::CodeStubAssembler::Uint32GreaterThan(tmp17, tmp18);
  if (tmp19) {
    goto block13;
  } else {
    goto block14;
  }

  block13:
  goto block1;

  block14:
  goto block5;

  block5:
  tmp20 = static_cast<Tagged<JSArray>>(p_o);
  goto block15;

  block1:
  *label_CastError = true;
  return;

  block15:
  return tmp20;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-proxy.tq?l=5&c=1
inline Tagged<JSProxy> TqRuntimeDownCastForTorqueClass_JSProxy_0(Tagged<HeapObject> p_o, bool* label_CastError) {
  intptr_t tmp0{}; USE(tmp0);
  Tagged<Map> tmp1{}; USE(tmp1);
  Tagged<Map> tmp2{}; USE(tmp2);
  bool tmp3{}; USE(tmp3);
  intptr_t tmp4{}; USE(tmp4);
  InstanceType tmp5{}; USE(tmp5);
  uint32_t tmp6{}; USE(tmp6);
  bool tmp7{}; USE(tmp7);
  int32_t tmp8{}; USE(tmp8);
  intptr_t tmp9{}; USE(tmp9);
  InstanceType tmp10{}; USE(tmp10);
  uint16_t tmp11{}; USE(tmp11);
  int32_t tmp12{}; USE(tmp12);
  InstanceType tmp13{}; USE(tmp13);
  uint16_t tmp14{}; USE(tmp14);
  int32_t tmp15{}; USE(tmp15);
  int32_t tmp16{}; USE(tmp16);
  uint32_t tmp17{}; USE(tmp17);
  uint32_t tmp18{}; USE(tmp18);
  bool tmp19{}; USE(tmp19);
  Tagged<JSProxy> tmp20{}; USE(tmp20);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(0);
  tmp1 = TaggedField<Tagged<Map>>::load(UncheckedCast<HeapObject>(p_o), static_cast<int>(tmp0));
  if (((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprInt31Equal(static_cast<InstanceType>(299), static_cast<InstanceType>(299))))) {
    goto block3;
  } else {
    goto block4;
  }

  block3:
  if ((CodeStubAssembler(state_).ClassHasMapConstant<JSProxy>())) {
    goto block6;
  } else {
    goto block7;
  }

  block6:
  tmp2 = []() -> Tagged<Map> { UNREACHABLE(); }();
  tmp3 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedNotEqual(tmp1, tmp2);
  if (tmp3) {
    goto block9;
  } else {
    goto block10;
  }

  block9:
  goto block1;

  block10:
  goto block8;

  block7:
  tmp4 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp5 = (tmp1)->ReadField<InstanceType>(tmp4);
  tmp6 = TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0(static_cast<InstanceType>(299));
  tmp7 = TorqueRuntimeMacroShims::CodeStubAssembler::Word32NotEqual(tmp5, tmp6);
  if (tmp7) {
    goto block11;
  } else {
    goto block12;
  }

  block11:
  goto block1;

  block12:
  goto block8;

  block8:
  goto block5;

  block4:
  tmp8 = TqRuntimeFromConstexpr_int32_constexpr_int32_0((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprUint32Sub(static_cast<InstanceType>(299), static_cast<InstanceType>(299))));
  tmp9 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp10 = (tmp1)->ReadField<InstanceType>(tmp9);
  tmp11 = TqRuntimeConvert_uint16_InstanceType_0(tmp10);
  tmp12 = TqRuntimeConvert_int32_uint16_0(tmp11);
  tmp13 = TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0(static_cast<InstanceType>(299));
  tmp14 = TqRuntimeConvert_uint16_InstanceType_0(tmp13);
  tmp15 = TqRuntimeConvert_int32_uint16_0(tmp14);
  tmp16 = TorqueRuntimeMacroShims::CodeStubAssembler::Int32Sub(tmp12, tmp15);
  tmp17 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp16);
  tmp18 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp8);
  tmp19 = TorqueRuntimeMacroShims::CodeStubAssembler::Uint32GreaterThan(tmp17, tmp18);
  if (tmp19) {
    goto block13;
  } else {
    goto block14;
  }

  block13:
  goto block1;

  block14:
  goto block5;

  block5:
  tmp20 = static_cast<Tagged<JSProxy>>(p_o);
  goto block15;

  block1:
  *label_CastError = true;
  return;

  block15:
  return tmp20;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=73&c=1
inline intptr_t TqRuntimeFromConstexpr_intptr_constexpr_int31_0(int31_t p_i) {
  intptr_t tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = (CastToUnderlyingTypeIfEnum(p_i));
  goto block2;

  block2:
  return tmp0;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=127&c=1
inline uint32_t TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0(uint32_t p_i) {
  int32_t tmp0{}; USE(tmp0);
  uint32_t tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = (CastToUnderlyingTypeIfEnum(p_i));
  tmp1 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp0);
  goto block2;

  block2:
  return tmp1;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=70&c=1
inline int32_t TqRuntimeFromConstexpr_int32_constexpr_int32_0(int32_t p_i) {
  int32_t tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = (CastToUnderlyingTypeIfEnum(p_i));
  goto block2;

  block2:
  return tmp0;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/string.tq?l=13&c=9
inline uint16_t TqRuntimeConvert_uint16_InstanceType_0(InstanceType p_i) {
  goto block0;

  block0:
  goto block2;

  block2:
  return p_i;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=249&c=1
inline int32_t TqRuntimeConvert_int32_uint16_0(uint16_t p_i) {
  uint32_t tmp0{}; USE(tmp0);
  int32_t tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = TqRuntimeConvert_WasmCodePointer_uint16_0(p_i);
  tmp1 = TorqueRuntimeMacroShims::CodeStubAssembler::Signed(tmp0);
  goto block2;

  block2:
  return tmp1;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=172&c=1
inline InstanceType TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0(InstanceType p_c) {
  uint16_t tmp0{}; USE(tmp0);
  InstanceType tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = TorqueRuntimeMacroShims::CodeStubAssembler::Uint16Constant(p_c);
  tmp1 = static_cast<InstanceType>(tmp0);
  goto block2;

  block2:
  return tmp1;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=250&c=17
inline uint32_t TqRuntimeConvert_WasmCodePointer_uint16_0(uint16_t p_i) {
  goto block0;

  block0:
  goto block2;

  block2:
  return p_i;
}


}  // namespace v8::internal
