// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/array-isarray.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/execution/isolate-inl.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/roots/roots-inl.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"
#include "torque-generated/cc-builtins-types.h"

namespace v8::internal {

// kCCBuiltins Phase 5 (revised) Task 5.8 — inline accessors for
// NamespaceConstants reachable from whitelisted builtins.
// Proper NamespaceConstant emission under kCCBuiltins is Phase 6
// groundwork; these hand-written inlines cover `const True` /
// `const False` from base.tq (torque-suffixed `_0`) so the
// ArrayIsArray fixture links. Phase 6.1 (I-1 follow-up) moved
// the `Isolate::Current()` lookup into the helper body — the
// emitter now emits `True_0()` / `False_0()` with no argument,
// so the same helper works from the outer builtin body and from
// nested TqRuntime* helper bodies without an `isolate` token
// needing to be in scope at the call site.
inline Tagged<True> True_0() {
  return Cast<True>(ReadOnlyRoots(Isolate::Current()).true_value());
}
inline Tagged<False> False_0() {
  return Cast<False>(
      ReadOnlyRoots(Isolate::Current()).false_value());
}

// Phase 8 — NumberConstant lives here (not in runtime-macro-shims.h)
// because its body needs factory.h and conversions-inl.h, which
// pull descriptor-array-tq-inl.inc transitively when included from
// the shims header — that .inc forward-references
// TorqueRuntimeMacroShims::CodeStubAssembler before the namespace
// is opened, breaking compilation. Emitting in the per-TU
// preamble means each kCCBuiltins .cc resolves NumberConstant
// against its own already-included factory-inl.h /
// conversions-inl.h. Inside the proper torque-shim namespace so
// the emitter's qualified emission `TorqueRuntimeMacroShims::
// CodeStubAssembler::NumberConstant(...)` resolves cleanly.
namespace TorqueRuntimeMacroShims {
namespace CodeStubAssembler {
inline Tagged<Number> NumberConstant(double v) {
  int smi_value;
  if (DoubleToSmiInteger(v, &smi_value)) {
    return Cast<Number>(Smi::FromInt(smi_value));
  }
  Isolate* isolate = Isolate::Current();
  return Cast<Number>(*isolate->factory()->NewHeapNumber(v));
}
// Phase 9A — shims for the catch-flow lowering. Live here, not
// in runtime-macro-shims.h, because they need factory.h /
// isolate-inl.h which would re-enter the descriptor-array-tq-inl
// include chain (see NumberConstant rationale above).
// `StringConstant(const char*)` interns a C-string literal as a
// V8 String. `GetPendingMessage` / `SetPendingMessage` access
// the isolate's pending-message slot used by the catch-flow
// machinery in TqRuntimeGetAndResetPendingMessage_0.
inline Tagged<String> StringConstant(const char* s) {
  Isolate* isolate = Isolate::Current();
  return *isolate->factory()->InternalizeUtf8String(s);
}
inline Tagged<Union<Hole, JSMessageObject>> GetPendingMessage() {
  return UncheckedCast<Union<Hole, JSMessageObject>>(
      Isolate::Current()->pending_message());
}
inline void SetPendingMessage(Tagged<Hole> v) {
  Isolate::Current()->set_pending_message(v);
}
}  // namespace CodeStubAssembler
}  // namespace TorqueRuntimeMacroShims

// Phase 9A — `TheHole_0()` mirrors True_0/False_0: emitter spells
// the bare name with no `isolate` arg under kCCBuiltins, so we
// internally fetch via Isolate::Current(). Used by the catch-flow
// machinery to clear the pending-message slot.
inline Tagged<Hole> TheHole_0() {
  return Cast<Hole>(
      ReadOnlyRoots(Isolate::Current()).the_hole_value());
}
// Phase 9A — `Undefined_0()` mirrors True_0/False_0/TheHole_0:
// torque emits the bare `Undefined` namespace-constant as
// `Undefined_0()` under kCCBuiltins. Used by callers that
// pass `Undefined` as a JSAny argument (e.g. the catch-block
// fixture's `ThrowCalledNonCallable(Undefined)` site).
inline Tagged<Undefined> Undefined_0() {
  return Cast<Undefined>(
      ReadOnlyRoots(Isolate::Current()).undefined_value());
}

// Phase 8 — TFC builtin C bridges. `Add` and `NonNumberToNumeric`
// are TFC (Torque, Function, Custom-call-descriptor) builtins —
// CSA-emitted to native code at snapshot time, NO `Builtin_<Name>`
// C symbol exists in any v8 lib. The kCCBuiltins emitter spells
// `Builtin_<Callee>(Isolate::Current(), args...)` at call sites,
// so we provide inline C functions here that wrap V8's high-level
// APIs (Object::ToNumeric, direct Number+Number arithmetic). The
// inline'd definition lives in every kCCBuiltins .cc TU; the
// linker dedupes via vague linkage. catch_block is deferred (Phase
// 9+), so the rare Symbol-input branch of NonNumberToNumeric
// UNREACHABLEs instead of throwing TypeError.
//
// Phase 9.7 — Builtin_Add and Builtin_Subtract delegate to V8's
// canonical Object::NumberValue + factory->NewNumber(double) APIs
// rather than re-implementing JS-spec Smi/HeapNumber arithmetic.
// `factory->NewNumber(double)` (factory-base.h:119) does the
// Smi/HeapNumber discrimination spec-correctly — same fast path
// Object::Add takes for Number+Number (objects.cc:Add). For our
// `tail Add(n, 1)` / `tail Subtract(n, 1)` call sites, torque's
// type system already excluded String / BigInt / ToPrimitive
// shapes, so we only need the Number+Number branch.
//
// Why not Object::Add directly? It returns MaybeDirectHandle<Object>
// (handles string concat / ToPrimitive failure) — for our
// statically-typed Number+Number case the fail branch is
// unreachable, and the MaybeHandle ceremony (HandleScope, ToHandle
// dispatch) is more code than the direct delegation below. The
// `Object::NumberValue + factory->NewNumber` path is what
// Object::Add itself takes internally for the Number+Number arm.
//
// Object::Subtract has no equivalent static helper in V8 (Add gets
// special treatment because of string concat); the direct path
// here is the canonical V8-internal pattern for both.
inline Tagged<Number> Builtin_Add(Isolate* isolate,
                                  Tagged<Context> context,
                                  Tagged<Number> left,
                                  Tagged<Number> right) {
  USE(context);
  double sum = Object::NumberValue(left) + Object::NumberValue(right);
  return *isolate->factory()->NewNumber(sum);
}

inline Tagged<Number> Builtin_Subtract(Isolate* isolate,
                                       Tagged<Context> context,
                                       Tagged<Number> left,
                                       Tagged<Number> right) {
  USE(context);
  double diff = Object::NumberValue(left) - Object::NumberValue(right);
  return *isolate->factory()->NewNumber(diff);
}

// `Builtin_NonNumberToNumeric` wraps Object::ToNumeric, which
// implements ECMAScript ToNumeric (string parse, boolean→Smi,
// null/undefined coercion, ToPrimitive recurse). Symbol inputs
// throw TypeError under spec — we UNREACHABLE because the
// kCCBuiltins emitter has no exception path yet (Phase 9+).
// Call sites in kCCBuiltins emission (UnaryOp1's JSAnyNotNumeric
// arm) only feed JSAnyNotNumeric inputs here, so Number/BigInt
// short-circuit before reaching this shim.
inline Tagged<Numeric> Builtin_NonNumberToNumeric(
    Isolate* isolate, Tagged<Context> context,
    Tagged<JSAny> input) {
  USE(context);
  // No inner HandleScope — the outer JS-linkage adaptor frame
  // already provides one. An inner scope would invalidate the
  // returned Tagged on close.
  Handle<JSAny> input_handle(input, isolate);
  DirectHandle<Object> result;
  if (!Object::ToNumeric(isolate, input_handle).ToHandle(&result)) {
    UNREACHABLE();  // Symbol input → TypeError; catch_block deferred.
  }
  return Cast<Numeric>(*result);
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/array-flat.tq?l=65&c=13
Tagged<JSArray> TqRuntimeCast_JSArray_1(Tagged<Context> p_context, Tagged<Object> p_o, bool* label_CastError);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/promise-abstract-operations.tq?l=56&c=7
Tagged<JSProxy> TqRuntimeCast_JSProxy_1(Tagged<Context> p_context, Tagged<Object> p_o, bool* label_CastError);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-array.tq?l=61&c=1
Tagged<JSArray> TqRuntimeCast_JSArray_0(Tagged<HeapObject> p_obj, bool* label_CastError);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-proxy.tq?l=5&c=1
Tagged<JSProxy> TqRuntimeCast_JSProxy_0(Tagged<HeapObject> p_obj, bool* label_CastError);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-array.tq?l=61&c=1
Tagged<JSArray> TqRuntimeDownCastForTorqueClass_JSArray_0(Tagged<HeapObject> p_o, bool* label_CastError);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-proxy.tq?l=5&c=1
Tagged<JSProxy> TqRuntimeDownCastForTorqueClass_JSProxy_0(Tagged<HeapObject> p_o, bool* label_CastError);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=73&c=1
intptr_t TqRuntimeFromConstexpr_intptr_constexpr_int31_0(int31_t p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=127&c=1
uint32_t TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0(uint32_t p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=70&c=1
int32_t TqRuntimeFromConstexpr_int32_constexpr_int32_0(int32_t p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/string.tq?l=13&c=9
uint16_t TqRuntimeConvert_uint16_InstanceType_0(InstanceType p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=249&c=1
int32_t TqRuntimeConvert_int32_uint16_0(uint16_t p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=172&c=1
InstanceType TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0(InstanceType p_c);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=250&c=17
uint32_t TqRuntimeConvert_WasmCodePointer_uint16_0(uint16_t p_i);

// Builtin: ArrayIsArray
Address Builtin_ArrayIsArray(int args_length, Address* args_object,
                         Isolate* isolate) {
  DCHECK(isolate->context().is_null() || IsContext(isolate->context()));
  BuiltinArguments args(args_length, args_object);
  HandleScope scope(isolate);
  USE(isolate);
  Tagged<NativeContext> parameter0 = Cast<NativeContext>(isolate->context());
  USE(parameter0);
  Tagged<NativeContext> context = parameter0;
  USE(context);
  Tagged<JSAny> parameter1 = Cast<JSAny>(args[1]);
  USE(parameter1);
  Tagged<JSAny> arg = parameter1;
  USE(arg);
  Tagged<JSArray> tmp0{};  USE(tmp0);
  bool label1 = false;
  Tagged<JSProxy> tmp2{};  USE(tmp2);
  bool label3 = false;
  Tagged<True> tmp4{}; USE(tmp4);
  Tagged<False> tmp5{}; USE(tmp5);
  Tagged<JSAny> tmp6{};  USE(tmp6);
  goto block0;

  block0:
  tmp0 = TqRuntimeCast_JSArray_1(parameter0, parameter1, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  tmp2 = TqRuntimeCast_JSProxy_1(parameter0, UncheckedCast<JSAny>(parameter1), &label3);
  if (label3) {
    goto block8;
  }
  goto block7;

  block3:
  tmp4 = True_0();
  return tmp4.ptr();

  block8:
  tmp5 = False_0();
  return tmp5.ptr();

  block7:
  {
    Address __rt_args[] = { parameter1.ptr() };
    tmp6 = UncheckedCast<JSAny>(Tagged<Object>(Runtime_ArrayIsArray(1, __rt_args, isolate)));
  }
  return tmp6.ptr();
}

#ifndef V8_INTERNAL_DEFINED_TqRuntimeCast_JSArray_1
#define V8_INTERNAL_DEFINED_TqRuntimeCast_JSArray_1

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/array-flat.tq?l=65&c=13
inline Tagged<JSArray> TqRuntimeCast_JSArray_1(Tagged<Context> p_context, Tagged<Object> p_o, bool* label_CastError) {
  Tagged<HeapObject> tmp0{};  USE(tmp0);
  bool label1 = false;
  Tagged<JSArray> tmp2{};  USE(tmp2);
  bool label3 = false;
  goto block0;

  block0:
  tmp0 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedToHeapObject(p_o, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  goto block1;

  block3:
  tmp2 = TqRuntimeCast_JSArray_0(tmp0, &label3);
  if (label3) {
    goto block6;
  }
  goto block5;

  block6:
  goto block1;

  block5:
  goto block7;

  block1:
  *label_CastError = true;
  return {};

  block7:
  return tmp2;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeCast_JSArray_1
#ifndef V8_INTERNAL_DEFINED_TqRuntimeCast_JSProxy_1
#define V8_INTERNAL_DEFINED_TqRuntimeCast_JSProxy_1

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/promise-abstract-operations.tq?l=56&c=7
inline Tagged<JSProxy> TqRuntimeCast_JSProxy_1(Tagged<Context> p_context, Tagged<Object> p_o, bool* label_CastError) {
  Tagged<HeapObject> tmp0{};  USE(tmp0);
  bool label1 = false;
  Tagged<JSProxy> tmp2{};  USE(tmp2);
  bool label3 = false;
  goto block0;

  block0:
  tmp0 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedToHeapObject(p_o, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  goto block1;

  block3:
  tmp2 = TqRuntimeCast_JSProxy_0(tmp0, &label3);
  if (label3) {
    goto block6;
  }
  goto block5;

  block6:
  goto block1;

  block5:
  goto block7;

  block1:
  *label_CastError = true;
  return {};

  block7:
  return tmp2;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeCast_JSProxy_1
#ifndef V8_INTERNAL_DEFINED_TqRuntimeCast_JSArray_0
#define V8_INTERNAL_DEFINED_TqRuntimeCast_JSArray_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-array.tq?l=61&c=1
inline Tagged<JSArray> TqRuntimeCast_JSArray_0(Tagged<HeapObject> p_obj, bool* label_CastError) {
  Tagged<JSArray> tmp0{};  USE(tmp0);
  bool label1 = false;
  goto block0;

  block0:
  tmp0 = TqRuntimeDownCastForTorqueClass_JSArray_0(p_obj, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  *label_CastError = true;
  return {};

  block3:
  goto block5;

  block5:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeCast_JSArray_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeCast_JSProxy_0
#define V8_INTERNAL_DEFINED_TqRuntimeCast_JSProxy_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-proxy.tq?l=5&c=1
inline Tagged<JSProxy> TqRuntimeCast_JSProxy_0(Tagged<HeapObject> p_obj, bool* label_CastError) {
  Tagged<JSProxy> tmp0{};  USE(tmp0);
  bool label1 = false;
  goto block0;

  block0:
  tmp0 = TqRuntimeDownCastForTorqueClass_JSProxy_0(p_obj, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  *label_CastError = true;
  return {};

  block3:
  goto block5;

  block5:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeCast_JSProxy_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeDownCastForTorqueClass_JSArray_0
#define V8_INTERNAL_DEFINED_TqRuntimeDownCastForTorqueClass_JSArray_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-array.tq?l=61&c=1
inline Tagged<JSArray> TqRuntimeDownCastForTorqueClass_JSArray_0(Tagged<HeapObject> p_o, bool* label_CastError) {
  intptr_t tmp0{}; USE(tmp0);
  Tagged<Map> tmp1{}; USE(tmp1);
  Tagged<Map> tmp2{}; USE(tmp2);
  bool tmp3{}; USE(tmp3);
  intptr_t tmp4{}; USE(tmp4);
  InstanceType tmp5{}; USE(tmp5);
  uint32_t tmp6{}; USE(tmp6);
  bool tmp7{}; USE(tmp7);
  int32_t tmp8{}; USE(tmp8);
  intptr_t tmp9{}; USE(tmp9);
  InstanceType tmp10{}; USE(tmp10);
  uint16_t tmp11{}; USE(tmp11);
  int32_t tmp12{}; USE(tmp12);
  InstanceType tmp13{}; USE(tmp13);
  uint16_t tmp14{}; USE(tmp14);
  int32_t tmp15{}; USE(tmp15);
  int32_t tmp16{}; USE(tmp16);
  uint32_t tmp17{}; USE(tmp17);
  uint32_t tmp18{}; USE(tmp18);
  bool tmp19{}; USE(tmp19);
  Tagged<JSArray> tmp20{}; USE(tmp20);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(0);
  tmp1 = TaggedField<Tagged<Map>>::load(UncheckedCast<HeapObject>(p_o), static_cast<int>(tmp0));
  if (((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprInt31Equal(static_cast<InstanceType>(2119), static_cast<InstanceType>(2119))))) {
    goto block3;
  } else {
    goto block4;
  }

  block3:
  if ((false)) {
    goto block6;
  } else {
    goto block7;
  }

  block6:
  tmp2 = []() -> Tagged<Map> { UNREACHABLE(); }();
  tmp3 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedNotEqual(tmp1, tmp2);
  if (tmp3) {
    goto block9;
  } else {
    goto block10;
  }

  block9:
  goto block1;

  block10:
  goto block8;

  block7:
  tmp4 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp5 = UncheckedCast<HeapObject>(tmp1)->ReadField<InstanceType>(tmp4);
  tmp6 = TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0(static_cast<InstanceType>(2119));
  tmp7 = TorqueRuntimeMacroShims::CodeStubAssembler::Word32NotEqual(tmp5, tmp6);
  if (tmp7) {
    goto block11;
  } else {
    goto block12;
  }

  block11:
  goto block1;

  block12:
  goto block8;

  block8:
  goto block5;

  block4:
  tmp8 = TqRuntimeFromConstexpr_int32_constexpr_int32_0((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprUint32Sub(static_cast<InstanceType>(2119), static_cast<InstanceType>(2119))));
  tmp9 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp10 = UncheckedCast<HeapObject>(tmp1)->ReadField<InstanceType>(tmp9);
  tmp11 = TqRuntimeConvert_uint16_InstanceType_0(tmp10);
  tmp12 = TqRuntimeConvert_int32_uint16_0(tmp11);
  tmp13 = TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0(static_cast<InstanceType>(2119));
  tmp14 = TqRuntimeConvert_uint16_InstanceType_0(tmp13);
  tmp15 = TqRuntimeConvert_int32_uint16_0(tmp14);
  tmp16 = TorqueRuntimeMacroShims::CodeStubAssembler::Int32Sub(tmp12, tmp15);
  tmp17 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp16);
  tmp18 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp8);
  tmp19 = TorqueRuntimeMacroShims::CodeStubAssembler::Uint32GreaterThan(tmp17, tmp18);
  if (tmp19) {
    goto block13;
  } else {
    goto block14;
  }

  block13:
  goto block1;

  block14:
  goto block5;

  block5:
  tmp20 = UncheckedCast<JSArray>(p_o);
  goto block15;

  block1:
  *label_CastError = true;
  return {};

  block15:
  return tmp20;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeDownCastForTorqueClass_JSArray_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeDownCastForTorqueClass_JSProxy_0
#define V8_INTERNAL_DEFINED_TqRuntimeDownCastForTorqueClass_JSProxy_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/js-proxy.tq?l=5&c=1
inline Tagged<JSProxy> TqRuntimeDownCastForTorqueClass_JSProxy_0(Tagged<HeapObject> p_o, bool* label_CastError) {
  intptr_t tmp0{}; USE(tmp0);
  Tagged<Map> tmp1{}; USE(tmp1);
  Tagged<Map> tmp2{}; USE(tmp2);
  bool tmp3{}; USE(tmp3);
  intptr_t tmp4{}; USE(tmp4);
  InstanceType tmp5{}; USE(tmp5);
  uint32_t tmp6{}; USE(tmp6);
  bool tmp7{}; USE(tmp7);
  int32_t tmp8{}; USE(tmp8);
  intptr_t tmp9{}; USE(tmp9);
  InstanceType tmp10{}; USE(tmp10);
  uint16_t tmp11{}; USE(tmp11);
  int32_t tmp12{}; USE(tmp12);
  InstanceType tmp13{}; USE(tmp13);
  uint16_t tmp14{}; USE(tmp14);
  int32_t tmp15{}; USE(tmp15);
  int32_t tmp16{}; USE(tmp16);
  uint32_t tmp17{}; USE(tmp17);
  uint32_t tmp18{}; USE(tmp18);
  bool tmp19{}; USE(tmp19);
  Tagged<JSProxy> tmp20{}; USE(tmp20);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(0);
  tmp1 = TaggedField<Tagged<Map>>::load(UncheckedCast<HeapObject>(p_o), static_cast<int>(tmp0));
  if (((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprInt31Equal(static_cast<InstanceType>(299), static_cast<InstanceType>(299))))) {
    goto block3;
  } else {
    goto block4;
  }

  block3:
  if ((false)) {
    goto block6;
  } else {
    goto block7;
  }

  block6:
  tmp2 = []() -> Tagged<Map> { UNREACHABLE(); }();
  tmp3 = TorqueRuntimeMacroShims::CodeStubAssembler::TaggedNotEqual(tmp1, tmp2);
  if (tmp3) {
    goto block9;
  } else {
    goto block10;
  }

  block9:
  goto block1;

  block10:
  goto block8;

  block7:
  tmp4 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp5 = UncheckedCast<HeapObject>(tmp1)->ReadField<InstanceType>(tmp4);
  tmp6 = TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0(static_cast<InstanceType>(299));
  tmp7 = TorqueRuntimeMacroShims::CodeStubAssembler::Word32NotEqual(tmp5, tmp6);
  if (tmp7) {
    goto block11;
  } else {
    goto block12;
  }

  block11:
  goto block1;

  block12:
  goto block8;

  block8:
  goto block5;

  block4:
  tmp8 = TqRuntimeFromConstexpr_int32_constexpr_int32_0((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprUint32Sub(static_cast<InstanceType>(299), static_cast<InstanceType>(299))));
  tmp9 = TqRuntimeFromConstexpr_intptr_constexpr_int31_0(12);
  tmp10 = UncheckedCast<HeapObject>(tmp1)->ReadField<InstanceType>(tmp9);
  tmp11 = TqRuntimeConvert_uint16_InstanceType_0(tmp10);
  tmp12 = TqRuntimeConvert_int32_uint16_0(tmp11);
  tmp13 = TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0(static_cast<InstanceType>(299));
  tmp14 = TqRuntimeConvert_uint16_InstanceType_0(tmp13);
  tmp15 = TqRuntimeConvert_int32_uint16_0(tmp14);
  tmp16 = TorqueRuntimeMacroShims::CodeStubAssembler::Int32Sub(tmp12, tmp15);
  tmp17 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp16);
  tmp18 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp8);
  tmp19 = TorqueRuntimeMacroShims::CodeStubAssembler::Uint32GreaterThan(tmp17, tmp18);
  if (tmp19) {
    goto block13;
  } else {
    goto block14;
  }

  block13:
  goto block1;

  block14:
  goto block5;

  block5:
  tmp20 = UncheckedCast<JSProxy>(p_o);
  goto block15;

  block1:
  *label_CastError = true;
  return {};

  block15:
  return tmp20;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeDownCastForTorqueClass_JSProxy_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_intptr_constexpr_int31_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_intptr_constexpr_int31_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=73&c=1
inline intptr_t TqRuntimeFromConstexpr_intptr_constexpr_int31_0(int31_t p_i) {
  intptr_t tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = (CastToUnderlyingTypeIfEnum(p_i));
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_intptr_constexpr_int31_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=127&c=1
inline uint32_t TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0(uint32_t p_i) {
  int32_t tmp0{}; USE(tmp0);
  uint32_t tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = (CastToUnderlyingTypeIfEnum(p_i));
  tmp1 = TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned(tmp0);
  goto block2;

  block2:
  return tmp1;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_WasmCodePointer_constexpr_WasmCodePointer_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_int32_constexpr_int32_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_int32_constexpr_int32_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=70&c=1
inline int32_t TqRuntimeFromConstexpr_int32_constexpr_int32_0(int32_t p_i) {
  int32_t tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = (CastToUnderlyingTypeIfEnum(p_i));
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_int32_constexpr_int32_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeConvert_uint16_InstanceType_0
#define V8_INTERNAL_DEFINED_TqRuntimeConvert_uint16_InstanceType_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/objects/string.tq?l=13&c=9
inline uint16_t TqRuntimeConvert_uint16_InstanceType_0(InstanceType p_i) {
  goto block0;

  block0:
  goto block2;

  block2:
  return p_i;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeConvert_uint16_InstanceType_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeConvert_int32_uint16_0
#define V8_INTERNAL_DEFINED_TqRuntimeConvert_int32_uint16_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=249&c=1
inline int32_t TqRuntimeConvert_int32_uint16_0(uint16_t p_i) {
  uint32_t tmp0{}; USE(tmp0);
  int32_t tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = TqRuntimeConvert_WasmCodePointer_uint16_0(p_i);
  tmp1 = TorqueRuntimeMacroShims::CodeStubAssembler::Signed(tmp0);
  goto block2;

  block2:
  return tmp1;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeConvert_int32_uint16_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=172&c=1
inline InstanceType TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0(InstanceType p_c) {
  uint16_t tmp0{}; USE(tmp0);
  InstanceType tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = TorqueRuntimeMacroShims::CodeStubAssembler::Uint16Constant(p_c);
  tmp1 = static_cast<InstanceType>(tmp0);
  goto block2;

  block2:
  return tmp1;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_InstanceType_constexpr_InstanceType_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeConvert_WasmCodePointer_uint16_0
#define V8_INTERNAL_DEFINED_TqRuntimeConvert_WasmCodePointer_uint16_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=250&c=17
inline uint32_t TqRuntimeConvert_WasmCodePointer_uint16_0(uint16_t p_i) {
  goto block0;

  block0:
  goto block2;

  block2:
  return p_i;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeConvert_WasmCodePointer_uint16_0

}  // namespace v8::internal
