// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/call-csa-macro-and-branch.tq
// DO NOT EDIT.

namespace v8::internal {

Tagged<Smi> Builtin_TorqueCcTest_CallCsaMacroAndBranch(Isolate* isolate, Tagged<Context> context) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  bool label0 = false;
  Tagged<Smi> tmp1{}; USE(tmp1);
  Tagged<Smi> tmp2{}; USE(tmp2);
  goto block0;

  block0:
  TorqueRuntimeMacroShims::CodeStubAssembler::GotoIfForceSlowPath(&label0);
  if (label0) {
    goto block4;
  }
  goto block3;

  block4:
  tmp1 = Smi::FromInt(CastToUnderlyingTypeIfEnum((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprIntegerLiteralToInt31(IntegerLiteral(false, 0x0ull)))));
  return tmp1;

  block3:
  tmp2 = Smi::FromInt(CastToUnderlyingTypeIfEnum((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprIntegerLiteralToInt31(IntegerLiteral(false, 0x1ull)))));
  return tmp2;
}


}  // namespace v8::internal
