// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/call-torque-macro.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/roots/roots-inl.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"

namespace v8::internal {

// kCCBuiltins Phase 5 (revised) Task 5.8 — inline accessors for
// NamespaceConstants reachable from whitelisted builtins.
// Proper NamespaceConstant emission under kCCBuiltins is Phase 6
// groundwork; these hand-written inlines cover `const True` /
// `const False` from base.tq (torque-suffixed `_0`) so the
// ArrayIsArray fixture links.
inline Tagged<True> True_0(Isolate* isolate) {
  return Cast<True>(ReadOnlyRoots(isolate).true_value());
}
inline Tagged<False> False_0(Isolate* isolate) {
  return Cast<False>(ReadOnlyRoots(isolate).false_value());
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/test/phase2-fixtures/call-torque-macro.tq?l=7&c=3
Tagged<Smi> TqRuntimeTorqueCcTest_CallMeFromBuiltin_0(Tagged<Smi> p_x, bool* label_Fail);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=56&c=1
Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=57&c=10
Tagged<Smi> TqRuntimeConvert_Smi_constexpr_int31_0(int31_t p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=85&c=1
Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_int31_0(int31_t p_i);

Tagged<Smi> Builtin_TorqueCcTest_CallTorqueMacro(Isolate* isolate, Tagged<Context> context, Tagged<Smi> arg) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = arg;
  USE(parameter1);
  Tagged<Smi> tmp0{};  USE(tmp0);
  bool label1 = false;
  Tagged<Smi> tmp2{}; USE(tmp2);
  goto block0;

  block0:
  tmp0 = TqRuntimeTorqueCcTest_CallMeFromBuiltin_0(parameter1, &label1);
  if (label1) {
    goto block4;
  }
  goto block3;

  block4:
  tmp2 = TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral(true, 0x1ull));
  return tmp2;

  block3:
  return tmp0;
}

#ifndef V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_CallMeFromBuiltin_0
#define V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_CallMeFromBuiltin_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/test/phase2-fixtures/call-torque-macro.tq?l=7&c=3
inline Tagged<Smi> TqRuntimeTorqueCcTest_CallMeFromBuiltin_0(Tagged<Smi> p_x, bool* label_Fail) {
  Tagged<Smi> tmp0{}; USE(tmp0);
  bool tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral(false, 0x0ull));
  tmp1 = TorqueRuntimeMacroShims::CodeStubAssembler::SmiEqual(p_x, tmp0);
  if (tmp1) {
    goto block3;
  } else {
    goto block4;
  }

  block3:
  *label_Fail = true;
  return {};

  block4:
  goto block5;

  block5:
  return p_x;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_CallMeFromBuiltin_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=56&c=1
inline Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral p_i) {
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = TqRuntimeConvert_Smi_constexpr_int31_0((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprIntegerLiteralToInt31(p_i)));
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeConvert_Smi_constexpr_int31_0
#define V8_INTERNAL_DEFINED_TqRuntimeConvert_Smi_constexpr_int31_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=57&c=10
inline Tagged<Smi> TqRuntimeConvert_Smi_constexpr_int31_0(int31_t p_i) {
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_Smi_constexpr_int31_0(p_i);
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeConvert_Smi_constexpr_int31_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_int31_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_int31_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=85&c=1
inline Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_int31_0(int31_t p_i) {
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = Smi::FromInt(CastToUnderlyingTypeIfEnum(p_i));
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_int31_0

}  // namespace v8::internal
