// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/call-runtime.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/roots/roots-inl.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"

namespace v8::internal {

// kCCBuiltins Phase 5 (revised) Task 5.8 — inline accessors for
// NamespaceConstants reachable from whitelisted builtins.
// Proper NamespaceConstant emission under kCCBuiltins is Phase 6
// groundwork; these hand-written inlines cover `const True` /
// `const False` from base.tq (torque-suffixed `_0`) so the
// ArrayIsArray fixture links.
inline Tagged<True> True_0(Isolate* isolate) {
  return Cast<True>(ReadOnlyRoots(isolate).true_value());
}
inline Tagged<False> False_0(Isolate* isolate) {
  return Cast<False>(ReadOnlyRoots(isolate).false_value());
}

Tagged<JSAny> Builtin_TorqueCcTest_CallRuntime(Isolate* isolate, Tagged<Context> context, Tagged<JSAny> arg) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<JSAny> parameter1 = arg;
  USE(parameter1);
  Tagged<JSAny> tmp0{};  USE(tmp0);
  goto block0;

  block0:
  {
    Address __rt_args[] = { parameter1.ptr() };
    tmp0 = UncheckedCast<JSAny>(Tagged<Object>(Runtime_ArrayIsArray(1, __rt_args, isolate)));
  }
  return tmp0;
}


}  // namespace v8::internal
