// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/catch-block.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/execution/isolate-inl.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/roots/roots-inl.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"

namespace v8::internal {

// kCCBuiltins Phase 5 (revised) Task 5.8 — inline accessors for
// NamespaceConstants reachable from whitelisted builtins.
// Proper NamespaceConstant emission under kCCBuiltins is Phase 6
// groundwork; these hand-written inlines cover `const True` /
// `const False` from base.tq (torque-suffixed `_0`) so the
// ArrayIsArray fixture links. Phase 6.1 (I-1 follow-up) moved
// the `Isolate::Current()` lookup into the helper body — the
// emitter now emits `True_0()` / `False_0()` with no argument,
// so the same helper works from the outer builtin body and from
// nested TqRuntime* helper bodies without an `isolate` token
// needing to be in scope at the call site.
inline Tagged<True> True_0() {
  return Cast<True>(ReadOnlyRoots(Isolate::Current()).true_value());
}
inline Tagged<False> False_0() {
  return Cast<False>(
      ReadOnlyRoots(Isolate::Current()).false_value());
}

// Phase 8 — NumberConstant lives here (not in runtime-macro-shims.h)
// because its body needs factory.h and conversions-inl.h, which
// pull descriptor-array-tq-inl.inc transitively when included from
// the shims header — that .inc forward-references
// TorqueRuntimeMacroShims::CodeStubAssembler before the namespace
// is opened, breaking compilation. Emitting in the per-TU
// preamble means each kCCBuiltins .cc resolves NumberConstant
// against its own already-included factory-inl.h /
// conversions-inl.h. Inside the proper torque-shim namespace so
// the emitter's qualified emission `TorqueRuntimeMacroShims::
// CodeStubAssembler::NumberConstant(...)` resolves cleanly.
namespace TorqueRuntimeMacroShims {
namespace CodeStubAssembler {
inline Tagged<Number> NumberConstant(double v) {
  int smi_value;
  if (DoubleToSmiInteger(v, &smi_value)) {
    return Cast<Number>(Smi::FromInt(smi_value));
  }
  Isolate* isolate = Isolate::Current();
  return Cast<Number>(*isolate->factory()->NewHeapNumber(v));
}
// Phase 9A — shims for the catch-flow lowering. Live here, not
// in runtime-macro-shims.h, because they need factory.h /
// isolate-inl.h which would re-enter the descriptor-array-tq-inl
// include chain (see NumberConstant rationale above).
// `StringConstant(const char*)` interns a C-string literal as a
// V8 String. `GetPendingMessage` / `SetPendingMessage` access
// the isolate's pending-message slot used by the catch-flow
// machinery in TqRuntimeGetAndResetPendingMessage_0.
inline Tagged<String> StringConstant(const char* s) {
  Isolate* isolate = Isolate::Current();
  return *isolate->factory()->InternalizeUtf8String(s);
}
inline Tagged<Union<Hole, JSMessageObject>> GetPendingMessage() {
  return UncheckedCast<Union<Hole, JSMessageObject>>(
      Isolate::Current()->pending_message());
}
inline void SetPendingMessage(Tagged<Hole> v) {
  Isolate::Current()->set_pending_message(v);
}
}  // namespace CodeStubAssembler
}  // namespace TorqueRuntimeMacroShims

// Phase 9A — `TheHole_0()` mirrors True_0/False_0: emitter spells
// the bare name with no `isolate` arg under kCCBuiltins, so we
// internally fetch via Isolate::Current(). Used by the catch-flow
// machinery to clear the pending-message slot.
inline Tagged<Hole> TheHole_0() {
  return Cast<Hole>(
      ReadOnlyRoots(Isolate::Current()).the_hole_value());
}
// Phase 9A — `Undefined_0()` mirrors True_0/False_0/TheHole_0:
// torque emits the bare `Undefined` namespace-constant as
// `Undefined_0()` under kCCBuiltins. Used by callers that
// pass `Undefined` as a JSAny argument (e.g. the catch-block
// fixture's `ThrowCalledNonCallable(Undefined)` site).
inline Tagged<Undefined> Undefined_0() {
  return Cast<Undefined>(
      ReadOnlyRoots(Isolate::Current()).undefined_value());
}

// Phase 8 — TFC builtin C bridges. `Add` and `NonNumberToNumeric`
// are TFC (Torque, Function, Custom-call-descriptor) builtins —
// CSA-emitted to native code at snapshot time, NO `Builtin_<Name>`
// C symbol exists in any v8 lib. The kCCBuiltins emitter spells
// `Builtin_<Callee>(Isolate::Current(), args...)` at call sites,
// so we provide inline C functions here that wrap V8's high-level
// APIs (Object::ToNumeric, direct Number+Number arithmetic). The
// inline'd definition lives in every kCCBuiltins .cc TU; the
// linker dedupes via vague linkage. catch_block is deferred (Phase
// 9+), so the rare Symbol-input branch of NonNumberToNumeric
// UNREACHABLEs instead of throwing TypeError.
//
// `Builtin_Add` covers only the Number(Number, Number) overload
// declared at number.tq:371 — the path Increment's `tail Add(n, 1)`
// hits, where both operands are Smi|HeapNumber. Full ECMA Add
// (string concat / BigInt / ToPrimitive) lives in the
// CSA-emitted Add Code object and is unaffected by this shim.
inline Tagged<Number> Builtin_Add(Isolate* isolate,
                                  Tagged<Context> context,
                                  Tagged<Number> left,
                                  Tagged<Number> right) {
  USE(context);
  if (IsSmi(left) && IsSmi(right)) {
    int64_t l = static_cast<int64_t>(Cast<Smi>(left).value());
    int64_t r = static_cast<int64_t>(Cast<Smi>(right).value());
    int64_t sum = l + r;
    if (Smi::IsValid(sum)) {
      return Cast<Number>(Smi::FromInt(static_cast<int>(sum)));
    }
    return Cast<Number>(
        *isolate->factory()->NewHeapNumber(static_cast<double>(sum)));
  }
  double l = IsSmi(left)
      ? static_cast<double>(Cast<Smi>(left).value())
      : Cast<HeapNumber>(left)->value();
  double r = IsSmi(right)
      ? static_cast<double>(Cast<Smi>(right).value())
      : Cast<HeapNumber>(right)->value();
  double sum = l + r;
  int smi_value;
  if (DoubleToSmiInteger(sum, &smi_value)) {
    return Cast<Number>(Smi::FromInt(smi_value));
  }
  return Cast<Number>(*isolate->factory()->NewHeapNumber(sum));
}

// `Builtin_Subtract` mirrors `Builtin_Add` for the Number(Number,
// Number) → Number overload at number.tq:373 — the path Decrement's
// `tail Subtract(n, 1)` hits. Same Smi/HeapNumber logic as Add,
// just with `l - r` instead of `l + r`.
inline Tagged<Number> Builtin_Subtract(Isolate* isolate,
                                       Tagged<Context> context,
                                       Tagged<Number> left,
                                       Tagged<Number> right) {
  USE(context);
  if (IsSmi(left) && IsSmi(right)) {
    int64_t l = static_cast<int64_t>(Cast<Smi>(left).value());
    int64_t r = static_cast<int64_t>(Cast<Smi>(right).value());
    int64_t diff = l - r;
    if (Smi::IsValid(diff)) {
      return Cast<Number>(Smi::FromInt(static_cast<int>(diff)));
    }
    return Cast<Number>(
        *isolate->factory()->NewHeapNumber(static_cast<double>(diff)));
  }
  double l = IsSmi(left)
      ? static_cast<double>(Cast<Smi>(left).value())
      : Cast<HeapNumber>(left)->value();
  double r = IsSmi(right)
      ? static_cast<double>(Cast<Smi>(right).value())
      : Cast<HeapNumber>(right)->value();
  double diff = l - r;
  int smi_value;
  if (DoubleToSmiInteger(diff, &smi_value)) {
    return Cast<Number>(Smi::FromInt(smi_value));
  }
  return Cast<Number>(*isolate->factory()->NewHeapNumber(diff));
}

// `Builtin_NonNumberToNumeric` wraps Object::ToNumeric, which
// implements ECMAScript ToNumeric (string parse, boolean→Smi,
// null/undefined coercion, ToPrimitive recurse). Symbol inputs
// throw TypeError under spec — we UNREACHABLE because the
// kCCBuiltins emitter has no exception path yet (Phase 9+).
// Call sites in kCCBuiltins emission (UnaryOp1's JSAnyNotNumeric
// arm) only feed JSAnyNotNumeric inputs here, so Number/BigInt
// short-circuit before reaching this shim.
inline Tagged<Numeric> Builtin_NonNumberToNumeric(
    Isolate* isolate, Tagged<Context> context,
    Tagged<JSAny> input) {
  USE(context);
  // No inner HandleScope — the outer JS-linkage adaptor frame
  // already provides one. An inner scope would invalidate the
  // returned Tagged on close.
  Handle<JSAny> input_handle(input, isolate);
  DirectHandle<Object> result;
  if (!Object::ToNumeric(isolate, input_handle).ToHandle(&result)) {
    UNREACHABLE();  // Symbol input → TypeError; catch_block deferred.
  }
  return Cast<Numeric>(*result);
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=56&c=1
Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/torque-internal.tq?l=423&c=1
Tagged<Union<Hole, JSMessageObject>> TqRuntimeGetAndResetPendingMessage_0();

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=57&c=10
Tagged<Smi> TqRuntimeConvert_Smi_constexpr_int31_0(int31_t p_i);

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=85&c=1
Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_int31_0(int31_t p_i);

Tagged<Smi> Builtin_TorqueCcTest_CatchBlock(Isolate* isolate, Tagged<Context> context, Tagged<Smi> shouldThrow) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = shouldThrow;
  USE(parameter1);
  Tagged<Smi> tmp0{}; USE(tmp0);
  Tagged<JSAny> tmp1{}; USE(tmp1);
  bool tmp2{}; USE(tmp2);
  Tagged<JSAny> tmp3{}; USE(tmp3);
  Tagged<Union<Hole, JSMessageObject>> tmp4{}; USE(tmp4);
  Tagged<Union<Hole, JSMessageObject>> tmp5{}; USE(tmp5);
  Tagged<Undefined> tmp6{}; USE(tmp6);
  Tagged<JSAny> tmp7{}; USE(tmp7);
  Tagged<Union<Hole, JSMessageObject>> tmp8{}; USE(tmp8);
  Tagged<Smi> tmp9{}; USE(tmp9);
  Tagged<JSAny> tmp10{}; USE(tmp10);
  Tagged<Union<Hole, JSMessageObject>> tmp11{}; USE(tmp11);
  Tagged<JSAny> phi_bb2_2{}; USE(phi_bb2_2);
  Tagged<Union<Hole, JSMessageObject>> phi_bb2_3{}; USE(phi_bb2_3);
  Tagged<Smi> tmp12{}; USE(tmp12);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral(false, 0x0ull));
  if (V8_UNLIKELY(Isolate::Current()->has_exception())) {
    tmp1 = UncheckedCast<JSAny>(Isolate::Current()->exception());
    Isolate::Current()->clear_internal_exception();
    goto block5;
  }
  tmp2 = TorqueRuntimeMacroShims::CodeStubAssembler::SmiNotEqual(parameter1, tmp0);
  if (V8_UNLIKELY(Isolate::Current()->has_exception())) {
    tmp3 = UncheckedCast<JSAny>(Isolate::Current()->exception());
    Isolate::Current()->clear_internal_exception();
    goto block6;
  }
  if (tmp2) {
    goto block3;
  } else {
    goto block4;
  }

  block5:
  tmp4 = TqRuntimeGetAndResetPendingMessage_0();
  phi_bb2_2 = tmp1;
  phi_bb2_3 = tmp4;
  goto block2;

  block6:
  tmp5 = TqRuntimeGetAndResetPendingMessage_0();
  phi_bb2_2 = tmp3;
  phi_bb2_3 = tmp5;
  goto block2;

  block3:
  tmp6 = Undefined_0();
  {
    Address __rt_args[] = { tmp6.ptr() };
    Runtime_ThrowCalledNonCallable(1, __rt_args, isolate);
  }
  if (V8_UNLIKELY(Isolate::Current()->has_exception())) {
    tmp7 = UncheckedCast<JSAny>(Isolate::Current()->exception());
    Isolate::Current()->clear_internal_exception();
    goto block7;
  }
  UNREACHABLE();

  block7:
  tmp8 = TqRuntimeGetAndResetPendingMessage_0();
  phi_bb2_2 = tmp7;
  phi_bb2_3 = tmp8;
  goto block2;

  block4:
  tmp9 = TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral(false, 0x2aull));
  if (V8_UNLIKELY(Isolate::Current()->has_exception())) {
    tmp10 = UncheckedCast<JSAny>(Isolate::Current()->exception());
    Isolate::Current()->clear_internal_exception();
    goto block8;
  }
  return tmp9;

  block8:
  tmp11 = TqRuntimeGetAndResetPendingMessage_0();
  phi_bb2_2 = tmp10;
  phi_bb2_3 = tmp11;
  goto block2;

  block2:
  tmp12 = TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral(true, 0x1ull));
  return tmp12;
}

#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=56&c=1
inline Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0(IntegerLiteral p_i) {
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = TqRuntimeConvert_Smi_constexpr_int31_0((TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprIntegerLiteralToInt31(p_i)));
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_IntegerLiteral_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeGetAndResetPendingMessage_0
#define V8_INTERNAL_DEFINED_TqRuntimeGetAndResetPendingMessage_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/torque-internal.tq?l=423&c=1
inline Tagged<Union<Hole, JSMessageObject>> TqRuntimeGetAndResetPendingMessage_0() {
  Tagged<Union<Hole, JSMessageObject>> tmp0{}; USE(tmp0);
  Tagged<Hole> tmp1{}; USE(tmp1);
  goto block0;

  block0:
  tmp0 = TorqueRuntimeMacroShims::CodeStubAssembler::GetPendingMessage();
  tmp1 = TheHole_0();
  TorqueRuntimeMacroShims::CodeStubAssembler::SetPendingMessage(tmp1);
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeGetAndResetPendingMessage_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeConvert_Smi_constexpr_int31_0
#define V8_INTERNAL_DEFINED_TqRuntimeConvert_Smi_constexpr_int31_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=57&c=10
inline Tagged<Smi> TqRuntimeConvert_Smi_constexpr_int31_0(int31_t p_i) {
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = TqRuntimeFromConstexpr_Smi_constexpr_int31_0(p_i);
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeConvert_Smi_constexpr_int31_0
#ifndef V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_int31_0
#define V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_int31_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/convert.tq?l=85&c=1
inline Tagged<Smi> TqRuntimeFromConstexpr_Smi_constexpr_int31_0(int31_t p_i) {
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = Smi::FromInt(CastToUnderlyingTypeIfEnum(p_i));
  goto block2;

  block2:
  return tmp0;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeFromConstexpr_Smi_constexpr_int31_0

}  // namespace v8::internal
