// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/js-return.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"

namespace v8::internal {

// Builtin: TorqueCcTest_JsReturn
Address Builtin_TorqueCcTest_JsReturn(int args_length, Address* args_object,
                         Isolate* isolate) {
  DCHECK(isolate->context().is_null() || IsContext(isolate->context()));
  BuiltinArguments args(args_length, args_object);
  HandleScope scope(isolate);
  USE(isolate);
  Tagged<NativeContext> parameter0 = Cast<NativeContext>(isolate->context());
  USE(parameter0);
  Tagged<NativeContext> context = parameter0;
  USE(context);
  Tagged<JSAny> parameter1 = Cast<JSAny>(args[1]);
  USE(parameter1);
  Tagged<JSAny> arg = parameter1;
  USE(arg);
  goto block0;

  block0:
  return parameter1.ptr();
}


}  // namespace v8::internal
