// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/make-lazy-node.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/handles/handles-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/smi.h"
#include "src/objects/tagged.h"

namespace v8::internal {

Tagged<Smi> Builtin_TorqueCcTest_MakeLazyNode(Isolate* isolate, Tagged<Context> context, Tagged<Smi> arg) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = arg;
  USE(parameter1);
  std::function<Tagged<Smi>()> tmp0;  USE(tmp0);
  goto block0;

  block0:
  tmp0 = [=]() { return TqRuntimeTorqueCcTest_LazyBody_0(parameter1); };
  return parameter1;
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/test/phase2-fixtures/make-lazy-node.tq?l=13&c=3
inline Tagged<Smi> TqRuntimeTorqueCcTest_LazyBody_0(Tagged<Smi> p_x) {
  goto block0;

  block0:
  goto block2;

  block2:
  return p_x;
}


}  // namespace v8::internal
