// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/make-lazy-node.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/execution/isolate-inl.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/roots/roots-inl.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"

namespace v8::internal {

// kCCBuiltins Phase 5 (revised) Task 5.8 — inline accessors for
// NamespaceConstants reachable from whitelisted builtins.
// Proper NamespaceConstant emission under kCCBuiltins is Phase 6
// groundwork; these hand-written inlines cover `const True` /
// `const False` from base.tq (torque-suffixed `_0`) so the
// ArrayIsArray fixture links. Phase 6.1 (I-1 follow-up) moved
// the `Isolate::Current()` lookup into the helper body — the
// emitter now emits `True_0()` / `False_0()` with no argument,
// so the same helper works from the outer builtin body and from
// nested TqRuntime* helper bodies without an `isolate` token
// needing to be in scope at the call site.
inline Tagged<True> True_0() {
  return Cast<True>(ReadOnlyRoots(Isolate::Current()).true_value());
}
inline Tagged<False> False_0() {
  return Cast<False>(
      ReadOnlyRoots(Isolate::Current()).false_value());
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/test/phase2-fixtures/make-lazy-node.tq?l=13&c=3
Tagged<Smi> TqRuntimeTorqueCcTest_LazyBody_0(Tagged<Smi> p_x);

Tagged<Smi> Builtin_TorqueCcTest_MakeLazyNode(Isolate* isolate, Tagged<Context> context, Tagged<Smi> arg) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = arg;
  USE(parameter1);
  std::function<Tagged<Smi>()> tmp0;  USE(tmp0);
  goto block0;

  block0:
  tmp0 = [=]() { return TqRuntimeTorqueCcTest_LazyBody_0(parameter1); };
  return parameter1;
}

#ifndef V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_LazyBody_0
#define V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_LazyBody_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/test/phase2-fixtures/make-lazy-node.tq?l=13&c=3
inline Tagged<Smi> TqRuntimeTorqueCcTest_LazyBody_0(Tagged<Smi> p_x) {
  goto block0;

  block0:
  goto block2;

  block2:
  return p_x;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_LazyBody_0

}  // namespace v8::internal
