// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/make-lazy-node.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/execution/isolate-inl.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/roots/roots-inl.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"
#include "torque-generated/cc-builtins-types.h"

namespace v8::internal {

// kCCBuiltins Phase 5 (revised) Task 5.8 — inline accessors for
// NamespaceConstants reachable from whitelisted builtins.
// Proper NamespaceConstant emission under kCCBuiltins is Phase 6
// groundwork; these hand-written inlines cover `const True` /
// `const False` from base.tq (torque-suffixed `_0`) so the
// ArrayIsArray fixture links. Phase 6.1 (I-1 follow-up) moved
// the `Isolate::Current()` lookup into the helper body — the
// emitter now emits `True_0()` / `False_0()` with no argument,
// so the same helper works from the outer builtin body and from
// nested TqRuntime* helper bodies without an `isolate` token
// needing to be in scope at the call site.
inline Tagged<True> True_0() {
  return Cast<True>(ReadOnlyRoots(Isolate::Current()).true_value());
}
inline Tagged<False> False_0() {
  return Cast<False>(
      ReadOnlyRoots(Isolate::Current()).false_value());
}

// Phase 8 — NumberConstant lives here (not in runtime-macro-shims.h)
// because its body needs factory.h and conversions-inl.h, which
// pull descriptor-array-tq-inl.inc transitively when included from
// the shims header — that .inc forward-references
// TorqueRuntimeMacroShims::CodeStubAssembler before the namespace
// is opened, breaking compilation. Emitting in the per-TU
// preamble means each kCCBuiltins .cc resolves NumberConstant
// against its own already-included factory-inl.h /
// conversions-inl.h. Inside the proper torque-shim namespace so
// the emitter's qualified emission `TorqueRuntimeMacroShims::
// CodeStubAssembler::NumberConstant(...)` resolves cleanly.
namespace TorqueRuntimeMacroShims {
namespace CodeStubAssembler {
inline Tagged<Number> NumberConstant(double v) {
  int smi_value;
  if (DoubleToSmiInteger(v, &smi_value)) {
    return Cast<Number>(Smi::FromInt(smi_value));
  }
  Isolate* isolate = Isolate::Current();
  return Cast<Number>(*isolate->factory()->NewHeapNumber(v));
}
// Phase 9A — shims for the catch-flow lowering. Live here, not
// in runtime-macro-shims.h, because they need factory.h /
// isolate-inl.h which would re-enter the descriptor-array-tq-inl
// include chain (see NumberConstant rationale above).
// `StringConstant(const char*)` interns a C-string literal as a
// V8 String. `GetPendingMessage` / `SetPendingMessage` access
// the isolate's pending-message slot used by the catch-flow
// machinery in TqRuntimeGetAndResetPendingMessage_0.
inline Tagged<String> StringConstant(const char* s) {
  Isolate* isolate = Isolate::Current();
  return *isolate->factory()->InternalizeUtf8String(s);
}
inline Tagged<Union<Hole, JSMessageObject>> GetPendingMessage() {
  return UncheckedCast<Union<Hole, JSMessageObject>>(
      Isolate::Current()->pending_message());
}
inline void SetPendingMessage(Tagged<Hole> v) {
  Isolate::Current()->set_pending_message(v);
}
}  // namespace CodeStubAssembler
}  // namespace TorqueRuntimeMacroShims

// Phase 9A — `TheHole_0()` mirrors True_0/False_0: emitter spells
// the bare name with no `isolate` arg under kCCBuiltins, so we
// internally fetch via Isolate::Current(). Used by the catch-flow
// machinery to clear the pending-message slot.
inline Tagged<Hole> TheHole_0() {
  return Cast<Hole>(
      ReadOnlyRoots(Isolate::Current()).the_hole_value());
}
// Phase 9A — `Undefined_0()` mirrors True_0/False_0/TheHole_0:
// torque emits the bare `Undefined` namespace-constant as
// `Undefined_0()` under kCCBuiltins. Used by callers that
// pass `Undefined` as a JSAny argument (e.g. the catch-block
// fixture's `ThrowCalledNonCallable(Undefined)` site).
inline Tagged<Undefined> Undefined_0() {
  return Cast<Undefined>(
      ReadOnlyRoots(Isolate::Current()).undefined_value());
}

// Phase 8 — TFC builtin C bridges. `Add` and `NonNumberToNumeric`
// are TFC (Torque, Function, Custom-call-descriptor) builtins —
// CSA-emitted to native code at snapshot time, NO `Builtin_<Name>`
// C symbol exists in any v8 lib. The kCCBuiltins emitter spells
// `Builtin_<Callee>(Isolate::Current(), args...)` at call sites,
// so we provide inline C functions here that wrap V8's high-level
// APIs (Object::ToNumeric, direct Number+Number arithmetic). The
// inline'd definition lives in every kCCBuiltins .cc TU; the
// linker dedupes via vague linkage. catch_block is deferred (Phase
// 9+), so the rare Symbol-input branch of NonNumberToNumeric
// UNREACHABLEs instead of throwing TypeError.
//
// Phase 9.7 — Builtin_Add and Builtin_Subtract delegate to V8's
// canonical Object::NumberValue + factory->NewNumber(double) APIs
// rather than re-implementing JS-spec Smi/HeapNumber arithmetic.
// `factory->NewNumber(double)` (factory-base.h:119) does the
// Smi/HeapNumber discrimination spec-correctly — same fast path
// Object::Add takes for Number+Number (objects.cc:Add). For our
// `tail Add(n, 1)` / `tail Subtract(n, 1)` call sites, torque's
// type system already excluded String / BigInt / ToPrimitive
// shapes, so we only need the Number+Number branch.
//
// Why not Object::Add directly? It returns MaybeDirectHandle<Object>
// (handles string concat / ToPrimitive failure) — for our
// statically-typed Number+Number case the fail branch is
// unreachable, and the MaybeHandle ceremony (HandleScope, ToHandle
// dispatch) is more code than the direct delegation below. The
// `Object::NumberValue + factory->NewNumber` path is what
// Object::Add itself takes internally for the Number+Number arm.
//
// Object::Subtract has no equivalent static helper in V8 (Add gets
// special treatment because of string concat); the direct path
// here is the canonical V8-internal pattern for both.
inline Tagged<Number> Builtin_Add(Isolate* isolate,
                                  Tagged<Context> context,
                                  Tagged<Number> left,
                                  Tagged<Number> right) {
  USE(context);
  double sum = Object::NumberValue(left) + Object::NumberValue(right);
  return *isolate->factory()->NewNumber(sum);
}

inline Tagged<Number> Builtin_Subtract(Isolate* isolate,
                                       Tagged<Context> context,
                                       Tagged<Number> left,
                                       Tagged<Number> right) {
  USE(context);
  double diff = Object::NumberValue(left) - Object::NumberValue(right);
  return *isolate->factory()->NewNumber(diff);
}

// `Builtin_NonNumberToNumeric` wraps Object::ToNumeric, which
// implements ECMAScript ToNumeric (string parse, boolean→Smi,
// null/undefined coercion, ToPrimitive recurse). Symbol inputs
// throw TypeError under spec — we UNREACHABLE because the
// kCCBuiltins emitter has no exception path yet (Phase 9+).
// Call sites in kCCBuiltins emission (UnaryOp1's JSAnyNotNumeric
// arm) only feed JSAnyNotNumeric inputs here, so Number/BigInt
// short-circuit before reaching this shim.
inline Tagged<Numeric> Builtin_NonNumberToNumeric(
    Isolate* isolate, Tagged<Context> context,
    Tagged<JSAny> input) {
  USE(context);
  // No inner HandleScope — the outer JS-linkage adaptor frame
  // already provides one. An inner scope would invalidate the
  // returned Tagged on close.
  Handle<JSAny> input_handle(input, isolate);
  DirectHandle<Object> result;
  if (!Object::ToNumeric(isolate, input_handle).ToHandle(&result)) {
    UNREACHABLE();  // Symbol input → TypeError; catch_block deferred.
  }
  return Cast<Numeric>(*result);
}

// https://source.chromium.org/chromium/chromium/src/+/main:v8/test/phase2-fixtures/make-lazy-node.tq?l=13&c=3
Tagged<Smi> TqRuntimeTorqueCcTest_LazyBody_0(Tagged<Smi> p_x);

Tagged<Smi> Builtin_TorqueCcTest_MakeLazyNode(Isolate* isolate, Tagged<Context> context, Tagged<Smi> arg) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = arg;
  USE(parameter1);
  std::function<Tagged<Smi>()> tmp0;  USE(tmp0);
  goto block0;

  block0:
  tmp0 = [=]() { return TqRuntimeTorqueCcTest_LazyBody_0(parameter1); };
  return parameter1;
}

#ifndef V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_LazyBody_0
#define V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_LazyBody_0

// https://source.chromium.org/chromium/chromium/src/+/main:v8/test/phase2-fixtures/make-lazy-node.tq?l=13&c=3
inline Tagged<Smi> TqRuntimeTorqueCcTest_LazyBody_0(Tagged<Smi> p_x) {
  goto block0;

  block0:
  goto block2;

  block2:
  return p_x;
}

#endif // V8_INTERNAL_DEFINED_TqRuntimeTorqueCcTest_LazyBody_0

}  // namespace v8::internal
