// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/namespace-constant.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/execution/isolate.h"
#include "src/objects/contexts.h"
#include "src/objects/smi.h"
#include "src/objects/tagged.h"

namespace v8::internal {

Tagged<Smi> Builtin_TorqueCcTest_NamespaceConstant(Isolate* isolate, Tagged<Context> context) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = kTorqueCcTestSmiZeroConstant_0(isolate);
  return tmp0;
}


}  // namespace v8::internal
