// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/push-uninitialized.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/builtins/builtins-utils-inl.h"
#include "src/execution/arguments-inl.h"
#include "src/execution/isolate.h"
#include "src/handles/handles-inl.h"
#include "src/objects/casting-inl.h"
#include "src/objects/contexts.h"
#include "src/objects/heap-object-inl.h"
#include "src/objects/instance-type.h"
#include "src/objects/js-array-inl.h"
#include "src/objects/js-proxy-inl.h"
#include "src/objects/map-inl.h"
#include "src/objects/oddball.h"
#include "src/objects/smi.h"
#include "src/objects/tagged-field-inl.h"
#include "src/objects/tagged.h"
#include "src/runtime/runtime.h"
#include "src/torque/runtime-macro-shims.h"
#include "src/torque/runtime-support.h"

namespace v8::internal {

Tagged<Smi> Builtin_TorqueCcTest_PushUninitialized(Isolate* isolate, Tagged<Context> context, Tagged<Smi> arg) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = arg;
  USE(parameter1);
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  return parameter1;
}


}  // namespace v8::internal
