// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/push-builtin-pointer.tq
// DO NOT EDIT.

namespace v8::internal {

Tagged<Smi> Builtin_TorqueCcTest_PushBuiltinPointer_Helper(Isolate* isolate, Tagged<Context> context, Tagged<Smi> x) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = x;
  USE(parameter1);
  goto block0;

  block0:
  return parameter1;
}

Tagged<Smi> Builtin_TorqueCcTest_PushBuiltinPointer(Isolate* isolate, Tagged<Context> context) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = Smi::FromInt(static_cast<int>(Builtin::kTorqueCcTest_PushBuiltinPointer_Helper));
  return tmp0;
}


}  // namespace v8::internal
