// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/return.tq
// DO NOT EDIT.

#include "src/base/macros.h"
#include "src/execution/isolate.h"
#include "src/objects/contexts.h"
#include "src/objects/smi.h"
#include "src/objects/tagged.h"

namespace v8::internal {

Tagged<Smi> Builtin_TorqueCcTest_Return(Isolate* isolate, Tagged<Context> context, Tagged<Smi> arg) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<Smi> parameter1 = arg;
  USE(parameter1);
  goto block0;

  block0:
  return parameter1;
}


}  // namespace v8::internal
