// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/store-reference.tq
// DO NOT EDIT.

namespace v8::internal {

Tagged<Smi> Builtin_TorqueCcTest_StoreReference(Isolate* isolate, Tagged<Context> context, Tagged<HeapObject> obj, intptr_t offset, Tagged<Smi> v) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  Tagged<HeapObject> parameter1 = obj;
  USE(parameter1);
  intptr_t parameter2 = offset;
  USE(parameter2);
  Tagged<Smi> parameter3 = v;
  USE(parameter3);
  Tagged<Union<HeapObject, TaggedIndex>> tmp0{}; USE(tmp0);
  intptr_t tmp1{}; USE(tmp1);
  goto block0;

  block0:
  std::tie(tmp0, tmp1) = (std::make_tuple(parameter1, parameter2));
  TaggedField<Tagged<Smi>>::store(UncheckedCast<HeapObject>(tmp0), static_cast<int>(tmp1), parameter3);
  return parameter3;
}


}  // namespace v8::internal
