// Copyright 2024 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED by torque CC-Builtins backend (Phase 1 scaffolding).
// Source: test/phase2-fixtures/store-bit-field.tq
// DO NOT EDIT.

namespace v8::internal {

uint32_t Builtin_TorqueCcTest_StoreBitField(Isolate* isolate, Tagged<Context> context, uint32_t bf, int32_t v) {
  USE(isolate);
  Tagged<Context> parameter0 = context;
  USE(parameter0);
  uint32_t parameter1 = bf;
  USE(parameter1);
  int32_t parameter2 = v;
  USE(parameter2);
  uint32_t tmp0{}; USE(tmp0);
  goto block0;

  block0:
  tmp0 = static_cast<uint32_t>(base::BitField<int32_t, 0, 8, uint32_t>::update(parameter1, parameter2));
  return tmp0;
}


}  // namespace v8::internal
