#!/usr/bin/env bash
set -euo pipefail

# Build gencat(1) from chimerautils for wasm32-posix-kernel.
#
# chimerautils is a meson project, but its top-level meson.build requires
# libacl and libxo for utilities Kandelo does not take from it, and meson is
# not part of the dev shell. gencat itself is one translation unit: upstream
# builds it as `executable('gencat', ['gencat.c'], include_directories: [inc])`
# (src.freebsd/gencat/meson.build), where `inc` is chimerautils' include/
# directory plus the generated config-compat.h. This script reproduces that
# one rule with the same project-wide compile arguments.
#
# Output: $KANDELO_PACKAGE_WORK_DIR/bin/gencat.wasm

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
# shellcheck source=/dev/null
source "$REPO_ROOT/scripts/package-build-roots.sh"
kandelo_package_prepare_build_roots "$SCRIPT_DIR" wasm32
WORK_DIR="$KANDELO_PACKAGE_WORK_DIR"
SRC_DIR="$WORK_DIR/chimerautils-src"
BIN_DIR="$WORK_DIR/bin"
GEN_DIR="$WORK_DIR/generated"
SYSROOT="$REPO_ROOT/sysroot"
CHIMERAUTILS_VERSION="${WASM_POSIX_DEP_VERSION:-${CHIMERAUTILS_VERSION:-15.1.1}}"
SOURCE_URL="${WASM_POSIX_DEP_SOURCE_URL:-https://github.com/chimera-linux/chimerautils/archive/refs/tags/v${CHIMERAUTILS_VERSION}.tar.gz}"
SOURCE_SHA256="${WASM_POSIX_DEP_SOURCE_SHA256:-18c558f0165af078a1a213617c2241d80164dc846ffb05c49f22a476720df773}"
VERIFIED_SOURCE_DIR="${WASM_POSIX_DEP_SOURCE_DIR:-}"
SOURCE_MARKER="$SRC_DIR/.kandelo-chimerautils-source"

# A resolver/Formula caller owns the declared work and output roots. Keep the
# reviewed checkout read-only and suppress the developer-only local mirror.
if [ -n "${WASM_POSIX_DEP_WORK_DIR:-}" ] && [ -n "${WASM_POSIX_DEP_OUT_DIR:-}" ]; then
    export WASM_POSIX_INSTALL_LOCAL_MIRROR=0
    export WASM_POSIX_INSTALL_FORK_INSTRUMENTATION=disabled
fi

# Keep direct and resolver-driven builds pinned to this worktree's SDK.
# shellcheck source=/dev/null
source "$REPO_ROOT/sdk/activate.sh"

if ! command -v wasm32posix-cc &>/dev/null; then
    echo "ERROR: wasm32posix-cc not found. Run through scripts/dev-shell.sh." >&2
    exit 1
fi

if [ ! -f "$SYSROOT/lib/libc.a" ]; then
    echo "ERROR: sysroot not found. Run: bash build.sh && bash scripts/build-musl.sh" >&2
    exit 1
fi

export WASM_POSIX_SYSROOT="$SYSROOT"

# --- Stage verified chimerautils source ---
expected_source_marker="$(printf '%s\n%s\n%s' \
    "$CHIMERAUTILS_VERSION" "$SOURCE_URL" "$SOURCE_SHA256")"
if [ -d "$SRC_DIR" ] && \
   [ "$(cat "$SOURCE_MARKER" 2>/dev/null || true)" != "$expected_source_marker" ]; then
    rm -rf "$SRC_DIR" "$BIN_DIR" "$GEN_DIR"
fi
if [ ! -d "$SRC_DIR" ]; then
    echo "==> Staging verified chimerautils $CHIMERAUTILS_VERSION source..."
    kandelo_package_stage_verified_source chimerautils "$SRC_DIR" \
        "$VERIFIED_SOURCE_DIR" "$SOURCE_URL" "$SOURCE_SHA256" "$WORK_DIR"
    printf '%s\n' "$expected_source_marker" >"$SOURCE_MARKER"
fi

# --- Generate config-compat.h (include/meson.build) ---
# Upstream answers each HAVE_* with meson's cc.has_function(), a link probe.
# The SDK links with --allow-undefined, so a link probe would succeed for
# every name. Answer from the symbols the sysroot's libc.a actually defines.
libc_defines() {
    wasm32posix-nm "$SYSROOT/lib/libc.a" 2>/dev/null |
        awk -v sym="$1" '$2 ~ /^[TW]$/ && $3 == sym { found = 1 } END { exit !found }'
}

mkdir -p "$GEN_DIR"
{
    printf '/* Generated by build-gencat.sh from %s */\n' "$SYSROOT/lib/libc.a"
    printf '#define PROJECT_NAME "chimerautils"\n'
    printf '#define PROJECT_VERSION "%s"\n' "$CHIMERAUTILS_VERSION"
    printf '#define LIBEXECDIR "/usr/libexec"\n'
    for fn in strtoq strlcpy strlcat strtonum reallocf errc warnc fts_open rpmatch; do
        macro="HAVE_$(printf '%s' "$fn" | tr '[:lower:]' '[:upper:]')"
        if libc_defines "$fn"; then
            printf '#define %s 1\n' "$macro"
        else
            printf '#undef %s\n' "$macro"
        fi
    done
    # PAM is not part of the Kandelo sysroot.
    printf '#undef HAVE_PAM_MISC\n'
} >"$GEN_DIR/config-compat.h.tmp"
mv "$GEN_DIR/config-compat.h.tmp" "$GEN_DIR/config-compat.h"
echo "==> config-compat.h:"
sed 's/^/    /' "$GEN_DIR/config-compat.h"

# --- Build ---
# Project-wide arguments from chimerautils' top-level meson.build: c99,
# _GNU_SOURCE, 64-bit file offsets, _CHIMERAUTILS_BUILD (lets public compat
# headers include config-compat.h), and -Dlint (drops unused RCS metadata).
echo "==> Building gencat..."
mkdir -p "$BIN_DIR"
wasm32posix-cc \
    -std=c99 \
    -O2 \
    -D_GNU_SOURCE \
    -D_FILE_OFFSET_BITS=64 \
    -D_CHIMERAUTILS_BUILD \
    -Dlint \
    -I"$GEN_DIR" \
    -I"$SRC_DIR/include" \
    "$SRC_DIR/src.freebsd/gencat/gencat.c" \
    -o "$BIN_DIR/gencat.wasm"

ls -lh "$BIN_DIR/gencat.wasm"
echo "==> gencat built successfully."

source "$REPO_ROOT/scripts/install-local-binary.sh"
install_local_binary gencat "$BIN_DIR/gencat.wasm"
