use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use tempfile::TempDir;

struct SourceFixture {
    _temp: TempDir,
    root: PathBuf,
}

fn write(root: &Path, relative: &str, contents: &str) {
    let path = root.join(relative);
    fs::create_dir_all(path.parent().expect("fixture file has a parent")).unwrap();
    fs::write(path, contents).unwrap();
}

fn compiled_repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("xtask remains below the repository root")
        .to_path_buf()
}

fn source_fixture() -> SourceFixture {
    let temp = tempfile::tempdir().unwrap();
    let root = fs::canonicalize(temp.path()).unwrap();
    let rust_toolchain = fs::read_to_string(compiled_repo_root().join("rust-toolchain.toml"))
        .expect("read the repository toolchain declaration");

    write(
        &root,
        "Cargo.toml",
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/fork-instrument\"]\n",
    );
    write(
        &root,
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"fork-instrument\"\nversion = \"0.1.0\"\n",
    );
    write(&root, "package.json", "{}\n");
    write(&root, "rust-toolchain.toml", &rust_toolchain);
    write(&root, "flake.nix", "fixture flake\n");
    write(&root, "flake.lock", "fixture lock\n");
    write(
        &root,
        "tools/xtask/Cargo.toml",
        "[package]\nname = \"fixture-xtask\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    );
    for path in [
        "scripts/dev-shell.sh",
        "scripts/build-musl.sh",
        "scripts/install-overlay-headers.sh",
        "scripts/build-fork-instrument-tool.sh",
        "scripts/run-wasm-fork-instrument.sh",
        "sdk/activate.sh",
        "sdk/config.site",
        "sdk/package.json",
        "sdk/package-lock.json",
    ] {
        write(&root, path, "fixture input\n");
    }
    for path in [
        ".github/actions/package-archive-build/input",
        ".github/actions/package-toolchain/input",
        ".github/actions/fetch-submodules/input",
        ".github/actions/download-run-artifacts/input",
        "libc/glue/input",
        "libc/musl-overlay/input",
        "libc/musl/input",
        "sdk/bin/input",
        "sdk/src/input",
        "host/src/input",
    ] {
        write(&root, path, "fixture input\n");
    }
    write(
        &root,
        "crates/fork-instrument/Cargo.toml",
        "[package]\nname = \"fork-instrument\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    );
    write(
        &root,
        "crates/fork-instrument/src/lib.rs",
        "pub fn fixture() {}\n",
    );

    write(
        &root,
        "packages/registry/demo/package.toml",
        r#"kind = "program"
name = "demo"
version = "1.0.0"
depends_on = []

[source]
url = "https://example.test/demo-1.0.0.tar.gz"
sha256 = "0000000000000000000000000000000000000000000000000000000000000000"

[license]
spdx = "MIT"

[[outputs]]
name = "demo"
wasm = "demo.wasm"
"#,
    );
    write(
        &root,
        "packages/registry/demo/build.toml",
        r#"script_path = "packages/registry/demo/build-demo.sh"
inputs = ["host/src"]
repo_url = "https://example.test/kandelo.git"
commit = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
revision = 1

[binary]
index_url = "https://example.test/binaries-abi-v{abi}/index.toml"
"#,
    );
    write(
        &root,
        "packages/registry/demo/build-demo.sh",
        "#!/usr/bin/env bash\nexit 0\n",
    );

    SourceFixture { _temp: temp, root }
}

fn relocated_xtask() -> (TempDir, PathBuf) {
    let temp = tempfile::tempdir().unwrap();
    let destination = temp.path().join("relocated-xtask");
    fs::copy(env!("CARGO_BIN_EXE_xtask"), &destination).unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(&destination).unwrap().permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(&destination, permissions).unwrap();
    }
    (temp, destination)
}

fn run_index(tool: &Path, root: &Path, output: &Path, explicit_root: bool) -> Output {
    let registry = root.join("packages/registry");
    let mut command = Command::new(tool);
    command.args(["build-deps", "program-index"]);
    if explicit_root {
        command.arg("--source-repo-root").arg(root);
    }
    command
        .arg(&registry)
        .arg(output)
        .current_dir(root.join("host"))
        .env(
            "WASM_POSIX_DEPS_REGISTRY",
            if explicit_root {
                Path::new("packages/registry")
            } else {
                registry.as_path()
            },
        )
        .output()
        .expect("run relocated xtask program-index")
}

fn generate(tool: &Path, root: &Path, name: &str) -> Vec<u8> {
    let output = root.join("packages/registry").join(name);
    let result = run_index(tool, root, &output, true);
    assert!(
        result.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&result.stderr)
    );
    fs::read(output).unwrap()
}

fn check(tool: &Path, root: &Path, name: &str) {
    let registry = root.join("packages/registry");
    let result = Command::new(tool)
        .args(["build-deps", "program-index-check"])
        .arg("--source-repo-root")
        .arg(root)
        .arg(&registry)
        .arg(registry.join(name))
        .current_dir(root)
        .env("WASM_POSIX_DEPS_REGISTRY", &registry)
        .output()
        .expect("run relocated xtask program-index-check");
    assert!(
        result.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&result.stderr)
    );
}

fn assert_relocated_without_root_is_rejected(
    tool: &Path,
    root: &Path,
    subcommand: &str,
    arguments: &[&Path],
) {
    let registry = root.join("packages/registry");
    let result = Command::new(tool)
        .arg("build-deps")
        .arg(subcommand)
        .args(arguments)
        .current_dir(root)
        .env("WASM_POSIX_DEPS_REGISTRY", &registry)
        .output()
        .expect("run relocated xtask without source authority");
    assert!(!result.status.success());
    let stderr = String::from_utf8_lossy(&result.stderr);
    assert!(
        stderr.contains("was compiled for") && stderr.contains("--source-repo-root"),
        "unexpected {subcommand} rejection: {stderr}"
    );
}

#[test]
fn relocated_xtask_requires_and_obeys_one_explicit_source_checkout() {
    let first = source_fixture();
    let second = source_fixture();
    let (_tool_temp, tool) = relocated_xtask();

    let registry = second.root.join("packages/registry");
    let rejected_output = registry.join("rejected.json");
    assert_relocated_without_root_is_rejected(
        &tool,
        &second.root,
        "program-index",
        &[&registry, &rejected_output],
    );
    assert_relocated_without_root_is_rejected(
        &tool,
        &second.root,
        "program-index-check",
        &[&registry, &rejected_output],
    );
    assert_relocated_without_root_is_rejected(&tool, &second.root, "check", &[]);
    assert!(!rejected_output.exists());

    let first_bytes = generate(&tool, &first.root, "program-packages.json");
    let second_bytes = generate(&tool, &second.root, "program-packages.json");
    assert_eq!(
        first_bytes, second_bytes,
        "byte-identical checkouts must not inherit the xtask compile path"
    );
    check(&tool, &first.root, "program-packages.json");
    check(&tool, &second.root, "program-packages.json");

    let repeated = generate(&tool, &second.root, "program-packages.json");
    assert_eq!(second_bytes, repeated, "a second generation must be clean");

    let external_output = _tool_temp.path().join("external-registry.json");
    let external_registry = second.root.join("packages/registry");
    let external = Command::new(&tool)
        .args(["build-deps", "program-index"])
        .arg("--source-repo-root")
        .arg(&first.root)
        .arg(&external_registry)
        .arg(&external_output)
        .current_dir(first.root.join("host"))
        .env("WASM_POSIX_DEPS_REGISTRY", &external_registry)
        .output()
        .expect("generate an external registry with first-party authority");
    assert!(
        external.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&external.stderr)
    );
    assert_eq!(
        first_bytes,
        fs::read(external_output).unwrap(),
        "an absolute external registry must retain the selected source root"
    );

    write(&second.root, "host/src/input", "changed declared input\n");
    let declared = generate(&tool, &second.root, "declared.json");
    assert_ne!(second_bytes, declared, "repo-relative input was not bound");
    write(&second.root, "host/src/input", "fixture input\n");

    write(&second.root, "sdk/config.site", "changed global input\n");
    let global = generate(&tool, &second.root, "global.json");
    assert_ne!(second_bytes, global, "global toolchain input was not bound");
    write(&second.root, "sdk/config.site", "fixture input\n");

    write(
        &second.root,
        "crates/fork-instrument/src/lib.rs",
        "pub fn changed_fixture() {}\n",
    );
    let fork = generate(&tool, &second.root, "fork.json");
    assert_ne!(second_bytes, fork, "fork tool input was not bound");

    write(
        &second.root,
        "crates/fork-instrument/src/lib.rs",
        "pub fn fixture() {}\n",
    );
    let restored = generate(&tool, &second.root, "restored.json");
    assert_eq!(
        second_bytes, restored,
        "restored source bytes changed identity"
    );
}

#[test]
fn same_checkout_implicit_and_explicit_generation_are_byte_identical() {
    let root = fs::canonicalize(compiled_repo_root()).unwrap();
    let registry = root.join("packages/registry");
    let output_root = tempfile::tempdir().unwrap();
    let implicit_path = output_root.path().join("implicit.json");
    let explicit_path = output_root.path().join("explicit.json");
    let tool = Path::new(env!("CARGO_BIN_EXE_xtask"));

    let implicit = run_index(tool, &root, &implicit_path, false);
    assert!(
        implicit.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&implicit.stderr)
    );
    let explicit = run_index(tool, &root, &explicit_path, true);
    assert!(
        explicit.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&explicit.stderr)
    );

    let implicit_bytes = fs::read(implicit_path).unwrap();
    let explicit_bytes = fs::read(explicit_path).unwrap();
    assert_eq!(implicit_bytes, explicit_bytes);
    assert_eq!(
        explicit_bytes,
        fs::read(registry.join("program-packages.json")).unwrap(),
        "the explicit current-source generation must match committed policy"
    );
}
