/*
 * ffi_core.c — classification, marshalling and closure-pool
 * bookkeeping of the full libffi port. The combinatorial halves
 * (the ffi_call signature switch and the trampoline pool) are
 * generated by gen-dispatch.sh; ffi_internal.h is the contract.
 *
 * wasm32 C ABI facts this file encodes (verified against clang's
 * lowering — see docs/architecture.md):
 *
 *   - A struct whose only member (recursively) is one scalar lowers to
 *     that scalar, as argument and as return.
 *   - Every other by-value struct argument is passed as a pointer to a
 *     caller-owned copy (byval). The callee may WRITE its copy, so
 *     ffi_call passes a scratch copy, never the caller's buffer.
 *   - Every other struct return is a hidden leading pointer argument
 *     (sret) with a void wasm-level return.
 *   - i8/i16 arguments and returns travel as i32, extended per
 *     signedness by the producing side.
 *
 * The same source compiles for the native test leg; pointers classify
 * by word size so scalar signatures stay ABI-correct there.
 */
#include "ffi_internal.h"

#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define DEF_TYPE(sym, sz, al, tag) \
    ffi_type sym = { (sz), (al), (tag), NULL }

DEF_TYPE(ffi_type_void,    1, 1, FFI_TYPE_VOID);
DEF_TYPE(ffi_type_uint8,   1, 1, FFI_TYPE_UINT8);
DEF_TYPE(ffi_type_sint8,   1, 1, FFI_TYPE_SINT8);
DEF_TYPE(ffi_type_uint16,  2, 2, FFI_TYPE_UINT16);
DEF_TYPE(ffi_type_sint16,  2, 2, FFI_TYPE_SINT16);
DEF_TYPE(ffi_type_uint32,  4, 4, FFI_TYPE_UINT32);
DEF_TYPE(ffi_type_sint32,  4, 4, FFI_TYPE_SINT32);
DEF_TYPE(ffi_type_uint64,  8, 8, FFI_TYPE_UINT64);
DEF_TYPE(ffi_type_sint64,  8, 8, FFI_TYPE_SINT64);
DEF_TYPE(ffi_type_uint,    4, 4, FFI_TYPE_UINT32);
DEF_TYPE(ffi_type_sint,    4, 4, FFI_TYPE_SINT32);
DEF_TYPE(ffi_type_ulong,   sizeof(long), sizeof(long),
         sizeof(long) == 4 ? FFI_TYPE_UINT32 : FFI_TYPE_UINT64);
DEF_TYPE(ffi_type_slong,   sizeof(long), sizeof(long),
         sizeof(long) == 4 ? FFI_TYPE_SINT32 : FFI_TYPE_SINT64);
DEF_TYPE(ffi_type_float,   4, 4, FFI_TYPE_FLOAT);
DEF_TYPE(ffi_type_double,  8, 8, FFI_TYPE_DOUBLE);
DEF_TYPE(ffi_type_pointer, sizeof(void *), sizeof(void *),
         FFI_TYPE_POINTER);

#undef DEF_TYPE

#define PTR_CLS (sizeof(void *) == 4 ? FFI_CLS_I32 : FFI_CLS_I64)

/* the scalar a struct collapses to, or NULL if it stays aggregate */
static ffi_type *singleton_of(ffi_type *t)
{
    while (t->type == FFI_TYPE_STRUCT) {
        if (t->elements == NULL || t->elements[0] == NULL ||
            t->elements[1] != NULL)
            return NULL;
        t = t->elements[0];
    }
    return t;
}

static int class_of_scalar(const ffi_type *t)
{
    switch (t->type) {
    case FFI_TYPE_INT:
    case FFI_TYPE_SINT32:
    case FFI_TYPE_UINT32:
    case FFI_TYPE_SINT16:
    case FFI_TYPE_UINT16:
    case FFI_TYPE_SINT8:
    case FFI_TYPE_UINT8:
        return FFI_CLS_I32;
    case FFI_TYPE_POINTER:
        return PTR_CLS;
    case FFI_TYPE_SINT64:
    case FFI_TYPE_UINT64:
        return FFI_CLS_I64;
    case FFI_TYPE_FLOAT:
        return FFI_CLS_F32;
    case FFI_TYPE_DOUBLE:
        return FFI_CLS_F64;
    default:
        return -1;
    }
}

static int arg_class(ffi_type *t)
{
    if (t->type == FFI_TYPE_STRUCT) {
        ffi_type *s = singleton_of(t);
        return s ? class_of_scalar(s) : PTR_CLS;
    }
    return class_of_scalar(t);
}

/* return class; *sret set when the value travels via a hidden leading
 * pointer argument instead */
static int ret_class(ffi_type *t, int *sret)
{
    *sret = 0;
    if (t->type == FFI_TYPE_VOID)
        return FFI_RET_VOID;
    if (t->type == FFI_TYPE_STRUCT) {
        ffi_type *s = singleton_of(t);
        if (s == NULL) {
            *sret = 1;
            return FFI_RET_VOID;
        }
        t = s;
    }
    switch (class_of_scalar(t)) {
    case FFI_CLS_I32: return FFI_RET_I32;
    case FFI_CLS_I64: return FFI_RET_I64;
    case FFI_CLS_F32: return FFI_RET_F32;
    case FFI_CLS_F64: return FFI_RET_F64;
    default: return -1;
    }
}

static ffi_status aggregate_layout(ffi_type *t)
{
    if (t->type != FFI_TYPE_STRUCT)
        return FFI_OK;
    if (t->elements == NULL || t->elements[0] == NULL)
        return FFI_BAD_TYPEDEF;

    size_t off = 0;
    size_t align = 1;
    for (ffi_type **e = t->elements; *e != NULL; e++) {
        if (aggregate_layout(*e) != FFI_OK)
            return FFI_BAD_TYPEDEF;
        size_t a = (*e)->alignment;
        off = (off + a - 1) & ~(a - 1);
        off += (*e)->size;
        if (a > align)
            align = a;
    }
    t->size = (off + align - 1) & ~(align - 1);
    t->alignment = (unsigned short) align;
    return FFI_OK;
}

/* the signature key both generated halves are enumerated over */
static uint64_t cif_key(const ffi_cif *cif, int *sret)
{
    int rc = ret_class(cif->rtype, sret);
    unsigned base = *sret ? 1u : 0u;
    uint64_t key = (uint64_t) rc |
                   ((uint64_t) (cif->nargs + base) << 3);
    if (*sret)
        key |= (uint64_t) PTR_CLS << 8;
    for (unsigned i = 0; i < cif->nargs; i++)
        key |= (uint64_t) arg_class(cif->arg_types[i])
               << (8 + 2 * (base + i));
    return key;
}

ffi_status ffi_prep_cif(ffi_cif *cif, ffi_abi abi, unsigned int nargs,
                        ffi_type *rtype, ffi_type **atypes)
{
    if (cif == NULL || rtype == NULL)
        return FFI_BAD_TYPEDEF;
    if (nargs > 0 && atypes == NULL)
        return FFI_BAD_TYPEDEF;

    int sret = 0;
    if (aggregate_layout(rtype) != FFI_OK)
        return FFI_BAD_TYPEDEF;
    if (ret_class(rtype, &sret) < 0)
        return FFI_BAD_TYPEDEF;
    if (nargs + (sret ? 1u : 0u) > FFI_MAX_ARGS)
        return FFI_BAD_ARGTYPE;

    for (unsigned i = 0; i < nargs; i++) {
        ffi_type *t = atypes[i];
        if (t == NULL || t->type == FFI_TYPE_VOID)
            return FFI_BAD_TYPEDEF;
        if (aggregate_layout(t) != FFI_OK)
            return FFI_BAD_TYPEDEF;
        if (arg_class(t) < 0)
            return FFI_BAD_ARGTYPE;
    }

    cif->abi = abi;
    cif->nargs = nargs;
    cif->rtype = rtype;
    cif->arg_types = atypes;
    return FFI_OK;
}

ffi_status ffi_prep_cif_var(ffi_cif *cif, ffi_abi abi,
                            unsigned int nfixedargs, unsigned int ntotalargs,
                            ffi_type *rtype, ffi_type **atypes)
{
    (void) nfixedargs;
    return ffi_prep_cif(cif, abi, ntotalargs, rtype, atypes);
}

/* load one classified argument value into its dispatch word */
static void load_arg(ffi_type *t, void *value, union ffi_word *w)
{
    if (t->type == FFI_TYPE_STRUCT)
        t = singleton_of(t); /* aggregates were copied by the caller */

    switch (t->type) {
    case FFI_TYPE_SINT8:
        w->w_i32 = (uint32_t) (int32_t) *(int8_t *) value;
        break;
    case FFI_TYPE_UINT8:
        w->w_i32 = *(uint8_t *) value;
        break;
    case FFI_TYPE_SINT16:
        w->w_i32 = (uint32_t) (int32_t) *(int16_t *) value;
        break;
    case FFI_TYPE_UINT16:
        w->w_i32 = *(uint16_t *) value;
        break;
    case FFI_TYPE_INT:
    case FFI_TYPE_SINT32:
    case FFI_TYPE_UINT32:
        w->w_i32 = *(uint32_t *) value;
        break;
    case FFI_TYPE_POINTER:
        w->w_ptr = *(uintptr_t *) value;
        break;
    case FFI_TYPE_SINT64:
    case FFI_TYPE_UINT64:
        w->w_i64 = *(uint64_t *) value;
        break;
    case FFI_TYPE_FLOAT:
        w->w_f32 = *(float *) value;
        break;
    case FFI_TYPE_DOUBLE:
        w->w_f64 = *(double *) value;
        break;
    default:
        break;
    }
}

void ffi_call(ffi_cif *cif, void (*fn)(void), void *rvalue, void **avalue)
{
    union ffi_word a[FFI_MAX_ARGS];
    union ffi_word r;
    unsigned char stack_scratch[128];
    unsigned char *scratch = stack_scratch;
    unsigned char *heap = NULL;
    size_t scratch_need = 0;
    int sret = 0;
    uint64_t key = cif_key(cif, &sret);
    unsigned base = sret ? 1u : 0u;

    for (unsigned i = 0; i < cif->nargs; i++) {
        ffi_type *t = cif->arg_types[i];
        if (t->type == FFI_TYPE_STRUCT && singleton_of(t) == NULL)
            scratch_need += (t->size + 7u) & ~(size_t) 7u;
    }
    if (scratch_need > sizeof(stack_scratch))
        scratch = heap = malloc(scratch_need);
    if (scratch == NULL)
        abort();

    if (sret)
        a[0].w_ptr = (uintptr_t) rvalue;

    size_t off = 0;
    for (unsigned i = 0; i < cif->nargs; i++) {
        ffi_type *t = cif->arg_types[i];
        if (t->type == FFI_TYPE_STRUCT && singleton_of(t) == NULL) {
            memcpy(scratch + off, avalue[i], t->size);
            a[base + i].w_ptr = (uintptr_t) (scratch + off);
            off += (t->size + 7u) & ~(size_t) 7u;
        } else {
            load_arg(t, avalue[i], &a[base + i]);
        }
    }

    if (ffi_wasm_dispatch_call(key, fn, a, &r) != 0) {
        fprintf(stderr,
                "libffi: signature key=%llu is outside the generated "
                "dispatch — extend a family bound in "
                "packages/registry/libffi/gen-dispatch.sh\n",
                (unsigned long long) key);
        abort();
    }
    free(heap);

    if (rvalue == NULL || sret)
        return;

    ffi_type *rt = cif->rtype;
    if (rt->type == FFI_TYPE_STRUCT)
        rt = singleton_of(rt); /* sret handled above */

    switch (rt->type) {
    case FFI_TYPE_VOID:
        break;
    case FFI_TYPE_SINT8:
        *(ffi_arg *) rvalue = (ffi_arg) (ffi_sarg) (int8_t) r.w_i32;
        break;
    case FFI_TYPE_UINT8:
        *(ffi_arg *) rvalue = (ffi_arg) (uint8_t) r.w_i32;
        break;
    case FFI_TYPE_SINT16:
        *(ffi_arg *) rvalue = (ffi_arg) (ffi_sarg) (int16_t) r.w_i32;
        break;
    case FFI_TYPE_UINT16:
        *(ffi_arg *) rvalue = (ffi_arg) (uint16_t) r.w_i32;
        break;
    case FFI_TYPE_INT:
    case FFI_TYPE_SINT32:
        *(ffi_arg *) rvalue = (ffi_arg) (ffi_sarg) (int32_t) r.w_i32;
        break;
    case FFI_TYPE_UINT32:
        *(ffi_arg *) rvalue = (ffi_arg) r.w_i32;
        break;
    case FFI_TYPE_POINTER:
        *(uintptr_t *) rvalue = r.w_ptr;
        break;
    case FFI_TYPE_SINT64:
    case FFI_TYPE_UINT64:
        *(uint64_t *) rvalue = r.w_i64;
        break;
    case FFI_TYPE_FLOAT:
        *(float *) rvalue = r.w_f32;
        break;
    case FFI_TYPE_DOUBLE:
        *(double *) rvalue = r.w_f64;
        break;
    default:
        break;
    }
}

/* ---- closures ---- */

static pthread_mutex_t pool_lock = PTHREAD_MUTEX_INITIALIZER;

void *ffi_closure_alloc(size_t size, void **code)
{
    if (size < sizeof(ffi_closure))
        return NULL;

    ffi_closure *cl = calloc(1, size);
    if (cl == NULL)
        return NULL;
    cl->slot = -1;
    cl->code_out = code;
    if (code != NULL)
        *code = cl; /* provisional; prep rebinds once the class is known */
    return cl;
}

ffi_status ffi_prep_closure_loc(ffi_closure *closure, ffi_cif *cif,
                                void (*fun)(ffi_cif *, void *, void **,
                                            void *),
                                void *user_data, void *codeloc)
{
    (void) codeloc;
    if (closure == NULL || cif == NULL || fun == NULL)
        return FFI_BAD_TYPEDEF;

    int sret = 0;
    uint64_t key = cif_key(cif, &sret);

    const struct ffi_closure_class *cls = NULL;
    for (uint32_t i = 0; i < ffi_closure_class_count; i++) {
        if (ffi_closure_classes[i].key == key) {
            cls = &ffi_closure_classes[i];
            break;
        }
    }
    if (cls == NULL) {
        fprintf(stderr,
                "libffi: closure signature key=%llu has no trampoline "
                "class — extend a family bound in "
                "packages/registry/libffi/gen-dispatch.sh\n",
                (unsigned long long) key);
        return FFI_BAD_ARGTYPE;
    }

    pthread_mutex_lock(&pool_lock);
    int32_t slot = -1;
    for (uint32_t i = 0; i < cls->count; i++) {
        if (ffi_closure_slot_owner[cls->base + i] == NULL) {
            slot = (int32_t) (cls->base + i);
            ffi_closure_slot_owner[slot] = closure;
            break;
        }
    }
    pthread_mutex_unlock(&pool_lock);

    if (slot < 0) {
        fprintf(stderr,
                "libffi: closure trampoline pool exhausted for signature "
                "key=%llu (%u slots) — raise its slot count in "
                "packages/registry/libffi/gen-dispatch.sh\n",
                (unsigned long long) key, cls->count);
        abort();
    }

    closure->slot = slot;
    closure->cif = cif;
    closure->fun = fun;
    closure->user_data = user_data;
    closure->tramp = cls->tramps[(uint32_t) slot - cls->base];
    if (closure->code_out != NULL)
        *closure->code_out = closure->tramp;
    return FFI_OK;
}

void ffi_closure_free(void *p)
{
    ffi_closure *cl = p;
    if (cl == NULL)
        return;
    if (cl->slot >= 0) {
        pthread_mutex_lock(&pool_lock);
        ffi_closure_slot_owner[cl->slot] = NULL;
        pthread_mutex_unlock(&pool_lock);
    }
    free(cl);
}

void ffi_wasm_closure_invoke(uint32_t slot, union ffi_word *argv,
                             union ffi_word *ret)
{
    ffi_closure *cl;

    pthread_mutex_lock(&pool_lock);
    cl = (slot < ffi_closure_slot_count) ? ffi_closure_slot_owner[slot]
                                         : NULL;
    pthread_mutex_unlock(&pool_lock);
    if (cl == NULL) {
        fprintf(stderr,
                "libffi: closure trampoline fired on free slot %u\n",
                slot);
        abort();
    }

    ffi_cif *cif = cl->cif;
    int sret = 0;
    (void) ret_class(cif->rtype, &sret);
    unsigned base = sret ? 1u : 0u;

    union {
        ffi_arg a;
        uint64_t u64;
        float f;
        double d;
    } rbuf;
    void *rptr = sret ? (void *) argv[0].w_ptr : (void *) &rbuf;

    void *avalue[FFI_MAX_ARGS];
    for (unsigned i = 0; i < cif->nargs; i++) {
        ffi_type *t = cif->arg_types[i];
        if (t->type == FFI_TYPE_STRUCT && singleton_of(t) == NULL)
            avalue[i] = (void *) argv[base + i].w_ptr;
        else
            avalue[i] = &argv[base + i];
    }

    cl->fun(cif, rptr, avalue, cl->user_data);

    if (sret)
        return;

    ffi_type *rt = cif->rtype;
    if (rt->type == FFI_TYPE_STRUCT)
        rt = singleton_of(rt);

    switch (rt->type) {
    case FFI_TYPE_VOID:
        break;
    case FFI_TYPE_SINT8:
        ret->w_i32 = (uint32_t) (int32_t) (int8_t) rbuf.a;
        break;
    case FFI_TYPE_UINT8:
        ret->w_i32 = (uint8_t) rbuf.a;
        break;
    case FFI_TYPE_SINT16:
        ret->w_i32 = (uint32_t) (int32_t) (int16_t) rbuf.a;
        break;
    case FFI_TYPE_UINT16:
        ret->w_i32 = (uint16_t) rbuf.a;
        break;
    case FFI_TYPE_INT:
    case FFI_TYPE_SINT32:
    case FFI_TYPE_UINT32:
        ret->w_i32 = (uint32_t) rbuf.a;
        break;
    case FFI_TYPE_POINTER:
        ret->w_ptr = (uintptr_t) rbuf.a;
        break;
    case FFI_TYPE_SINT64:
    case FFI_TYPE_UINT64:
        ret->w_i64 = rbuf.u64;
        break;
    case FFI_TYPE_FLOAT:
        ret->w_f32 = rbuf.f;
        break;
    case FFI_TYPE_DOUBLE:
        ret->w_f64 = rbuf.d;
        break;
    default:
        break;
    }
}
