// `mkrootfs extract <image> <outDir>` — reverse of build. Writes every
// regular file's content to <outDir>/<path>, recreates directories, and
// emits a generated MANIFEST at <outDir>/MANIFEST that would rebuild the
// image (modulo lazy-archive content, which is not available at extract
// time — archive-backed files are written as empty stubs).
//
// Host-side uid/gid isn't preserved on disk (requires root); the MANIFEST
// is the source of truth for ownership metadata.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { MemoryFileSystem } from "../../../host/src/vfs/memory-fs";

const S_IFMT  = 0o170000;
const S_IFDIR = 0o040000;
const S_IFREG = 0o100000;
const S_IFLNK = 0o120000;

interface ManifestLine {
  kind: "node" | "archive";
  text: string;
}

export function extractImage(imagePath: string, outDir: string): string {
  const image = new Uint8Array(readFileSync(imagePath));
  const mfs = MemoryFileSystem.fromImage(image);

  mkdirSync(outDir, { recursive: true });
  const rootOut = join(outDir, "rootfs");
  mkdirSync(rootOut, { recursive: true });

  const lines: ManifestLine[] = [];
  walk(mfs, "/", rootOut, lines);

  const manifest = "# Generated by mkrootfs extract\n" +
    lines.map((l) => l.text).join("\n") + "\n";
  writeFileSync(join(outDir, "MANIFEST"), manifest);
  return manifest;
}

function walk(
  mfs: MemoryFileSystem,
  vfsPath: string,
  diskRoot: string,
  lines: ManifestLine[],
): void {
  const st = mfs.lstat(vfsPath);
  const mode = st.mode & 0o7777;
  const modeOctal = mode.toString(8).padStart(4, "0");
  const modeBits = st.mode & S_IFMT;

  if (modeBits === S_IFDIR) {
    const diskPath = vfsPath === "/" ? diskRoot : join(diskRoot, stripLeadingSlash(vfsPath));
    mkdirSync(diskPath, { recursive: true });
    lines.push({ kind: "node", text: `${padPath(vfsPath)} d  ${modeOctal}  ${st.uid}  ${st.gid}` });

    const handle = mfs.opendir(vfsPath);
    const names: string[] = [];
    try {
      while (true) {
        const e = mfs.readdir(handle);
        if (!e) break;
        if (e.name === "." || e.name === "..") continue;
        names.push(e.name);
      }
    } finally {
      mfs.closedir(handle);
    }
    names.sort();
    for (const n of names) {
      const childVfs = vfsPath === "/" ? `/${n}` : `${vfsPath}/${n}`;
      walk(mfs, childVfs, diskRoot, lines);
    }
    return;
  }

  if (modeBits === S_IFLNK) {
    const target = mfs.readlink(vfsPath);
    lines.push({
      kind: "node",
      text: `${padPath(vfsPath)} l  ${modeOctal}  ${st.uid}  ${st.gid}  target=${target}`,
    });
    return;
  }

  if (modeBits === S_IFREG) {
    const diskPath = join(diskRoot, stripLeadingSlash(vfsPath));
    mkdirSync(join(diskPath, ".."), { recursive: true });
    const content = readWhole(mfs, vfsPath, st.size);
    writeFileSync(diskPath, content);
    lines.push({ kind: "node", text: `${padPath(vfsPath)} f  ${modeOctal}  ${st.uid}  ${st.gid}` });
    return;
  }

  // Skip device nodes, sockets, FIFOs — v1 doesn't emit those.
}

function readWhole(mfs: MemoryFileSystem, path: string, size: number): Uint8Array {
  const fd = mfs.open(path, 0, 0);
  try {
    const buf = new Uint8Array(size);
    let offset = 0;
    while (offset < size) {
      const n = mfs.read(fd, buf.subarray(offset), null, size - offset);
      if (n <= 0) break;
      offset += n;
    }
    return buf.subarray(0, offset);
  } finally {
    mfs.close(fd);
  }
}

function stripLeadingSlash(p: string): string {
  return p.replace(/^\/+/, "");
}

function padPath(p: string): string {
  return p.padEnd(Math.max(20, p.length + 1));
}
