export interface Preset {
  id: string;
  title: string;
  summary: string;
  base: string;
  packages: string[];
  accent: string;
  glyph: string;
  bootCommand: string[];
  estimatedUrlBytes: number;
}

export const PRESET_LIBRARY: Preset[] = [
  {
    id: "shell",
    title: "Bare shell",
    summary: "Bash, dash, coreutils, and the full utility set from the shell demo.",
    base: "kandelo:shell@abi8",
    packages: [
      "bash@local",
      "dash@local",
      "coreutils@local",
      "grep@local",
      "sed@local",
      "curl@local",
      "git@local",
      "nano@local",
    ],
    accent: "#dc6529",
    glyph: "sh",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 312,
  },
  {
    id: "node",
    title: "Node.js",
    summary: "Node.js and npm layered onto the shell demo VFS with a writable /work project.",
    base: "kandelo:shell@abi8",
    packages: ["node@local", "node-vfs@local", "npm@10.9.2", "bash@local", "coreutils@local"],
    accent: "#43853d",
    glyph: "js",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 864,
  },
  {
    id: "nginx",
    title: "nginx",
    summary: "Static HTTP service supervised by dinit and exposed through the browser bridge.",
    base: "kandelo:shell@abi8",
    packages: ["dinit@local", "nginx@local", "bash@local", "coreutils@local"],
    accent: "#3a8f41",
    glyph: "nx",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 756,
  },
  {
    id: "nginx-php",
    title: "nginx + PHP",
    summary: "nginx forwarding through FastCGI to PHP-FPM.",
    base: "kandelo:shell@abi8",
    packages: ["dinit@local", "nginx@local", "php-fpm@local", "bash@local", "coreutils@local"],
    accent: "#6b63a6",
    glyph: "php",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 944,
  },
  {
    id: "wordpress-sqlite",
    title: "WordPress SQLite",
    summary: "WordPress on nginx + PHP-FPM with the SQLite database plugin.",
    base: "kandelo:shell@abi8",
    packages: [
      "dinit@local",
      "nginx@local",
      "php-fpm@local",
      "wordpress@local",
      "sqlite@local",
      "bash@local",
      "coreutils@local",
    ],
    accent: "#21759b",
    glyph: "wp",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 1284,
  },
  {
    id: "wordpress-mariadb",
    title: "WordPress MariaDB",
    summary: "WordPress on nginx + PHP-FPM with MariaDB.",
    base: "kandelo:shell@abi8",
    packages: [
      "dinit@local",
      "nginx@local",
      "php-fpm@local",
      "mariadb@local",
      "wordpress@local",
      "bash@local",
      "coreutils@local",
    ],
    accent: "#5f8f73",
    glyph: "wp+",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 1442,
  },
  {
    id: "wordpress-development",
    title: "WordPress Development",
    summary: "A shallow-cloned wordpress-develop repo with MariaDB, PHPUnit, Node, npm, and dev scripts.",
    base: "kandelo:shell@abi8",
    packages: [
      "dinit@local",
      "nginx@local",
      "php@local",
      "php-fpm@local",
      "mariadb@local",
      "node@local",
      "npm@local",
      "phpunit@local",
      "wordpress-develop@git",
    ],
    accent: "#3858e9",
    glyph: "dev",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 1880,
  },
  {
    id: "doom",
    title: "fbDOOM",
    summary: "id Software's DOOM rendering directly to /dev/fb0.",
    base: "kandelo:shell@abi8",
    packages: ["fbdoom@local", "doom-shareware@local", "bash@local", "coreutils@local"],
    accent: "#b5301c",
    glyph: "D",
    bootCommand: ["/usr/games/fbdoom"],
    estimatedUrlBytes: 1018,
  },
];
