export interface Preset {
  id: string;
  title: string;
  summary: string;
  base: string;
  packages: string[];
  accent: string;
  glyph: string;
  bootCommand: string[];
  estimatedUrlBytes: number;
}

export const PRESET_LIBRARY: Preset[] = [
  {
    id: "shell",
    title: "Bare shell",
    summary: "Bash, dash, coreutils, and the full utility set from the shell demo.",
    base: "kandelo:shell@abi8",
    packages: [
      "bash@local",
      "dash@local",
      "coreutils@local",
      "grep@local",
      "sed@local",
      "curl@local",
      "git@local",
      "nano@local",
    ],
    accent: "#dc6529",
    glyph: "sh",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 312,
  },
  {
    id: "node",
    title: "Node.js",
    summary: "SpiderMonkey-backed Node.js compatibility runtime with npm staged as /usr/bin/node.",
    base: "kandelo:shell@abi12",
    packages: ["node@local", "node-vfs@local", "npm@10.9.2", "bash@local", "coreutils@local"],
    accent: "#43853d",
    glyph: "js",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 812,
  },
  {
    id: "nginx",
    title: "nginx",
    summary: "Static HTTP service supervised by dinit and exposed through the browser bridge.",
    base: "kandelo:shell@abi8",
    packages: ["dinit@local", "nginx@local", "bash@local", "coreutils@local"],
    accent: "#3a8f41",
    glyph: "nx",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 756,
  },
  {
    id: "nginx-php",
    title: "nginx + PHP",
    summary: "nginx forwarding through FastCGI to PHP-FPM.",
    base: "kandelo:shell@abi8",
    packages: ["dinit@local", "nginx@local", "php-fpm@local", "bash@local", "coreutils@local"],
    accent: "#6b63a6",
    glyph: "php",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 944,
  },
  {
    id: "wordpress-sqlite",
    title: "WordPress SQLite",
    summary: "WordPress on nginx + PHP-FPM with the SQLite database plugin.",
    base: "kandelo:shell@abi8",
    packages: [
      "dinit@local",
      "nginx@local",
      "php-fpm@local",
      "wordpress@local",
      "sqlite@local",
      "bash@local",
      "coreutils@local",
    ],
    accent: "#21759b",
    glyph: "wp",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 1284,
  },
  {
    id: "wordpress-mariadb",
    title: "WordPress MariaDB",
    summary: "WordPress on nginx + PHP-FPM with MariaDB.",
    base: "kandelo:shell@abi8",
    packages: [
      "dinit@local",
      "nginx@local",
      "php-fpm@local",
      "mariadb@local",
      "wordpress@local",
      "bash@local",
      "coreutils@local",
    ],
    accent: "#5f8f73",
    glyph: "wp+",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl"],
    estimatedUrlBytes: 1442,
  },
  {
    id: "doom",
    title: "fbDOOM",
    summary: "id Software's DOOM rendering directly to /dev/fb0.",
    base: "kandelo:shell@abi8",
    packages: ["fbdoom@local", "doom-shareware@local", "bash@local", "coreutils@local"],
    accent: "#b5301c",
    glyph: "D",
    bootCommand: ["/usr/games/fbdoom"],
    estimatedUrlBytes: 1018,
  },
  {
    id: "love",
    title: "LOVE games",
    summary: "Lua game demos rendered by a native LOVE-style /dev/fb0 runtime.",
    base: "kandelo:shell@abi8",
    packages: ["love@local", "bash@local", "coreutils@local"],
    accent: "#e04b83",
    glyph: "lv",
    bootCommand: ["/usr/local/bin/love", "/usr/local/share/love/examples"],
    estimatedUrlBytes: 1056,
  },
  {
    id: "bytepath",
    title: "BYTEPATH",
    summary: "The open-source LÖVE arcade shooter running through Kandelo's native framebuffer runtime.",
    base: "kandelo:shell@abi8",
    packages: ["love@local", "bash@local", "coreutils@local"],
    accent: "#7bd7c2",
    glyph: "BP",
    bootCommand: ["/usr/local/bin/love", "/usr/local/share/love/examples/bytepath"],
    estimatedUrlBytes: 1120,
  },
  {
    id: "snkrx",
    title: "SNKRX",
    summary: "The open-source LÖVE snake roguelite running through Kandelo's native framebuffer runtime.",
    base: "kandelo:shell@abi8",
    packages: ["love@local", "bash@local", "coreutils@local"],
    accent: "#f0cf45",
    glyph: "SX",
    bootCommand: ["/usr/local/bin/love", "/usr/local/share/love/examples/snkrx"],
    estimatedUrlBytes: 1140,
  },
];
