import { ABI_VERSION } from "../../../../host/src/generated/abi";

export interface Preset {
  id: string;
  title: string;
  summary: string;
  base: string;
  packages: string[];
  accent: string;
  glyph: string;
  bootCommand: string[];
  estimatedUrlBytes: number;
}

const SHELL_BASE = `kandelo:shell@abi${ABI_VERSION}`;

export const PRESET_LIBRARY: Preset[] = [
  {
    id: "shell",
    title: "Bare shell",
    summary: "Bash, dash, coreutils, and the full utility set from the shell image.",
    base: SHELL_BASE,
    packages: [
      "bash@local",
      "dash@local",
      "coreutils@local",
      "grep@local",
      "sed@local",
      "curl@local",
      "git@local",
      "nano@local",
    ],
    accent: "#3858e9",
    glyph: "sh",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 312,
  },
  {
    id: "node",
    title: "Node.js",
    summary: "SpiderMonkey-backed Node.js compatibility runtime with npm staged as /usr/bin/node.",
    base: SHELL_BASE,
    packages: ["node@local", "node-vfs@local", "npm@10.9.2", "bash@local", "coreutils@local"],
    accent: "#43853d",
    glyph: "js",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 812,
  },
  {
    id: "nginx",
    title: "nginx",
    summary: "Static HTTP service supervised by dinit and exposed through the browser bridge.",
    base: SHELL_BASE,
    packages: ["dinit@local", "nginx@local", "bash@local", "coreutils@local"],
    accent: "#3a8f41",
    glyph: "nx",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl", "nginx"],
    estimatedUrlBytes: 756,
  },
  {
    id: "nginx-php",
    title: "nginx + PHP",
    summary: "nginx forwarding through FastCGI to PHP-FPM.",
    base: SHELL_BASE,
    packages: ["dinit@local", "nginx@local", "php-fpm@local", "bash@local", "coreutils@local"],
    accent: "#6b63a6",
    glyph: "php",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl", "nginx"],
    estimatedUrlBytes: 944,
  },
  {
    id: "wordpress-sqlite",
    title: "WordPress SQLite",
    summary: "WordPress on nginx + PHP-FPM with the SQLite database plugin.",
    base: SHELL_BASE,
    packages: [
      "dinit@local",
      "nginx@local",
      "php-fpm@local",
      "wordpress@local",
      "sqlite@local",
      "bash@local",
      "coreutils@local",
    ],
    accent: "#21759b",
    glyph: "wp",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl", "nginx"],
    estimatedUrlBytes: 1284,
  },
  {
    id: "wordpress-mariadb",
    title: "WordPress MariaDB",
    summary: "WordPress on nginx + PHP-FPM with MariaDB.",
    base: SHELL_BASE,
    packages: [
      "dinit@local",
      "nginx@local",
      "php-fpm@local",
      "mariadb@local",
      "wordpress@local",
      "bash@local",
      "coreutils@local",
    ],
    accent: "#5f8f73",
    glyph: "wp+",
    bootCommand: ["/sbin/dinit", "--container", "-p", "/tmp/dinitctl", "nginx"],
    estimatedUrlBytes: 1442,
  },
  {
    id: "doom",
    title: "fbDOOM",
    summary: "DOOM on /dev/fb0 with OSS audio through /dev/dsp.",
    base: SHELL_BASE,
    packages: ["fbdoom@local", "doom-shareware@local", "bash@local", "coreutils@local"],
    accent: "#b5301c",
    glyph: "D",
    bootCommand: ["/usr/games/fbdoom"],
    estimatedUrlBytes: 1018,
  },
  {
    id: "modeset",
    title: "DRM/KMS fluid sim",
    summary: "Pavel-style EGL/GLES fluid simulation presented through /dev/dri/card0 page flips.",
    base: SHELL_BASE,
    packages: ["modeset@local", "bash@local", "coreutils@local"],
    accent: "#4f8fd6",
    glyph: "K",
    bootCommand: ["/usr/local/bin/modeset"],
    estimatedUrlBytes: 612,
  },
  {
    id: "sdl2",
    title: "SDL2 GLSL playground",
    summary: "SDL2 GLSL shader playground: a live-coding editor (left) beside a GLES2 fragment shader rendered on a 1920×1080 /dev/dri/card0 surface (right), auto-recompiling 250 ms after you stop typing. F1/F2 switch between the image and sound shader, Ctrl+L cycles presets, Ctrl+S persists, ESC quits.",
    base: SHELL_BASE,
    packages: ["bash@local", "coreutils@local"],
    accent: "#9c27b0",
    glyph: "S",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 612,
  },
  {
    id: "scummvm",
    title: "ScummVM",
    summary: "ScummVM's SCUMM engine fullscreen on /dev/dri/card0: SDL2's KMSDRM backend takes the display as DRM master and renders GLES2 directly, with OSS audio on /dev/dsp. No game ships with it: upload a zipped SCUMM title with Load game data, then add it from the launcher.",
    base: SHELL_BASE,
    packages: ["bash@local", "coreutils@local"],
    accent: "#c46a3c",
    glyph: "G",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 612,
  },
  {
    id: "wayland",
    title: "Wayland terminal",
    summary: "A real Wayland stack on /dev/dri/card0: wlcompositor (a wl_shm/xdg_shell server driving KMS) composites wlterm — a VT100 terminal built on the in-tree libkwl toolkit — running a forkpty'd dash shell. Type to drive the shell; output renders through the compositor.",
    base: SHELL_BASE,
    packages: ["bash@local", "coreutils@local"],
    accent: "#3a7d7b",
    glyph: "W",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 612,
  },
  {
    id: "hyprland",
    title: "Hyprland tiling WM",
    summary: "wlcompositor in dwindle mode — a Hyprland-class tiling window manager on /dev/dri/card0. Two wlterm terminals and a wlclock tile into gapped, borderless (server-side-decorated) frames; each client honors the compositor's xdg configure to resize into its tile. Open new panes Hyprland-style with per-app launch keybinds: CTRL+Return spawns a terminal, CTRL+K a clock, CTRL+P a paint canvas; CTRL+W kills the focused window and CTRL+1..9 switch workspaces. Every bind is mirrored on SUPER (real Hyprland) and CTRL, which a browser (unlike SUPER=Cmd/Win) doesn't reserve. Bindings from /etc/kandelo/wlcompositor.conf.",
    base: SHELL_BASE,
    packages: ["bash@local", "coreutils@local"],
    accent: "#00aaff",
    glyph: "H",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 612,
  },
  {
    id: "omarchy",
    title: "Omarchy desktop",
    summary: "The Omarchy desktop on Kandelo: the tiling compositor with the shell Omarchy is made of. Unmodified Waybar — the real GTK3 status bar, on wlr-layer-shell, its hyprland modules reading the compositor's Hyprland IPC sockets — reserves the top strip (workspaces, focused window, clock) and the windows tile beneath it. CTRL+Space opens klauncher, a keyboard-exclusive overlay launcher reading /usr/share/kandelo/apps; type to filter and Enter to launch — including Theme Gallery, a QtGui application whose cards preview every installed theme and restyle the whole desktop on click, or swap the running Quickshell for another QML shell. CTRL+SHIFT+Space cycles six themes (Tokyo Night, Catppuccin, Gruvbox, Nord, Everforest, Rosé Pine), each with its own Omarchy background image, recolouring the borders, gaps, wallpaper, bar and launcher live from one palette file. CTRL+Return spawns a terminal, CTRL+K a clock, CTRL+P a paint canvas, CTRL+W closes, CTRL+1..9 switch workspaces — every bind mirrored on SUPER for real Hyprland.",
    base: SHELL_BASE,
    packages: ["bash@local", "coreutils@local"],
    accent: "#7aa2f7",
    glyph: "O",
    bootCommand: ["bash", "-l", "-i"],
    estimatedUrlBytes: 612,
  },
];
