/* wpkdraw font engine — see include/wpkdraw/wpkfont.h.
 *
 * The stb_truetype implementation is compiled in a separate TU
 * (wpk_stb_impl.c, generated by build.sh); here we include the header
 * declarations only. The font bytes come from the build-time-generated
 * wpk_font_ttf.h (source of truth: third_party/Inconsolata-Regular.ttf).
 */
#include <wpkdraw/wpkfont.h>

#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "stb_truetype.h"
#include "wpk_font_ttf.h" /* wpk_font_ttf[] */

#define WPK_GLYPH_CACHE_CAP 256

struct cached_glyph {
    int valid;              /* 0 = empty slot */
    int codepoint;
    int w, h, xoff, yoff;   /* stb glyph bitmap box + offset from origin */
    int advance;            /* horizontal advance in font units */
    unsigned char *bitmap;  /* stb-malloc'd 8-bit alpha mask (or NULL) */
};

struct wpk_font {
    stbtt_fontinfo info;
    int px_size;
    float scale;
    int ascent, descent;  /* font-unit vmetrics */
    struct cached_glyph cache[WPK_GLYPH_CACHE_CAP];
    int cache_next;                  /* FIFO eviction cursor */
};

struct wpk_font *wpk_font_load_default(int px_size) {
    if (px_size < 4 || px_size > 256) { errno = EINVAL; return NULL; }
    struct wpk_font *f = calloc(1, sizeof *f);
    if (!f) { errno = ENOMEM; return NULL; }
    int off = stbtt_GetFontOffsetForIndex(wpk_font_ttf, 0);
    if (off < 0 || !stbtt_InitFont(&f->info, wpk_font_ttf, off)) {
        free(f);
        errno = EINVAL;
        return NULL;
    }
    f->px_size = px_size;
    f->scale = stbtt_ScaleForPixelHeight(&f->info, (float)px_size);
    stbtt_GetFontVMetrics(&f->info, &f->ascent, &f->descent, NULL);
    return f;
}

void wpk_font_destroy(struct wpk_font *f) {
    if (!f) return;
    for (int i = 0; i < WPK_GLYPH_CACHE_CAP; i++)
        if (f->cache[i].bitmap) stbtt_FreeBitmap(f->cache[i].bitmap, NULL);
    free(f);
}

static struct cached_glyph *get_glyph(struct wpk_font *f, int cp) {
    for (int i = 0; i < WPK_GLYPH_CACHE_CAP; i++)
        if (f->cache[i].valid && f->cache[i].codepoint == cp)
            return &f->cache[i];
    /* Miss — render into the next FIFO slot, evicting whatever's there. */
    struct cached_glyph *g = &f->cache[f->cache_next];
    f->cache_next = (f->cache_next + 1) % WPK_GLYPH_CACHE_CAP;
    if (g->bitmap) { stbtt_FreeBitmap(g->bitmap, NULL); g->bitmap = NULL; }
    g->valid = 1;
    g->codepoint = cp;
    g->bitmap = stbtt_GetCodepointBitmap(&f->info, 0, f->scale, cp,
                                         &g->w, &g->h, &g->xoff, &g->yoff);
    stbtt_GetCodepointHMetrics(&f->info, cp, &g->advance, NULL);
    return g;
}

/* Decode one codepoint and advance *pp. Returns 0 at NUL; malformed or
 * 4-byte sequences yield '?' (v1 is BMP-only). */
static int decode_utf8(const char **pp) {
    const unsigned char *p = (const unsigned char *)*pp;
    if (!*p) return 0;
    int c;
    if ((*p & 0x80) == 0)          { c = *p; *pp += 1; }
    else if ((*p & 0xe0) == 0xc0)  { c = (*p & 0x1f) << 6 | (p[1] & 0x3f);
                                     *pp += 2; }
    else if ((*p & 0xf0) == 0xe0)  { c = (*p & 0x0f) << 12 | (p[1] & 0x3f) << 6
                                         | (p[2] & 0x3f);
                                     *pp += 3; }
    else                           { c = '?'; *pp += 1; }
    return c;
}

int wpk_text_width(struct wpk_font *f, const char *utf8) {
    if (!f || !utf8) return 0;
    float x = 0;
    while (*utf8) {
        int cp = decode_utf8(&utf8);
        if (cp == 0) break;
        int adv;
        stbtt_GetCodepointHMetrics(&f->info, cp, &adv, NULL);
        x += adv * f->scale;
    }
    return (int)(x + 0.5f);
}

void wpk_text(struct wpk_surface *s, struct wpk_font *f,
              int x, int y, const char *utf8, wpk_color color) {
    if (!s || !f || !utf8) return;
    while (*utf8) {
        int cp = decode_utf8(&utf8);
        if (cp == 0) break;
        struct cached_glyph *g = get_glyph(f, cp);
        if (g->bitmap) {
            for (int gy = 0; gy < g->h; gy++) {
                for (int gx = 0; gx < g->w; gx++) {
                    unsigned char a = g->bitmap[gy * g->w + gx];
                    if (!a) continue;
                    wpk_color c = (color & 0x00ffffffu) | ((uint32_t)a << 24);
                    wpk_pixel(s, x + g->xoff + gx, y + g->yoff + gy, c);
                }
            }
        }
        x += (int)(g->advance * f->scale + 0.5f);
    }
}

int wpk_font_height_px(struct wpk_font *f) {
    if (!f) return 0;
    return (int)((f->ascent - f->descent) * f->scale + 0.5f);
}

int wpk_font_ascent_px(struct wpk_font *f) {
    if (!f) return 0;
    return (int)(f->ascent * f->scale + 0.5f);
}
