/* wpkdraw font engine — see include/wpkdraw/wpkfont.h.
 *
 * The stb_truetype implementation is compiled in a separate TU
 * (wpk_stb_impl.c, generated by build.sh); here we include the header
 * declarations only. The font bytes come from the build-time-generated
 * wpk_font_ttf.h (source of truth: the repository-root
 * third_party/Inconsolata-Regular.ttf, shared with the SDL2 playground).
 */
#include <wpkdraw/wpkfont.h>

#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "stb_truetype.h"
#include "wpk_font_ttf.h" /* wpk_font_ttf[] */

#define WPK_GLYPH_CACHE_CAP 256

struct cached_glyph {
    int valid;              /* 0 = empty slot */
    int codepoint;
    int w, h, xoff, yoff;   /* stb glyph bitmap box + offset from origin */
    int advance;            /* horizontal advance in font units */
    unsigned char *bitmap;  /* stb-malloc'd 8-bit alpha mask (or NULL) */
};

struct wpk_font {
    stbtt_fontinfo info;
    int px_size;          /* the LOGICAL size the caller asked for */
    int ui_scale;         /* wpk_scale() at load time; glyphs are this bigger */
    float scale;          /* font units -> DEVICE pixels */
    int ascent, descent;  /* font-unit vmetrics */
    struct cached_glyph cache[WPK_GLYPH_CACHE_CAP];
    int cache_next;                  /* FIFO eviction cursor */
};

struct wpk_font *wpk_font_load_default(int px_size) {
    if (px_size < 4 || px_size > 256) { errno = EINVAL; return NULL; }
    struct wpk_font *f = calloc(1, sizeof *f);
    if (!f) { errno = ENOMEM; return NULL; }
    int off = stbtt_GetFontOffsetForIndex(wpk_font_ttf, 0);
    if (off < 0 || !stbtt_InitFont(&f->info, wpk_font_ttf, off)) {
        free(f);
        errno = EINVAL;
        return NULL;
    }
    f->px_size = px_size;
    /* Rasterize at the device size. Asking stb for bigger glyphs is the only
     * thing that makes text sharper on a scaled output — a mask rendered at
     * the logical size and blown up is exactly the blur being removed. */
    f->ui_scale = wpk_scale();
    f->scale = stbtt_ScaleForPixelHeight(&f->info,
                                         (float)(px_size * f->ui_scale));
    stbtt_GetFontVMetrics(&f->info, &f->ascent, &f->descent, NULL);
    return f;
}

void wpk_font_destroy(struct wpk_font *f) {
    if (!f) return;
    for (int i = 0; i < WPK_GLYPH_CACHE_CAP; i++)
        if (f->cache[i].bitmap) stbtt_FreeBitmap(f->cache[i].bitmap, NULL);
    free(f);
}

static struct cached_glyph *get_glyph(struct wpk_font *f, int cp) {
    for (int i = 0; i < WPK_GLYPH_CACHE_CAP; i++)
        if (f->cache[i].valid && f->cache[i].codepoint == cp)
            return &f->cache[i];
    /* Miss — render into the next FIFO slot, evicting whatever's there. */
    struct cached_glyph *g = &f->cache[f->cache_next];
    f->cache_next = (f->cache_next + 1) % WPK_GLYPH_CACHE_CAP;
    if (g->bitmap) { stbtt_FreeBitmap(g->bitmap, NULL); g->bitmap = NULL; }
    g->valid = 1;
    g->codepoint = cp;
    g->bitmap = stbtt_GetCodepointBitmap(&f->info, 0, f->scale, cp,
                                         &g->w, &g->h, &g->xoff, &g->yoff);
    stbtt_GetCodepointHMetrics(&f->info, cp, &g->advance, NULL);
    return g;
}

/* Decode one codepoint and advance *pp. Returns 0 at NUL. A malformed,
 * truncated, overlong, or surrogate sequence yields U+FFFD and consumes the
 * bytes examined so far -- never past the terminating NUL, which is not a
 * continuation byte and so stops the scan. */
static int decode_utf8(const char **pp) {
    const unsigned char *p = (const unsigned char *)*pp;
    unsigned char b = p[0];
    if (!b) return 0;
    if (b < 0x80) { *pp += 1; return b; }
    int need, cp, min;
    if ((b & 0xe0) == 0xc0)      { need = 1; cp = b & 0x1f; min = 0x80; }
    else if ((b & 0xf0) == 0xe0) { need = 2; cp = b & 0x0f; min = 0x800; }
    else if ((b & 0xf8) == 0xf0) { need = 3; cp = b & 0x07; min = 0x10000; }
    else { *pp += 1; return 0xFFFD; }
    for (int i = 1; i <= need; i++) {
        if ((p[i] & 0xc0) != 0x80) { *pp += i; return 0xFFFD; }
        cp = cp << 6 | (p[i] & 0x3f);
    }
    *pp += need + 1;
    if (cp < min || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF))
        return 0xFFFD;
    return cp;
}

int wpk_text_width(struct wpk_font *f, const char *utf8) {
    if (!f || !utf8) return 0;
    float x = 0;
    while (*utf8) {
        int cp = decode_utf8(&utf8);
        if (cp == 0) break;
        int adv;
        stbtt_GetCodepointHMetrics(&f->info, cp, &adv, NULL);
        x += adv * f->scale;
    }
    return (int)(x / (float)f->ui_scale + 0.5f);
}

void wpk_text(struct wpk_surface *s, struct wpk_font *f,
              int x, int y, const char *utf8, wpk_color color) {
    if (!s || !f || !utf8) return;
    /* The origin is logical; the glyph masks are device pixels. Advance in
     * device pixels so a run of text does not accumulate rounding error at
     * every character. */
    int px = x * s->scale, py = y * s->scale;
    while (*utf8) {
        int cp = decode_utf8(&utf8);
        if (cp == 0) break;
        struct cached_glyph *g = get_glyph(f, cp);
        if (g->bitmap) {
            for (int gy = 0; gy < g->h; gy++) {
                for (int gx = 0; gx < g->w; gx++) {
                    unsigned char a = g->bitmap[gy * g->w + gx];
                    if (!a) continue;
                    wpk_color c = (color & 0x00ffffffu) | ((uint32_t)a << 24);
                    wpk_pixel_device(s, px + g->xoff + gx, py + g->yoff + gy, c);
                }
            }
        }
        px += (int)(g->advance * f->scale + 0.5f);
    }
}

int wpk_font_height_px(struct wpk_font *f) {
    if (!f) return 0;
    return (int)((f->ascent - f->descent) * f->scale / (float)f->ui_scale + 0.5f);
}

int wpk_font_ascent_px(struct wpk_font *f) {
    if (!f) return 0;
    return (int)(f->ascent * f->scale / (float)f->ui_scale + 0.5f);
}
