#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
output="${1:-$repo_root/scripts/resolve-binary.bundle.mjs}"

mkdir -p "$(dirname "$output")"
cd "$repo_root"
npx --no-install esbuild scripts/resolve-binary.ts \
    --bundle \
    --platform=node \
    --format=esm \
    --target=node22 \
    --minify \
    --legal-comments=none \
    --banner:js='// Generated by scripts/build-resolve-binary-bundle.sh; do not edit. Third-party notices: resolve-binary.bundle.LICENSES.txt' \
    --outfile="$output"
