#!/usr/bin/env bash
#
# Walk a directory of CI artifact subdirs (each named "<pkg>-<arch>"
# and containing exactly one .tar.zst) and write
# packages/registry/<pkg>/package.pr.toml entries pointing at the local
# archive via file:// URL + sha256. The resolver applies these
# overlays at lookup time, so a downstream `xtask build-deps resolve`
# (or `archive-stage`) finds the archive without source-building.
#
# Used by:
#   * matrix-build (program wave) — pre-stage already-built archives so
#     the program's transitive deps are warm-cache hits.
#   * test-gate's "Materialize binaries" — same primitive, applied to
#     both lib + prog matrix outputs.
#
# Inputs:
#   $1  Artifact root (e.g. $RUNNER_TEMP/staged-archives or
#       $RUNNER_TEMP/lib-archives). Each immediate subdir is
#       "<pkg>-<arch>" with a single .tar.zst inside.
#   $2  (optional) Stage dir to copy archives into before pointing
#       file:// at them. Defaults to $1 (use the artifact dir as-is).
#       The copy is only useful when the artifact dir is on a
#       short-lived volume; a stable archive path lets the resolver
#       cache it across reruns.
#
# Writes:
#   packages/registry/<pkg>/package.pr.toml — accumulating one
#   [binary.<arch>] block per artifact processed. Duplicate (package,
#   arch) overlays are rejected here so independently materialized
#   inherited/current artifact sets cannot create ambiguous TOML.
#
# Echoes one log line per overlay written. Exits 0 if the artifact
# dir is empty or absent (no overlays needed); fails on malformed
# artifact names, duplicate overlays, or artifact directories that do
# not contain exactly one .tar.zst.

set -euo pipefail

ART_DIR="${1:-}"
[ -n "$ART_DIR" ] || { echo "usage: $0 <artifact-dir> [stage-dir]" >&2; exit 2; }
STAGE_DIR="${2:-$ART_DIR}"

if [ ! -d "$ART_DIR" ]; then
    echo "materialize-pr-overlays: $ART_DIR does not exist; nothing to materialize"
    exit 0
fi

mkdir -p "$STAGE_DIR"

shopt -s nullglob
count=0
for adir in "$ART_DIR"/*/; do
    aname=$(basename "$adir")

    # Artifact name shape: "<pkg>-<arch>". Trailing arch tag tells us
    # which [binary.<arch>] block to write.
    case "$aname" in
        *-wasm32) arch=wasm32; pkg="${aname%-wasm32}" ;;
        *-wasm64) arch=wasm64; pkg="${aname%-wasm64}" ;;
        *)
            echo "materialize-pr-overlays: artifact $aname does not end in -wasm32 or -wasm64" >&2
            exit 1
            ;;
    esac

    ptoml="packages/registry/$pkg/package.toml"
    if [ ! -f "$ptoml" ]; then
        echo "materialize-pr-overlays: no package.toml for $pkg (artifact $aname)" >&2
        exit 1
    fi

    # Exactly one .tar.zst per matrix entry.
    archives=("$adir"*.tar.zst)
    if [ "${#archives[@]}" -ne 1 ]; then
        echo "materialize-pr-overlays: artifact $aname must contain exactly one .tar.zst; found ${#archives[@]}" >&2
        exit 1
    fi
    archive="${archives[0]}"

    if [ "$STAGE_DIR" != "$ART_DIR" ]; then
        dest="$STAGE_DIR/$(basename "$archive")"
        cp "$archive" "$dest"
        archive_path="$dest"
    else
        archive_path="$archive"
    fi

    sha=$(sha256sum "$archive_path" | awk '{print $1}')
    url="file://$archive_path"

    prtoml="packages/registry/$pkg/package.pr.toml"
    if [ -f "$prtoml" ] && grep -Fqx "[binary.$arch]" "$prtoml"; then
        echo "materialize-pr-overlays: duplicate overlay for $pkg ($arch)" >&2
        exit 1
    fi
    if [ ! -f "$prtoml" ]; then
        cat > "$prtoml" <<EOF
# Generated by scripts/materialize-pr-overlays.sh; pins matrix-built
# archives via file:// URLs. The resolver merges these on top of
# package.toml's [binary.<arch>] block at lookup time.
EOF
    fi

    {
        echo ""
        echo "[binary.$arch]"
        echo "archive_url = \"$url\""
        echo "archive_sha256 = \"$sha\""
    } >> "$prtoml"

    echo "materialize-pr-overlays: $pkg ($arch) -> $url"
    count=$((count + 1))
done

echo "materialize-pr-overlays: wrote $count overlay block(s) under packages/registry/*/package.pr.toml"
