#!/usr/bin/env bash
set -euo pipefail

INVENTORY_NAME=".ci-exact-abi-source-test-inventory.json"
MAX_FILE_BYTES=$((512 * 1024 * 1024))
MAX_TOTAL_BYTES=$((1024 * 1024 * 1024))
EXACT_WORKSPACE_PRIVATE_ROOT=""

cleanup_private_root() {
    if [ -n "${EXACT_WORKSPACE_PRIVATE_ROOT:-}" ]; then
        rm -rf -- "$EXACT_WORKSPACE_PRIVATE_ROOT"
        EXACT_WORKSPACE_PRIVATE_ROOT=""
    fi
}
trap cleanup_private_root EXIT

# These are the only generated bytes consumed by the exact source-only lane.
# The kernel is copied from Cargo's exact output rather than from the mutable
# resolver mirror. The rootfs is a package-free test fixture built from this
# checkout's manifest/source tree. Audio/mouse and the worker recursion module
# are ordinary repository test fixtures built from this same checkout/sysroot.
artifact_rows() {
    printf '%s\t%s\n' \
        'host/test/fixtures/deep-wasm-recursion.wasm' \
            'host/test/fixtures/deep-wasm-recursion.wasm' \
        'local-binaries/programs/wasm32/audiotest.wasm' \
            'host/wasm/audiotest.wasm' \
        'local-binaries/programs/wasm32/mousetest.wasm' \
            'host/wasm/mousetest.wasm' \
        'target/wasm32-unknown-unknown/release/kandelo_kernel.wasm' \
            'host/wasm/kandelo-kernel.wasm' \
        'target/wasm32-unknown-unknown/release/kandelo_kernel.wasm' \
            'local-binaries/kernel.wasm' \
        'target/exact-abi-source-test/rootfs.vfs' \
            'host/wasm/rootfs.vfs'
}

fail() {
    echo "pack-exact-abi-source-test-workspace: $*" >&2
    exit 1
}

usage() {
    cat >&2 <<'EOF'
usage:
  pack-exact-abi-source-test-workspace.sh list
  pack-exact-abi-source-test-workspace.sh pack --source-root <absolute> --archive <absolute>
  pack-exact-abi-source-test-workspace.sh extract --source-root <absolute> --archive <absolute>
EOF
    exit 2
}

sha256_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    else
        shasum -a 256 "$1" | awk '{print $1}'
    fi
}

canonical_directory() {
    local label="$1"
    local input="$2"
    case "$input" in /*) ;; *) fail "$label must be absolute" ;; esac
    [ -d "$input" ] && [ ! -L "$input" ] || fail "$label is not a real directory"
    realpath "$input"
}

validate_source_checkout() {
    local source_root="$1"
    git -C "$source_root" rev-parse --is-inside-work-tree >/dev/null 2>&1 ||
        fail "source root is not a Git worktree"
    local commit tree
    commit="$(git -C "$source_root" rev-parse HEAD)"
    tree="$(git -C "$source_root" rev-parse 'HEAD^{tree}')"
    printf '%s\n' "$commit" | grep -Eq '^[0-9a-f]{40}$' ||
        fail "source commit is not a full lowercase SHA"
    printf '%s\n' "$tree" | grep -Eq '^[0-9a-f]{40}$' ||
        fail "source tree is not a full lowercase SHA"
    git -C "$source_root" diff --quiet --ignore-submodules=none -- ||
        fail "source checkout has tracked modifications"
    git -C "$source_root" diff --cached --quiet --ignore-submodules=none -- ||
        fail "source checkout has staged modifications"
    printf '%s\t%s\n' "$commit" "$tree"
}

assert_no_forbidden_source_artifacts() {
    local source_root="$1"
    if [ -e "$source_root/binaries" ] || [ -L "$source_root/binaries" ]; then
        fail "legacy binaries/ is forbidden from the exact source-test workspace"
    fi

    local found
    found="$({
        find "$source_root/host/wasm" \
            -mindepth 1 -maxdepth 1 -name '*.wasm' -print 2>/dev/null || true
        find "$source_root/host/test/fixtures" \
            -mindepth 1 -maxdepth 1 -name '*.wasm' \
            ! -name 'deep-wasm-recursion.wasm' -print 2>/dev/null || true
        find "$source_root/local-binaries/programs/wasm32" \
            -mindepth 1 -maxdepth 1 -name '*.wasm' \
            ! -name 'audiotest.wasm' ! -name 'mousetest.wasm' \
            -print 2>/dev/null || true
    } | LC_ALL=C sort | head -1)"
    [ -z "$found" ] || fail "undeclared source-test artifact: ${found#"$source_root/"}"

    found="$(find \
        "$source_root/host/wasm" \
        "$source_root/host/test/fixtures" \
        "$source_root/local-binaries" \
        \( -name '*.vfs' -o -name '*.vfs.zst' \) -print 2>/dev/null |
        LC_ALL=C sort | head -1 || true)"
    [ -z "$found" ] || fail "product VFS is forbidden: ${found#"$source_root/"}"

    found="$(find \
        "$source_root/host/wasm" \
        "$source_root/host/test/fixtures" \
        "$source_root/local-binaries" \
        -name '*.tar.zst' -print 2>/dev/null |
        LC_ALL=C sort | head -1 || true)"
    [ -z "$found" ] || fail "package archive is forbidden: ${found#"$source_root/"}"
}

validate_kernel_generation() {
    local source_root="$1"
    local mirror="$source_root/local-binaries/kernel.wasm"
    local cargo_kernel="$source_root/target/wasm32-unknown-unknown/release/kandelo_kernel.wasm"
    [ -L "$mirror" ] || fail "kernel mirror must select one immutable local generation"
    local selected
    selected="$(realpath "$mirror" 2>/dev/null || true)"
    [ -n "$selected" ] && [ -f "$selected" ] && [ ! -L "$selected" ] ||
        fail "kernel mirror must select one immutable local generation"
    case "$selected" in
        "$source_root/local-binaries/.kandelo-local-generations/"*) ;;
        *) fail "kernel mirror must select one immutable local generation" ;;
    esac
    cmp "$cargo_kernel" "$selected" ||
        fail "immutable local kernel generation differs from the exact Cargo output"
}

validate_source_artifact_ancestors() {
    local source_root="$1"
    local relative_path="$2"
    local parent component component_name
    parent="$(dirname "$relative_path")"
    component="$source_root"
    local -a parts=()
    IFS='/' read -r -a parts <<< "$parent"
    for component_name in "${parts[@]}"; do
        [ "$component_name" = . ] && continue
        component="$component/$component_name"
        [ ! -L "$component" ] ||
            fail "source artifact parent is a symbolic link: $relative_path"
        [ -d "$component" ] ||
            fail "source artifact parent is not a directory: $relative_path"
    done
}

validate_regular_artifact() {
    local path="$1"
    local label="$2"
    [ -f "$path" ] && [ ! -L "$path" ] || fail "$label is not a regular file"
    local bytes
    bytes="$(wc -c < "$path" | tr -d '[:space:]')"
    case "$bytes" in ''|*[!0-9]*) fail "$label size is invalid" ;; esac
    [ "$bytes" -gt 0 ] && [ "$bytes" -le "$MAX_FILE_BYTES" ] ||
        fail "$label exceeds its file bound"
    printf '%s\n' "$bytes"
}

write_inventory() {
    local stage="$1"
    local commit="$2"
    local tree="$3"
    shift 3
    node --input-type=module - "$stage" "$commit" "$tree" "$@" <<'NODE'
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [stage, commit, tree, ...paths] = process.argv.slice(2);
const files = paths.sort().map((path) => {
  const bytes = readFileSync(join(stage, path));
  return {
    bytes: bytes.byteLength,
    path,
    sha256: createHash("sha256").update(bytes).digest("hex"),
  };
});
const value = {
  files,
  schema: 1,
  source: { commit, tree },
};
function canonical(input) {
  if (Array.isArray(input)) return input.map(canonical);
  if (input !== null && typeof input === "object") {
    return Object.fromEntries(Object.keys(input).sort().map((key) => [key, canonical(input[key])]));
  }
  return input;
}
writeFileSync(join(stage, ".ci-exact-abi-source-test-inventory.json"),
  `${JSON.stringify(canonical(value))}\n`, { flag: "wx" });
NODE
}

pack_workspace() {
    local source_root="$1"
    local archive="$2"
    source_root="$(canonical_directory "source root" "$source_root")"
    case "$archive" in /*) ;; *) fail "archive path must be absolute" ;; esac
    [ ! -e "$archive" ] && [ ! -L "$archive" ] || fail "archive output already exists"
    local archive_parent
    archive_parent="$(canonical_directory "archive parent" "$(dirname "$archive")")"
    archive="$archive_parent/$(basename "$archive")"

    local source_identity commit tree extra
    source_identity="$(validate_source_checkout "$source_root")"
    IFS=$'\t' read -r commit tree extra <<< "$source_identity"
    [ -n "$commit" ] && [ -n "$tree" ] && [ -z "$extra" ] ||
        fail "source identity is invalid"
    assert_no_forbidden_source_artifacts "$source_root"
    validate_kernel_generation "$source_root"

    local private stage total=0 source_path destination_path bytes
    private="$(mktemp -d "${RUNNER_TEMP:-/tmp}/kandelo-exact-workspace-pack.XXXXXX")"
    EXACT_WORKSPACE_PRIVATE_ROOT="$private"
    stage="$private/workspace"
    mkdir -p "$stage"
    local -a destinations=()
    while IFS=$'\t' read -r source_path destination_path extra; do
        [ -n "$source_path" ] && [ -n "$destination_path" ] && [ -z "$extra" ] ||
            fail "internal artifact allowlist is invalid"
        validate_source_artifact_ancestors "$source_root" "$source_path"
        bytes="$(validate_regular_artifact "$source_root/$source_path" "$source_path")"
        total=$((total + bytes))
        [ "$total" -le "$MAX_TOTAL_BYTES" ] || fail "source-test workspace exceeds its aggregate bound"
        mkdir -p "$stage/$(dirname "$destination_path")"
        cp -- "$source_root/$source_path" "$stage/$destination_path"
        chmod u=rw,go=r "$stage/$destination_path"
        destinations+=("$destination_path")
    done < <(artifact_rows)
    write_inventory "$stage" "$commit" "$tree" "${destinations[@]}"
    chmod u=rw,go=r "$stage/$INVENTORY_NAME"

    local temporary_archive="$private/workspace.tar.zst"
    tar --sort=name --mtime='UTC 1970-01-01' \
        --owner=0 --group=0 --numeric-owner \
        --mode='u+rwX,go+rX,go-w' \
        --pax-option=delete=atime,delete=ctime \
        -I 'zstd -19 --threads=1' \
        -cf "$temporary_archive" -C "$stage" .
    mv "$temporary_archive" "$archive"
    cleanup_private_root
}

validate_extracted_workspace() {
    local source_root="$1"
    local workspace="$2"
    local inventory="$workspace/$INVENTORY_NAME"
    local inventory_bytes
    inventory_bytes="$(validate_regular_artifact "$inventory" "$INVENTORY_NAME")"
    [ "$inventory_bytes" -le 1048576 ] || fail "source-test inventory exceeds its byte bound"

    local commit tree
    IFS=$'\t' read -r commit tree _ <<< "$(validate_source_checkout "$source_root")"
    node --input-type=module - "$workspace" "$inventory" "$commit" "$tree" <<'NODE'
import { createHash } from "node:crypto";
import { lstatSync, readFileSync } from "node:fs";
import { isAbsolute, join } from "node:path";

const [workspace, inventoryPath, commit, tree] = process.argv.slice(2);
const bytes = readFileSync(inventoryPath);
const value = JSON.parse(bytes.toString("utf8"));
function canonical(input) {
  if (Array.isArray(input)) return input.map(canonical);
  if (input !== null && typeof input === "object") {
    return Object.fromEntries(Object.keys(input).sort().map((key) => [key, canonical(input[key])]));
  }
  return input;
}
if (!bytes.equals(Buffer.from(`${JSON.stringify(canonical(value))}\n`))) {
  throw new Error("source-test inventory is not canonical JSON");
}
if (JSON.stringify(Object.keys(value).sort()) !== JSON.stringify(["files", "schema", "source"]) ||
    value.schema !== 1 || value.source?.commit !== commit || value.source?.tree !== tree ||
    JSON.stringify(Object.keys(value.source ?? {}).sort()) !== JSON.stringify(["commit", "tree"]) ||
    !Array.isArray(value.files) || value.files.length !== 6) {
  throw new Error("source identity differs from the canonical workspace inventory");
}
let previous = "";
for (const file of value.files) {
  if (JSON.stringify(Object.keys(file).sort()) !== JSON.stringify(["bytes", "path", "sha256"]) ||
      typeof file.path !== "string" || file.path.length === 0 || isAbsolute(file.path) ||
      file.path.startsWith("../") || file.path.includes("/../") || file.path.includes("//") ||
      file.path <= previous || !Number.isSafeInteger(file.bytes) || file.bytes <= 0 ||
      !/^[0-9a-f]{64}$/.test(file.sha256)) {
    throw new Error("source-test inventory file entry is invalid");
  }
  previous = file.path;
  const path = join(workspace, file.path);
  const metadata = lstatSync(path);
  if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size !== file.bytes) {
    throw new Error(`source-test workspace member differs: ${file.path}`);
  }
  const actual = createHash("sha256").update(readFileSync(path)).digest("hex");
  if (actual !== file.sha256) throw new Error(`source-test workspace member differs: ${file.path}`);
}
NODE

    local expected actual expected_directories actual_directories
    expected="$workspace/.expected-files"
    actual="$workspace/.actual-files"
    expected_directories="$workspace/.expected-directories"
    actual_directories="$workspace/.actual-directories"
    artifact_rows | cut -f2 | LC_ALL=C sort > "$expected"
    printf '%s\n' "$INVENTORY_NAME" >> "$expected"
    LC_ALL=C sort -o "$expected" "$expected"
    find "$workspace" ! -type f ! -type d -print -quit | grep -q . &&
        fail "source-test workspace contains a nonregular member"
    find "$workspace" -type f \
        ! -name '.expected-files' ! -name '.actual-files' \
        ! -name '.expected-directories' ! -name '.actual-directories' \
        -print | sed "s#^$workspace/##" | LC_ALL=C sort > "$actual"
    cmp "$expected" "$actual" || fail "source-test workspace contains an undeclared member"
    printf '.\n' > "$expected_directories"
    while IFS=$'\t' read -r _ destination_path _; do
        local parent
        parent="$(dirname "$destination_path")"
        while [ "$parent" != . ]; do
            printf '%s\n' "$parent" >> "$expected_directories"
            parent="$(dirname "$parent")"
        done
    done < <(artifact_rows)
    LC_ALL=C sort -u -o "$expected_directories" "$expected_directories"
    find "$workspace" -type d -print |
        sed -e "s#^$workspace\$#.#" -e "s#^$workspace/##" |
        LC_ALL=C sort > "$actual_directories"
    cmp "$expected_directories" "$actual_directories" ||
        fail "source-test workspace contains an undeclared directory"
    rm "$expected" "$actual" "$expected_directories" "$actual_directories"
}

extract_workspace() {
    local source_root="$1"
    local archive="$2"
    source_root="$(canonical_directory "source root" "$source_root")"
    case "$archive" in /*) ;; *) fail "archive path must be absolute" ;; esac
    validate_regular_artifact "$archive" "source-test archive" >/dev/null

    local private workspace
    private="$(mktemp -d "${RUNNER_TEMP:-/tmp}/kandelo-exact-workspace-extract.XXXXXX")"
    EXACT_WORKSPACE_PRIVATE_ROOT="$private"
    workspace="$private/workspace"
    mkdir -p "$workspace"
    tar --zstd --no-same-owner --no-same-permissions -xf "$archive" -C "$workspace"
    validate_extracted_workspace "$source_root" "$workspace"

    local destination_path parent component
    while IFS=$'\t' read -r _ destination_path _; do
        [ ! -e "$source_root/$destination_path" ] && [ ! -L "$source_root/$destination_path" ] ||
            fail "source-test destination already exists: $destination_path"
        parent="$(dirname "$destination_path")"
        component="$source_root"
        IFS='/' read -r -a parts <<< "$parent"
        for component_name in "${parts[@]}"; do
            [ "$component_name" = . ] && continue
            component="$component/$component_name"
            if [ -L "$component" ]; then
                fail "source-test destination parent is a symbolic link: $parent"
            fi
            if [ -e "$component" ] && [ ! -d "$component" ]; then
                fail "source-test destination parent is not a directory: $parent"
            fi
        done
    done < <(artifact_rows)
    [ ! -e "$source_root/$INVENTORY_NAME" ] && [ ! -L "$source_root/$INVENTORY_NAME" ] ||
        fail "source-test inventory destination already exists"

    while IFS=$'\t' read -r _ destination_path _; do
        mkdir -p "$source_root/$(dirname "$destination_path")"
        cp -- "$workspace/$destination_path" "$source_root/$destination_path"
    done < <(artifact_rows)
    cp -- "$workspace/$INVENTORY_NAME" "$source_root/$INVENTORY_NAME"
    cleanup_private_root
}

[ "$#" -ge 1 ] || usage
command_name="$1"
shift
if [ "$command_name" = list ]; then
    [ "$#" -eq 0 ] || usage
    artifact_rows
    exit 0
fi
case "$command_name" in pack|extract) ;; *) usage ;; esac

source_root=""
archive=""
while [ "$#" -gt 0 ]; do
    case "$1" in
        --source-root)
            [ "$#" -ge 2 ] && [ -z "$source_root" ] || usage
            source_root="$2"
            shift 2
            ;;
        --archive)
            [ "$#" -ge 2 ] && [ -z "$archive" ] || usage
            archive="$2"
            shift 2
            ;;
        *) usage ;;
    esac
done
[ -n "$source_root" ] && [ -n "$archive" ] || usage

case "$command_name" in
    pack) pack_workspace "$source_root" "$archive" ;;
    extract) extract_workspace "$source_root" "$archive" ;;
esac
