[package]
name = "wgpu-window"
version = "0.0.0"
edition = "2021"

[dependencies]
wgpu = { version = "=30.0.1", default-features = false, features = ["std", "parking_lot", "gles", "wgsl"] }
winit = { version = "=0.30.13", default-features = false, features = ["rwh_06", "wayland"] }
pollster = "0.4"

[profile.release]
panic = "abort"

[workspace]
