/*
 * posix_spawn() for wasm32posix — non-forking implementation.
 *
 * Marshals argv + envp + file actions + spawn attributes into a single
 * contiguous blob and issues SYS_SPAWN. The kernel allocates a child pid,
 * builds the child process descriptor (with attrs and file actions
 * already applied), and the host launches a fresh worker — no fork, no
 * fork rewind, no exec replay.
 *
 * Wire format and design rationale:
 *   docs/plans/2026-05-04-non-forking-posix-spawn-design.md (Section 1).
 *
 * SYS_SPAWN channel args:
 *   arg0 = path_ptr        (caller memory; PATH-resolved by posix_spawnp)
 *   arg1 = path_len        (no NUL terminator counted)
 *   arg2 = blob_ptr        (caller memory)
 *   arg3 = blob_len
 *   arg4 = pid_out_ptr     (kernel writes child pid here on success)
 *   arg5 = 0               (reserved)
 *
 * Kernel returns 0 on success / -errno on failure. POSIX requires
 * posix_spawn() to return errno directly (not via the global errno), so
 * we negate the kernel return on the failure path.
 */

#define _GNU_SOURCE
#include <spawn.h>
#include <signal.h>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "../fdop.h"
#include "spawn_contract.h"

/* The blob carries musl's public spawn flags without translation. Keep the
 * separately-owned POSIX header values pinned to the generated wire contract
 * so a libc update cannot silently change the transported bits. Only the
 * subset documented by the kernel is implemented today. */
_Static_assert(POSIX_SPAWN_RESETIDS == WASM_POSIX_SPAWN_ATTR_RESETIDS,
	"POSIX_SPAWN_RESETIDS drifted from the spawn wire contract");
_Static_assert(POSIX_SPAWN_SETPGROUP == WASM_POSIX_SPAWN_ATTR_SETPGROUP,
	"POSIX_SPAWN_SETPGROUP drifted from the spawn wire contract");
_Static_assert(POSIX_SPAWN_SETSIGDEF == WASM_POSIX_SPAWN_ATTR_SETSIGDEF,
	"POSIX_SPAWN_SETSIGDEF drifted from the spawn wire contract");
_Static_assert(POSIX_SPAWN_SETSIGMASK == WASM_POSIX_SPAWN_ATTR_SETSIGMASK,
	"POSIX_SPAWN_SETSIGMASK drifted from the spawn wire contract");
_Static_assert(POSIX_SPAWN_SETSCHEDPARAM == WASM_POSIX_SPAWN_ATTR_SETSCHEDPARAM,
	"POSIX_SPAWN_SETSCHEDPARAM drifted from the spawn wire contract");
_Static_assert(POSIX_SPAWN_SETSCHEDULER == WASM_POSIX_SPAWN_ATTR_SETSCHEDULER,
	"POSIX_SPAWN_SETSCHEDULER drifted from the spawn wire contract");
_Static_assert(POSIX_SPAWN_USEVFORK == WASM_POSIX_SPAWN_ATTR_USEVFORK,
	"POSIX_SPAWN_USEVFORK drifted from the spawn wire contract");
_Static_assert(POSIX_SPAWN_SETSID == WASM_POSIX_SPAWN_ATTR_SETSID,
	"POSIX_SPAWN_SETSID drifted from the spawn wire contract");

/* WHY: record sizes alone cannot detect a same-size field reorder. These
 * relationships pin musl's encoder to every generated byte offset while
 * keeping C's exact integer widths independently checked. */
_Static_assert(sizeof(uint32_t) == WASM_POSIX_SPAWN_STRING_OFFSET_BYTES,
	"spawn string-offset width must match uint32_t");
_Static_assert(WASM_POSIX_SPAWN_HEADER_ARGC_OFFSET == 0,
	"spawn header argc must begin the record");
_Static_assert(WASM_POSIX_SPAWN_HEADER_ENVC_OFFSET
	== WASM_POSIX_SPAWN_HEADER_ARGC_OFFSET + sizeof(uint32_t),
	"spawn header envc offset drifted");
_Static_assert(WASM_POSIX_SPAWN_HEADER_ACTION_COUNT_OFFSET
	== WASM_POSIX_SPAWN_HEADER_ENVC_OFFSET + sizeof(uint32_t),
	"spawn header action-count offset drifted");
_Static_assert(WASM_POSIX_SPAWN_HEADER_ATTR_FLAGS_OFFSET
	== WASM_POSIX_SPAWN_HEADER_ACTION_COUNT_OFFSET + sizeof(uint32_t),
	"spawn header attr-flags offset drifted");
_Static_assert(WASM_POSIX_SPAWN_HEADER_PGRP_OFFSET
	== WASM_POSIX_SPAWN_HEADER_ATTR_FLAGS_OFFSET + sizeof(uint32_t),
	"spawn header pgrp offset drifted");
_Static_assert(WASM_POSIX_SPAWN_HEADER_PAD_OFFSET
	== WASM_POSIX_SPAWN_HEADER_PGRP_OFFSET + sizeof(int32_t),
	"spawn header pad offset drifted");
_Static_assert(WASM_POSIX_SPAWN_HEADER_SIGDEF_OFFSET
	== WASM_POSIX_SPAWN_HEADER_PAD_OFFSET + sizeof(uint32_t),
	"spawn header sigdef offset drifted");
_Static_assert(WASM_POSIX_SPAWN_HEADER_SIGMASK_OFFSET
	== WASM_POSIX_SPAWN_HEADER_SIGDEF_OFFSET + sizeof(uint64_t),
	"spawn header sigmask offset drifted");
_Static_assert(WASM_POSIX_SPAWN_HEADER_BYTES
	== WASM_POSIX_SPAWN_HEADER_SIGMASK_OFFSET + sizeof(uint64_t),
	"spawn header size no longer covers every field");

_Static_assert(WASM_POSIX_SPAWN_ACTION_OP_OFFSET == 0,
	"spawn action op must begin the record");
_Static_assert(WASM_POSIX_SPAWN_ACTION_FD_OFFSET
	== WASM_POSIX_SPAWN_ACTION_OP_OFFSET + sizeof(uint32_t),
	"spawn action fd offset drifted");
_Static_assert(WASM_POSIX_SPAWN_ACTION_NEWFD_OFFSET
	== WASM_POSIX_SPAWN_ACTION_FD_OFFSET + sizeof(int32_t),
	"spawn action newfd offset drifted");
_Static_assert(WASM_POSIX_SPAWN_ACTION_PATH_OFF_OFFSET
	== WASM_POSIX_SPAWN_ACTION_NEWFD_OFFSET + sizeof(int32_t),
	"spawn action path-off offset drifted");
_Static_assert(WASM_POSIX_SPAWN_ACTION_PATH_LEN_OFFSET
	== WASM_POSIX_SPAWN_ACTION_PATH_OFF_OFFSET + sizeof(uint32_t),
	"spawn action path-len offset drifted");
_Static_assert(WASM_POSIX_SPAWN_ACTION_OFLAG_OFFSET
	== WASM_POSIX_SPAWN_ACTION_PATH_LEN_OFFSET + sizeof(uint32_t),
	"spawn action oflag offset drifted");
_Static_assert(WASM_POSIX_SPAWN_ACTION_MODE_OFFSET
	== WASM_POSIX_SPAWN_ACTION_OFLAG_OFFSET + sizeof(int32_t),
	"spawn action mode offset drifted");
_Static_assert(WASM_POSIX_SPAWN_ACTION_RECORD_BYTES
	== WASM_POSIX_SPAWN_ACTION_MODE_OFFSET + sizeof(uint32_t),
	"spawn action size no longer covers every field");

/* Matches the definition in libc/glue/channel_syscall.c — all six syscall args
 * are passed as long long (i64). Declaring them as plain `long` produces
 * an i32-vs-i64 signature mismatch at link time on wasm32. */
extern long __syscall6(long n, long long a1, long long a2, long long a3,
                       long long a4, long long a5, long long a6);

static const posix_spawnattr_t empty_attr;
static const posix_spawn_file_actions_t empty_fa;

static int checked_add_size(size_t lhs, size_t rhs, size_t *out)
{
	if (rhs > SIZE_MAX - lhs) return E2BIG;
	*out = lhs + rhs;
	return 0;
}

static int checked_mul_size(size_t lhs, size_t rhs, size_t *out)
{
	if (lhs != 0 && rhs > SIZE_MAX / lhs) return E2BIG;
	*out = lhs * rhs;
	return 0;
}

static void store_u32(uint8_t *bytes, size_t offset, uint32_t value)
{
	memcpy(bytes + offset, &value, sizeof(value));
}

static void store_i32(uint8_t *bytes, size_t offset, int32_t value)
{
	memcpy(bytes + offset, &value, sizeof(value));
}

static void store_u64(uint8_t *bytes, size_t offset, uint64_t value)
{
	memcpy(bytes + offset, &value, sizeof(value));
}

/* Count and size a NULL-terminated argv-style array without allowing either
 * arithmetic wraparound or a protocol count beyond the generated parser cap. */
static int scan_strings(char *const *list, unsigned max_count,
	unsigned *out_count, size_t *out_bytes)
{
	unsigned count = 0;
	size_t total = 0;
	if (list) {
		while (list[count]) {
			if (count >= max_count) return E2BIG;
			size_t len = strlen(list[count]);
			if (len == SIZE_MAX || checked_add_size(total, len + 1, &total))
				return E2BIG;
			count++;
		}
	}
	*out_count = count;
	*out_bytes = total;
	return 0;
}

/* Walk the fdop list to count actions and total path bytes that need to
 * land in the strings region. Path strings are stored once each, NUL-
 * terminated.
 *
 * NOTE on traversal direction: musl's `posix_spawn_file_actions_add*`
 * helpers PREPEND new entries (`op->next = fa->__actions; fa->__actions
 * = op;`), so iterating from `__actions` via `next` walks the list in
 * REVERSE insertion order. POSIX requires file actions to be applied in
 * insertion order, so the emit-side walk uses `op->prev` from the tail
 * — see `emit_actions`. The count/scan walk direction doesn't matter
 * (we only need totals). */
static int scan_actions(struct fdop *head, unsigned *out_count,
	size_t *out_path_bytes)
{
	unsigned n = 0;
	size_t path_bytes = 0;
	for (struct fdop *op = head; op; op = op->next) {
		if (n >= WASM_POSIX_SPAWN_MAX_ACTION_COUNT) return E2BIG;
		n++;
		if (op->cmd == FDOP_OPEN || op->cmd == FDOP_CHDIR) {
			size_t path_len = strlen(op->path);
			if (path_len >= WASM_POSIX_PATH_MAX_BYTES)
				return ENAMETOOLONG;
			if (checked_add_size(path_bytes, path_len + 1, &path_bytes))
				return E2BIG;
		}
	}
	*out_count = n;
	*out_path_bytes = path_bytes;
	return 0;
}

/* Translate musl's FDOP_* code into the wire-format op code. */
static unsigned wire_op_for(int cmd) {
	switch (cmd) {
	case FDOP_OPEN:   return WASM_POSIX_SPAWN_OP_OPEN;
	case FDOP_CLOSE:  return WASM_POSIX_SPAWN_OP_CLOSE;
	case FDOP_DUP2:   return WASM_POSIX_SPAWN_OP_DUP2;
	case FDOP_CHDIR:  return WASM_POSIX_SPAWN_OP_CHDIR;
	case FDOP_FCHDIR: return WASM_POSIX_SPAWN_OP_FCHDIR;
	default:          return (unsigned)-1;
	}
}

/* Reduce sigset_t to the kernel's 64-bit signal-mask convention (signals
 * 1..64 in low-order bits). musl's sigset_t is opaque here, so peek at
 * the first 8 bytes — same approach the kernel uses for setitimer/etc. */
static uint64_t sigset_to_u64(const sigset_t *s) {
	uint64_t v = 0;
	memcpy(&v, s, sizeof(v) <= sizeof(*s) ? sizeof(v) : sizeof(*s));
	return v;
}

int posix_spawn(pid_t *restrict res, const char *restrict path,
	const posix_spawn_file_actions_t *fa,
	const posix_spawnattr_t *restrict attr,
	char *const argv[restrict], char *const envp[restrict])
{
	if (!path) return EINVAL;
	if (strlen(path) >= WASM_POSIX_PATH_MAX_BYTES) return ENAMETOOLONG;

	const posix_spawnattr_t *a = attr ? attr : &empty_attr;
	const posix_spawn_file_actions_t *f = fa ? fa : &empty_fa;

	/* Resolve envp default: if the caller passed NULL, use environ. */
	extern char **__environ;
	char *const *env = envp ? envp : (char *const *)__environ;

	unsigned argc = 0;
	unsigned envc = 0;
	unsigned n_actions = 0;
	size_t argv_bytes = 0;
	size_t envp_bytes = 0;
	size_t action_path_bytes = 0;
	int error = scan_strings(argv, WASM_POSIX_SPAWN_MAX_ARGV_COUNT,
		&argc, &argv_bytes);
	if (error) return error;
	error = scan_strings(env, WASM_POSIX_SPAWN_MAX_ENVP_COUNT,
		&envc, &envp_bytes);
	if (error) return error;
	error = scan_actions((struct fdop *)f->__actions,
		&n_actions, &action_path_bytes);
	if (error) return error;

	/* ARG_MAX includes both string bytes and the source pointer arrays,
	 * including their two terminating NULL entries. */
	size_t pointer_count;
	size_t pointer_bytes;
	size_t metadata_bytes;
	if (checked_add_size((size_t)argc, (size_t)envc, &pointer_count)
	    || checked_add_size(pointer_count, 2, &pointer_count)
	    || checked_mul_size(pointer_count, sizeof(char *), &pointer_bytes)
	    || checked_add_size(argv_bytes, envp_bytes, &metadata_bytes)
	    || checked_add_size(metadata_bytes, pointer_bytes, &metadata_bytes))
		return E2BIG;
	if (metadata_bytes > WASM_POSIX_ARG_MAX_BYTES) return E2BIG;

	size_t header_bytes = WASM_POSIX_SPAWN_HEADER_BYTES;
	size_t argv_off_bytes;
	size_t envp_off_bytes;
	size_t actions_bytes;
	size_t strings_bytes;
	size_t blob_len;
	if (checked_mul_size((size_t)argc,
		WASM_POSIX_SPAWN_STRING_OFFSET_BYTES, &argv_off_bytes)
	    || checked_mul_size((size_t)envc,
		WASM_POSIX_SPAWN_STRING_OFFSET_BYTES, &envp_off_bytes)
	    || checked_mul_size((size_t)n_actions,
		WASM_POSIX_SPAWN_ACTION_RECORD_BYTES, &actions_bytes)
	    || checked_add_size(argv_bytes, envp_bytes, &strings_bytes)
	    || checked_add_size(strings_bytes, action_path_bytes, &strings_bytes)
	    || checked_add_size(header_bytes, argv_off_bytes, &blob_len)
	    || checked_add_size(blob_len, envp_off_bytes, &blob_len)
	    || checked_add_size(blob_len, actions_bytes, &blob_len)
	    || checked_add_size(blob_len, strings_bytes, &blob_len))
		return E2BIG;
	if (blob_len > WASM_POSIX_SPAWN_WIRE_MAX_BYTES) return E2BIG;

	/* Allocate on the heap; alloca() of unbounded size is unsafe and
	 * fork-instrument's switch-dispatch interacts poorly with large
	 * stack frames in spawn-heavy programs. The blob is short-lived. */
	uint8_t *blob = malloc(blob_len);
	if (!blob) return ENOMEM;

	/* ── Header ── */
	store_u32(blob, WASM_POSIX_SPAWN_HEADER_ARGC_OFFSET, argc);
	store_u32(blob, WASM_POSIX_SPAWN_HEADER_ENVC_OFFSET, envc);
	store_u32(blob, WASM_POSIX_SPAWN_HEADER_ACTION_COUNT_OFFSET, n_actions);
	store_u32(blob, WASM_POSIX_SPAWN_HEADER_ATTR_FLAGS_OFFSET,
		(uint32_t)a->__flags);
	store_i32(blob, WASM_POSIX_SPAWN_HEADER_PGRP_OFFSET,
		(int32_t)a->__pgrp);
	store_u32(blob, WASM_POSIX_SPAWN_HEADER_PAD_OFFSET, 0);
	uint64_t sigdef  = sigset_to_u64(&a->__def);
	uint64_t sigmask = sigset_to_u64(&a->__mask);
	store_u64(blob, WASM_POSIX_SPAWN_HEADER_SIGDEF_OFFSET, sigdef);
	store_u64(blob, WASM_POSIX_SPAWN_HEADER_SIGMASK_OFFSET, sigmask);

	/* ── Offsets tables + strings region ──
	 *
	 * Argv strings come first in `strings`, then envp, then action
	 * paths. Each block is packed: NUL-terminated, no padding. */
	uint8_t  *argv_offs = blob + header_bytes;
	uint8_t  *envp_offs = blob + header_bytes + argv_off_bytes;
	uint8_t  *actions   =  blob + header_bytes + argv_off_bytes + envp_off_bytes;
	uint8_t  *strings   =  actions + actions_bytes;

	uint32_t cursor = 0;
	for (unsigned i = 0; i < argc; i++) {
		size_t n = strlen(argv[i]) + 1;
		memcpy(strings + cursor, argv[i], n);
		store_u32(argv_offs,
			(size_t)i * WASM_POSIX_SPAWN_STRING_OFFSET_BYTES, cursor);
		cursor += (uint32_t)n;
	}
	for (unsigned i = 0; i < envc; i++) {
		size_t n = strlen(env[i]) + 1;
		memcpy(strings + cursor, env[i], n);
		store_u32(envp_offs,
			(size_t)i * WASM_POSIX_SPAWN_STRING_OFFSET_BYTES, cursor);
		cursor += (uint32_t)n;
	}

	/* ── Action records (POSIX-required INSERTION order) ──
	 *
	 * musl's `posix_spawn_file_actions_add*` helpers prepend to the
	 * linked list, so `fa->__actions` is the most-recently-added entry
	 * and the list is reverse-insertion order. To emit insertion
	 * order, walk to the tail first, then iterate via `prev`.
	 *
	 * Wire-format `record.fd` and `record.newfd` map to musl's fdop fields
	 * differently per op:
	 *   * DUP2: record.fd  = op->srcfd (source)
	 *           record.newfd = op->fd  (target)
	 *   * CLOSE/OPEN/FCHDIR: record.fd = op->fd
	 *                       record.newfd = unused (0)
	 *   * CHDIR: both unused (0); only `path` carries information.
	 *
	 * The kernel parser (`crates/kernel/src/spawn.rs::parse_blob`) reads
	 * the same two slots for every op and dispatches via the op code, so
	 * mis-encoding here would silently corrupt DUP2 actions. */
	struct fdop *tail = (struct fdop *)f->__actions;
	if (tail) {
		while (tail->next) tail = tail->next;
	}
	unsigned ai = 0;
	for (struct fdop *op = tail; op; op = op->prev) {
		uint8_t *record = actions
			+ ai * WASM_POSIX_SPAWN_ACTION_RECORD_BYTES;
		store_u32(record, WASM_POSIX_SPAWN_ACTION_OP_OFFSET,
			wire_op_for(op->cmd));
		if (op->cmd == FDOP_DUP2) {
			store_i32(record, WASM_POSIX_SPAWN_ACTION_FD_OFFSET,
				op->srcfd); /* record.fd = source */
			store_i32(record, WASM_POSIX_SPAWN_ACTION_NEWFD_OFFSET,
				op->fd); /* record.newfd = target */
		} else {
			store_i32(record, WASM_POSIX_SPAWN_ACTION_FD_OFFSET,
				op->fd);
			store_i32(record, WASM_POSIX_SPAWN_ACTION_NEWFD_OFFSET, 0);
		}
		uint32_t path_off = 0;
		uint32_t path_len = 0;
		if (op->cmd == FDOP_OPEN || op->cmd == FDOP_CHDIR) {
			path_off = cursor;
			path_len = (uint32_t)strlen(op->path) + 1;
			memcpy(strings + cursor, op->path, path_len);
			cursor += path_len;
		}
		store_u32(record, WASM_POSIX_SPAWN_ACTION_PATH_OFF_OFFSET,
			path_off);
		store_u32(record, WASM_POSIX_SPAWN_ACTION_PATH_LEN_OFFSET,
			path_len);
		store_i32(record, WASM_POSIX_SPAWN_ACTION_OFLAG_OFFSET,
			op->oflag);
		store_u32(record, WASM_POSIX_SPAWN_ACTION_MODE_OFFSET,
			(uint32_t)op->mode);
		ai++;
	}

	/* ── Issue SYS_SPAWN ── */
	pid_t pid_out = 0;
	long ret = __syscall6(
		WASM_POSIX_SYS_SPAWN,
		(long long)(uintptr_t)path,
		(long long)strlen(path),
		(long long)(uintptr_t)blob,
		(long long)blob_len,
		(long long)(uintptr_t)&pid_out,
		0LL
	);

	free(blob);

	if (ret < 0) {
		/* POSIX: posix_spawn returns the errno directly, doesn't set errno. */
		return (int)-ret;
	}
	if (res) *res = pid_out;
	return 0;
}
