script_path = "packages/registry/lua/build-lua.sh"
repo_url    = "https://github.com/brandonpayton/wasm-posix-kernel.git"
commit      = "d32e6e34d2a81eeac77a67818a8e1ef51305e704"
revision    = 1

[binary]
index_url = "https://github.com/brandonpayton/wasm-posix-kernel/releases/download/binaries-abi-v{abi}/index.toml"

