#!/usr/bin/env bash
set -euo pipefail

# Build SQLite testfixture for wasm32-posix-kernel.
#
# testfixture is a custom tclsh linked with SQLite test internals.
# It runs SQLite's upstream TCL-based test suite (~1,159 test files).
#
# Prerequisites:
#   - bash packages/registry/tcl/build-tcl.sh (provides libtcl8.6.a)
#   - bash packages/registry/sqlite/build-sqlite.sh (provides amalgamation)
#
# Output: packages/registry/sqlite/bin/testfixture.wasm

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SYSROOT="$REPO_ROOT/sysroot"
TCL_INSTALL="$SCRIPT_DIR/../tcl/tcl-install"
SQLITE_SRC="$SCRIPT_DIR/sqlite-src"
SQLITE_FULL="$SCRIPT_DIR/sqlite-full-src"
ZLIB_INSTALL="$SCRIPT_DIR/../zlib/zlib-install"
BUILD_DIR="$SCRIPT_DIR/testfixture-build"
SQLITE_VERSION="${SQLITE_VERSION:-3.49.1}"
SQLITE_MAX_COMPOUND_SELECT="${SQLITE_MAX_COMPOUND_SELECT:-50}"
SQLITE_MAX_EXPR_DEPTH="${SQLITE_MAX_EXPR_DEPTH:-100}"
SQLITE_JSON_MAX_DEPTH="${SQLITE_JSON_MAX_DEPTH:-100}"

sqlite_packed_version() {
    local major minor patch
    IFS=. read -r major minor patch _ <<<"$SQLITE_VERSION"
    printf "%d%02d%02d00" "$major" "$minor" "${patch:-0}"
}

# --- Prerequisites ---
if ! command -v wasm32posix-cc &>/dev/null; then
    echo "ERROR: wasm32posix-cc not found. Run 'npm link' in sdk/ first." >&2
    exit 1
fi

if [ ! -f "$TCL_INSTALL/lib/libtcl8.6.a" ]; then
    echo "ERROR: libtcl8.6.a not found. Run: bash packages/registry/tcl/build-tcl.sh" >&2
    exit 1
fi

if [ ! -f "$SQLITE_SRC/sqlite3.c" ]; then
    echo "ERROR: SQLite amalgamation not found. Run: bash packages/registry/sqlite/build-sqlite.sh" >&2
    exit 1
fi

if [ ! -d "$SQLITE_FULL/src" ]; then
    SQLITE_PACKED="$(sqlite_packed_version)"
    SQLITE_FULL_SOURCE_URL="${SQLITE_FULL_SOURCE_URL:-https://www.sqlite.org/2025/sqlite-src-${SQLITE_PACKED}.zip}"
    echo "==> Downloading full SQLite source for upstream tests..."
    TMP_ZIP="/tmp/sqlite-full-${SQLITE_PACKED}.zip"
    TMP_DIR="/tmp/sqlite-full-${SQLITE_PACKED}"
    rm -rf "$TMP_DIR"
    curl --retry 10 --retry-delay 5 --retry-max-time 300 --retry-all-errors -fsSL \
        "$SQLITE_FULL_SOURCE_URL" -o "$TMP_ZIP"
    unzip -q "$TMP_ZIP" -d "$TMP_DIR"
    inner="$(find "$TMP_DIR" -mindepth 1 -maxdepth 1 -type d -name 'sqlite-src-*' | head -1)"
    if [ -z "$inner" ]; then
        echo "ERROR: could not find sqlite-src-* directory in $TMP_ZIP" >&2
        exit 1
    fi
    rm -rf "$SQLITE_FULL"
    mv "$inner" "$SQLITE_FULL"
    rm -rf "$TMP_DIR" "$TMP_ZIP"
fi

PATCH_DIR="$SCRIPT_DIR/patches"
if [ -d "$PATCH_DIR" ]; then
    echo "==> Applying SQLite testfixture patches..."
    for patch_file in "$PATCH_DIR"/*.patch; do
        [ -f "$patch_file" ] || continue
        patch_name="$(basename "$patch_file")"
        if (cd "$SQLITE_FULL" && git apply -p0 --check "$patch_file") >/dev/null 2>&1; then
            echo "  Applying $patch_name..."
            (cd "$SQLITE_FULL" && git apply -p0 "$patch_file")
        elif (cd "$SQLITE_FULL" && git apply -p0 --reverse --check "$patch_file") >/dev/null 2>&1; then
            echo "  $patch_name already applied"
        else
            echo "ERROR: $patch_name does not apply cleanly" >&2
            exit 1
        fi
    done
fi

export WASM_POSIX_SYSROOT="$SYSROOT"

# --- Generate required headers ---
# The test files include sqliteInt.h which needs parse.h, opcodes.h,
# and sqlite_cfg.h. These are normally generated by SQLite's build system.
# We extract them from the amalgamation.
mkdir -p "$BUILD_DIR"

# parse.h — token constants (TK_*)
echo "==> Generating parse.h..."
grep '^#define TK_' "$SQLITE_SRC/sqlite3.c" > "$BUILD_DIR/parse.h"

# opcodes.h — opcode constants (OP_*)
echo "==> Generating opcodes.h..."
grep '^#define OP_' "$SQLITE_SRC/sqlite3.c" > "$BUILD_DIR/opcodes.h"

# sqlite_cfg.h — empty (normally generated by configure)
echo "==> Generating sqlite_cfg.h..."
echo "/* Generated stub */" > "$BUILD_DIR/sqlite_cfg.h"

cd "$BUILD_DIR"

# Common CFLAGS for the testfixture build. Keep recursive SQL limits aligned
# with the shipped library so the tests observe the supported configuration.
CFLAGS=(
    -O2
    -DSQLITE_TEST=1
    -DSQLITE_CRASH_TEST=1
    -DSQLITE_CORE
    -DSQLITE_THREADSAFE=1
    -DSQLITE_NO_SYNC=1
    -DSQLITE_ENABLE_SETLK_TIMEOUT=2
    -DSQLITE_MAX_COMPOUND_SELECT="$SQLITE_MAX_COMPOUND_SELECT"
    -DSQLITE_MAX_EXPR_DEPTH="$SQLITE_MAX_EXPR_DEPTH"
    -DSQLITE_JSON_MAX_DEPTH="$SQLITE_JSON_MAX_DEPTH"
    -DHAVE_PREAD=1
    -DHAVE_PWRITE=1
    -DSQLITE_OMIT_LOAD_EXTENSION
    -DSQLITE_ENABLE_FTS3
    -DSQLITE_ENABLE_FTS3_PARENTHESIS
    -DSQLITE_ENABLE_FTS4
    -DSQLITE_ENABLE_FTS5
    -DSQLITE_ENABLE_RTREE
    -DSQLITE_ENABLE_GEOPOLY
    -DSQLITE_ENABLE_JSON1
    -DSQLITE_ENABLE_STMTVTAB
    -DSQLITE_ENABLE_DBPAGE_VTAB
    -DSQLITE_ENABLE_BYTECODE_VTAB
    -DSQLITE_ENABLE_DBSTAT_VTAB
    -DSQLITE_ENABLE_MATH_FUNCTIONS
    -DSQLITE_ENABLE_COLUMN_METADATA
    -DSQLITE_ENABLE_STAT4
    -DSQLITE_ENABLE_DESERIALIZE
    -DSQLITE_CKSUMVFS_STATIC
    -DSQLITE_STATIC_RANDOMJSON
    -DSQLITE_STRICT_SUBTYPE=1
    -DSQLITE_SERIES_CONSTRAINT_VERIFY=1
    -DSQLITE_DEFAULT_PAGE_SIZE=1024
    -DSQLITE_SERVER=1
    -DBUILD_sqlite
    -DTCLSH_INIT_PROC=sqlite3TestInit
    -DTCLSH=1
    -I"$BUILD_DIR"
    -I"$SQLITE_FULL/src"
    -I"$SQLITE_SRC"
    -I"$TCL_INSTALL/include"
    -I"$SQLITE_FULL/ext/fts3"
    -I"$SQLITE_FULL/ext/rtree"
    -I"$SQLITE_FULL/ext/recover"
    -I"$SQLITE_FULL/ext/session"
    -I"$ZLIB_INSTALL/include"
)

# SQLite's recursive test cases need more than wasm-ld's default 64 KiB shadow
# stack. Use 1 MiB without reviving the old 2 GiB maximum-memory workaround.
TESTFIXTURE_LDFLAGS=(
    -Wl,-z,stack-size=1048576
)

# TESTSRC — test C files (excluding test_thread.c)
TESTSRC_FILES=(
    "$SQLITE_FULL/src/test1.c"
    "$SQLITE_FULL/src/test2.c"
    "$SQLITE_FULL/src/test3.c"
    "$SQLITE_FULL/src/test4.c"
    "$SQLITE_FULL/src/test5.c"
    "$SQLITE_FULL/src/test6.c"
    "$SQLITE_FULL/src/test8.c"
    "$SQLITE_FULL/src/test9.c"
    "$SQLITE_FULL/src/test_autoext.c"
    "$SQLITE_FULL/src/test_backup.c"
    "$SQLITE_FULL/src/test_bestindex.c"
    "$SQLITE_FULL/src/test_blob.c"
    "$SQLITE_FULL/src/test_btree.c"
    "$SQLITE_FULL/src/test_config.c"
    "$SQLITE_FULL/src/test_delete.c"
    "$SQLITE_FULL/src/test_demovfs.c"
    "$SQLITE_FULL/src/test_devsym.c"
    "$SQLITE_FULL/src/test_fs.c"
    "$SQLITE_FULL/src/test_func.c"
    "$SQLITE_FULL/src/test_hexio.c"
    "$SQLITE_FULL/src/test_init.c"
    "$SQLITE_FULL/src/test_intarray.c"
    "$SQLITE_FULL/src/test_journal.c"
    "$SQLITE_FULL/src/test_malloc.c"
    "$SQLITE_FULL/src/test_md5.c"
    "$SQLITE_FULL/src/test_multiplex.c"
    "$SQLITE_FULL/src/test_mutex.c"
    "$SQLITE_FULL/src/test_onefile.c"
    "$SQLITE_FULL/src/test_osinst.c"
    "$SQLITE_FULL/src/test_pcache.c"
    "$SQLITE_FULL/src/test_quota.c"
    "$SQLITE_FULL/src/test_rtree.c"
    "$SQLITE_FULL/src/test_schema.c"
    "$SQLITE_FULL/src/test_superlock.c"
    "$SQLITE_FULL/src/test_syscall.c"
    "$SQLITE_FULL/src/test_tclsh.c"
    "$SQLITE_FULL/src/test_tclvar.c"
    # test_thread.c — excluded, requires pthreads
    "$SQLITE_FULL/src/test_vdbecov.c"
    "$SQLITE_FULL/src/test_vfs.c"
    "$SQLITE_FULL/src/test_window.c"
    "$SQLITE_FULL/src/test_wsd.c"
    # Extension test files
    "$SQLITE_FULL/ext/fts3/fts3_term.c"
    "$SQLITE_FULL/ext/fts3/fts3_test.c"
    "$SQLITE_FULL/ext/session/test_session.c"
    "$SQLITE_FULL/ext/recover/sqlite3recover.c"
    "$SQLITE_FULL/ext/recover/dbdata.c"
    "$SQLITE_FULL/ext/recover/test_recover.c"
    "$SQLITE_FULL/ext/intck/test_intck.c"
    "$SQLITE_FULL/ext/intck/sqlite3intck.c"
    "$SQLITE_FULL/ext/rbu/test_rbu.c"
    # Statically linked extensions
    "$SQLITE_FULL/ext/expert/sqlite3expert.c"
    "$SQLITE_FULL/ext/expert/test_expert.c"
    "$SQLITE_FULL/ext/misc/amatch.c"
    "$SQLITE_FULL/ext/misc/appendvfs.c"
    "$SQLITE_FULL/ext/misc/basexx.c"
    "$SQLITE_FULL/ext/misc/carray.c"
    "$SQLITE_FULL/ext/misc/cksumvfs.c"
    "$SQLITE_FULL/ext/misc/closure.c"
    "$SQLITE_FULL/ext/misc/csv.c"
    "$SQLITE_FULL/ext/misc/decimal.c"
    "$SQLITE_FULL/ext/misc/eval.c"
    "$SQLITE_FULL/ext/misc/explain.c"
    "$SQLITE_FULL/ext/misc/fileio.c"
    "$SQLITE_FULL/ext/misc/fuzzer.c"
    "$SQLITE_FULL/ext/fts5/fts5_tcl.c"
    "$SQLITE_FULL/ext/fts5/fts5_test_mi.c"
    "$SQLITE_FULL/ext/fts5/fts5_test_tok.c"
    "$SQLITE_FULL/ext/misc/ieee754.c"
    "$SQLITE_FULL/ext/misc/mmapwarm.c"
    "$SQLITE_FULL/ext/misc/nextchar.c"
    "$SQLITE_FULL/ext/misc/normalize.c"
    "$SQLITE_FULL/ext/misc/percentile.c"
    "$SQLITE_FULL/ext/misc/prefixes.c"
    "$SQLITE_FULL/ext/misc/qpvtab.c"
    "$SQLITE_FULL/ext/misc/randomjson.c"
    "$SQLITE_FULL/ext/misc/regexp.c"
    "$SQLITE_FULL/ext/misc/remember.c"
    "$SQLITE_FULL/ext/misc/series.c"
    "$SQLITE_FULL/ext/misc/spellfix.c"
    "$SQLITE_FULL/ext/misc/stmtrand.c"
    "$SQLITE_FULL/ext/misc/totype.c"
    "$SQLITE_FULL/ext/misc/unionvtab.c"
    "$SQLITE_FULL/ext/misc/wholenumber.c"
    "$SQLITE_FULL/ext/misc/zipfile.c"
    "$SQLITE_FULL/ext/rtree/test_rtreedoc.c"
)

# --- Compile all source files to .o ---
# Compile the amalgamation with SQLITE_PRIVATE= (empty) so that internal
# functions are visible to the test files (which reference them as extern).
# Without this, the amalgamation defines them as static.
echo "==> Compiling SQLite amalgamation..."
wasm32posix-cc -c "${CFLAGS[@]}" -DSQLITE_PRIVATE= "$SQLITE_SRC/sqlite3.c" -o sqlite3.o

echo "==> Compiling tclsqlite.c..."
wasm32posix-cc -c "${CFLAGS[@]}" "$SQLITE_FULL/src/tclsqlite.c" -o tclsqlite.o

echo "==> Compiling test source files (${#TESTSRC_FILES[@]} files)..."
OBJ_FILES=(sqlite3.o tclsqlite.o)
NPROC="$(sysctl -n hw.ncpu 2>/dev/null || nproc)"
COMPILE_JOBS=0

for src in "${TESTSRC_FILES[@]}"; do
    base="$(basename "$src" .c)"
    # Handle name collisions from different directories
    dir="$(basename "$(dirname "$src")")"
    obj="${dir}_${base}.o"
    wasm32posix-cc -c "${CFLAGS[@]}" "$src" -o "$obj" &
    OBJ_FILES+=("$obj")
    COMPILE_JOBS=$((COMPILE_JOBS + 1))
    if [ "$COMPILE_JOBS" -ge "$NPROC" ]; then
        wait
        COMPILE_JOBS=0
    fi
done
wait

# Compile stubs for excluded test modules
echo "==> Compiling wasm stubs..."
wasm32posix-cc -c "${CFLAGS[@]}" "$SCRIPT_DIR/wasm_stubs.c" -o wasm_stubs.o
OBJ_FILES+=(wasm_stubs.o)

echo "==> Linking testfixture (${#OBJ_FILES[@]} object files)..."
wasm32posix-cc "${CFLAGS[@]}" \
    "${OBJ_FILES[@]}" \
    -L"$TCL_INSTALL/lib" -ltcl8.6 \
    -L"$ZLIB_INSTALL/lib" -lz \
    "${TESTFIXTURE_LDFLAGS[@]}" \
    -o testfixture

if [ ! -f testfixture ]; then
    echo "ERROR: Link failed — testfixture not found" >&2
    exit 1
fi

# --- Fork instrumentation ---
# TCL's exec command uses fork(). Many SQLite tests use exec.
# wasm-fork-instrument auto-discovers fork paths via call-graph analysis —
# no onlylist needed. Must run last — it hardcodes mutable-global offsets
# and any later pass reordering globals would corrupt the fork buffer.
FORK_INSTRUMENT="$REPO_ROOT/scripts/run-wasm-fork-instrument.sh"
echo "==> Applying fork instrumentation..."
"$FORK_INSTRUMENT" testfixture -o testfixture.instr
mv testfixture.instr testfixture

# --- Install ---
mkdir -p "$SCRIPT_DIR/bin"
cp testfixture "$SCRIPT_DIR/bin/testfixture.wasm"

echo "==> testfixture built successfully!"
ls -lh "$SCRIPT_DIR/bin/testfixture.wasm"
echo ""
echo "Run a test with:"
echo "  TCL_LIBRARY=\$TCL_INSTALL/lib/tcl8.6 KERNEL_CWD=\$SQLITE_FULL \\"
echo "    npx tsx examples/run-example.ts testfixture test/select1.test"
