#!/usr/bin/env bash
#
# Build libhubbub (libhubbub.a) for wasm32-posix-kernel with the NetSurf
# build system. See scripts/netsurf-library-build.sh for how and why.
#
# Two generated sources:
#   - src/tokeniser/entities.inc is generated by upstream's
#     build/make-entities.pl (Perl, from the dev shell).
#   - src/treebuilder/autogenerated-element-type.c needs gperf, which the dev
#     shell does not provide. src/autogenerated-element-type.c in this
#     package is upstream's gperf output, committed; its header explains why
#     and how to regenerate it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../../../scripts/netsurf-library-build.sh"

# sha256 of the element-type.gperf that src/autogenerated-element-type.c was
# generated from.
ELEMENT_TYPE_GPERF_SHA256="bf3ad6526a27954b11718b877844a8591530af1994061b37dca7c6e101574611"

netsurf_library_setup "$SCRIPT_DIR" libhubbub 0.3.8 \
    8ac1e6f5f3d48c05141d59391719534290c59cd029efc249eb4fdbac102cd5a5
netsurf_library_require_dep libparserutils lib/libparserutils.a
netsurf_library_stage_source

# Install the pre-generated table only when it still describes this source.
# A stale table would silently mis-classify elements the new release added.
TREEBUILDER_DIR="$NETSURF_SRC_DIR/src/treebuilder"
actual_gperf_sha256="$(shasum -a 256 "$TREEBUILDER_DIR/element-type.gperf" | awk '{print $1}')"
if [ "$actual_gperf_sha256" != "$ELEMENT_TYPE_GPERF_SHA256" ]; then
    echo "ERROR: libhubbub element-type.gperf changed (sha256 $actual_gperf_sha256)." >&2
    echo "       Regenerate packages/registry/libhubbub/src/autogenerated-element-type.c" >&2
    echo "       as its header describes, then update ELEMENT_TYPE_GPERF_SHA256." >&2
    exit 1
fi
# Copying after staging makes the table newer than element-type.gperf, so
# make treats upstream's gperf rule as already satisfied.
cp "$SCRIPT_DIR/src/autogenerated-element-type.c" \
    "$TREEBUILDER_DIR/autogenerated-element-type.c"
touch "$TREEBUILDER_DIR/autogenerated-element-type.c"

netsurf_library_make_install
netsurf_library_install
