# CMake toolchain identity for Kandelo's wasm32 POSIX SDK.
set(CMAKE_SYSTEM_NAME Kandelo)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(CMAKE_C_COMPILER wasm32posix-cc)
set(CMAKE_CXX_COMPILER wasm32posix-c++)
set(CMAKE_AR wasm32posix-ar)
set(CMAKE_RANLIB wasm32posix-ranlib)
set(CMAKE_NM wasm32posix-nm)
set(CMAKE_STRIP wasm32posix-strip)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")

if(DEFINED ENV{WASM_POSIX_SYSROOT})
  set(CMAKE_SYSROOT "$ENV{WASM_POSIX_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH "$ENV{WASM_POSIX_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
