/*
 * Gate for the Qt host generator flake.nix builds itself. qtbase compiles
 * qtwaylandscanner only where it finds Wayland::Scanner, and it looks for
 * that only `if(LINUX)` (src/tools/configure.cmake:5), so nixpkgs' darwin
 * qtbase ships neither the tool nor its Qt6WaylandScannerTools CMake
 * package and a Qt Wayland cross-build stops at
 *   Failed to find the host tool "Qt6::qtwaylandscanner".
 * The derivation in flake.nix closes that gap from qtbase's own source.
 *
 * Two halves, because a cross-build needs both: the CMake package must
 * answer the restricted find_package of QtToolHelpers.cmake:740, and the
 * tool itself must generate the Qt glue. The probe project owns the first,
 * this file runs it and owns the second.
 *
 * QT_HOST_PATH and cmake come from flake.nix, so this exercises the real
 * dev-shell toolchain — the CLAUDE.md vitest gate runs inside
 * scripts/dev-shell.sh. Outside it the test skips, like the sibling
 * wayland-protocols-scanner test.
 */
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";

import { afterAll, describe, expect, it } from "vitest";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "../..");
const PROBE = join(REPO_ROOT, "nix/qtwaylandscanner/test");
const XDG_SHELL = join(
  REPO_ROOT,
  "packages/registry/wayland-protocols/xml/xdg-shell.xml",
);

function hostQtVersion(): string | null {
  if (!process.env.QT_HOST_PATH) return null;
  try {
    return execFileSync("qmake", ["-query", "QT_VERSION"], {
      encoding: "utf8",
    }).trim();
  } catch {
    return null;
  }
}

const QT_VERSION = hostQtVersion();
const workDirs: string[] = [];

afterAll(() => {
  for (const dir of workDirs) rmSync(dir, { recursive: true, force: true });
});

function configureProbe(version: string): string {
  const build = mkdtempSync(join(tmpdir(), "qtwaylandscanner-probe-"));
  workDirs.push(build);
  return execFileSync(
    "cmake",
    ["-S", PROBE, "-B", build, `-DQT_HOST_VERSION=${version}`],
    { encoding: "utf8" },
  );
}

describe("qtwaylandscanner — the Qt host generator flake.nix builds", () => {
  it.skipIf(!QT_VERSION)(
    "answers the cross-build lookup for Qt6WaylandScannerTools",
    () => {
      const out = configureProbe(QT_VERSION!);
      expect(out, out).toContain("QTWAYLANDSCANNER_OK");
    },
  );

  it.skipIf(!QT_VERSION)("generates the Qt glue for xdg-shell", () => {
    const out = configureProbe(QT_VERSION!);
    const scanner = out.match(/QTWAYLANDSCANNER_OK (\S+)/)?.[1];
    expect(scanner).toBeTruthy();

    const header = execFileSync(scanner!, ["client-header", XDG_SHELL], {
      encoding: "utf8",
    });
    expect(header).toContain("// This file was generated by qtwaylandscanner");
    expect(header).toContain("class  xdg_wm_base");
    expect(header).toContain("class  xdg_toplevel");
  });
});
